### ISSUE TITLE
Default OpenMM platform?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#101]
It looks like `oldrepex` currently selects the `CPU` platform as default if none is specified.

The problem is that, if we want to allow users to select their own platform of choice, we either have to have this everywhere:

```
if platform:
   context = openmm.Context(system, integrator, platform)
else:
   context = openmm.Context(system, integrator)
```

or we have to select a platform of some sort.

`Context()` will automatically select the fastest platform available by default (using a very simple scheme in which each platform that can be successfully loaded just has a speed number assigned).  I wonder if I can just use this to create a `Context` and destroy it after figuring out what `Platform` was instantiated.

**Comment by Lnaden** [comment]
Fixed by #518
