### ISSUE TITLE
Malformed html file from yank analyze report

### ISSUE THREAD

**Issue by sgill2** [choderalab/yank#1049]
With 0.23.1 I'm finding that outputting html files directly using `yank analyze report -s ./-o some.html` results in strangely formed html files. If I first output an ipython notebook and then convert it using `jupyter nbconvert`, however, then the resulting html file is normal.

Here's a zip file ([yankhtml.zip](https://github.com/choderalab/yank/files/2224423/yankhtml.zip))
 containing the example outputs from an experiment:
- direct.html is the html output directly using `yank analyze report`
- output.ipynb is the ipython notebook output from `yank analyze report`
- indirect.html is the html file generated using `jupyter nbconvert` on the `output.ipynb`

**Comment by Lnaden** [comment]
See #1037 

I added a `--format` flag to the command line because the multi-analysis output files become ambiguous since the target becomes a directory instead of a single file. So I force you to specify instead of infering

**Comment by sgill2** [comment]
Thanks! That worked.

Maybe the docs could be updated to reflect that change? http://getyank.org/latest/analysis.html#visual-analysis

**Comment by Lnaden** [comment]
Huh.. I missed that section when I was fixing the docs for the multi-analyze. I'll fix that. Thanks for the suggestion. Once I get the PR for that, I'll close this as part of it.
