### ISSUE TITLE
where to get input file to calculate energy

### ISSUE THREAD

**Issue by naveenmeena584** [choderalab/yank#1058]
hi,

i just want to know can i directly download pdb file from protein data bank  for receptor or i have to do some modification before starting with yank and which format of ligand it support, it should be mol2 only.

**Comment by andrrizzi** [comment]
Hi. We support pdb files for peptides, and mol2, sdf, SMILES for small molecules. The PDB should have all the residues, although you can use the recent [`pdbfixer` feature](http://getyank.org/latest/yamlpages/molecules.html#pdbfixer) to add them automatically. The hydrogens will be added by tleap, so make sure that the protein residue names adhere to the AMBER conventions for amino acids with multiple possible protonation states.
