### ISSUE TITLE
Cache minimization and energies of identical configurations to speed up setup

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#107]
If we are minimizing or computing energies for the same configurations, we should cache these values to speed up setup.

**Comment by jchodera** [comment]
Memoization?

**Comment by pgrinaway** [comment]
Should this issue (and its resolution) be in repex instead?

**Comment by pgrinaway** [comment]
I'm going to wait until we decide on what we are doing re: repex and yank 1.0, and proceed from there.

**Comment by jchodera** [comment]
Sounds good.  The MPI-only structure of the `repex` project might actually make this difficult.

**Comment by jchodera** [comment]
Actually, scratch that.  It shouldn't be any more difficult to implement in `repex`.

**Comment by jchodera** [comment]
Actually, memoization will not work here, since each alchemical state will have a different potential function, and would lead to a different minimized conformation and energy.
