### ISSUE TITLE
mpi4py symbol error

### ISSUE THREAD

**Issue by dtmoustakas** [choderalab/yank#1070]
Hi all,

When I try running a yank job using MPI on my ubuntu 16.04 system, I get the following error:

ImportError: /home/ubuntu/miniconda3/lib/python3.6/site-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so: undefined symbol: MPI_UNWEIGHTED

I'm using the miniconda3 python and mpi executables, and serial jobs run fine on this system.  I've tried reinstalling mpi4py via pip and conda, with no success.  Has anyone else encountered this before?

Thanks!

**Comment by dtmoustakas** [comment]
quick update - on this system, I had forgotten to update LD_LIBRARY_PATH to be ~/miniconda3/lib

that seems to have fixed the problem, I'll post again if it fails, but it seems to be working now

**Comment by jchodera** [comment]
Let us know if you have further trouble! Sometimes, having both system- and conda-installed MPICH versions can cause problems if you have paths set incorrectly!
