### ISSUE TITLE
Fresh conda install of YANK uses OpenMPI implementation instead of MPICH

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#1080]
Our `build_mpirun_configfile` utility works only with MPICH so I'm thinking about adding an explicit `mpich` dependency on the `clusterutils` conda recipe rather than adding it to YANK, which in principle should work with both implementations, and let conda solve the package specifications.

**Comment by jchodera** [comment]
+1!

**Comment by andrrizzi** [comment]
This was addressed with the new `clusterutils` build. See omnia-md/conda-recipes#937 .
