### ISSUE TITLE
How to compute Free Energy for different number of iterations

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#1095]
Hi there, I'm sorry to bother you. I have some questions. I have the Yank directory and I would like to analyze it in chunks e.g. suppose that I've run 1000 Yank iterations and I want to see how the free energy was changing during the whole run. So, I want to calculate the binding affinity between 0-100 yank iterations, 0-200 yank iterations etc. How can I do it by using the Yank API?  A little code snippet will be enough.

Thanks a lot Gaetano

**Comment by davidlmobley** [comment]
CC @elkhoury (she was wondering about this at some point).

**Comment by nividic** [comment]
@andrrizzi Thanks that worked for me
