### ISSUE TITLE
ExperimentBuilder should configure by default MCDisplacement/Rotation atom_subset

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#1098]
I've just realized that the `mcmc_moves` block doesn't treat specially the constructor argument `atom_subset` of `MCDisplacementMove` and `MCRotationMove`. This means that when the YAML specification doesn't contain a list of atom indices, the default is used (`None`), and the move tries to perform a rigid rotation/translation of the whole system instead of the ligand.

In the future, we'll want to integrate this with the region system, but for now, I'll implement a fix to use the ligand atoms when `atom_subset` is not given.

**Comment by jchodera** [comment]
Yikes! Thanks!

**Comment by jchodera** [comment]
Can we also have MCDisplacement / rotation send success rates and initial atom index sets to the logger? I don't think it currently does this, so it was easy to miss that this wasn't working?

**Comment by andrrizzi** [comment]
Will do the change in `openmmtools`!

**Comment by andrrizzi** [comment]
We save the success rates in the netcdf file btw, in case you're interested and you didn't know.
