### ISSUE TITLE
Add nose test that tests examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#110]
It would be great to automatically test that the examples run via nosetests.

**Comment by jchodera** [comment]
Each example directory should have a `test.sh` file that runs just one iteration so that we can test that all the examples at least *run* using travis.

Here's an example:
https://github.com/choderalab/yank/blob/master/examples/p-xylene-implicit/test.sh

**Comment by andrrizzi** [comment]
This is implemented [here](https://github.com/choderalab/yank/blob/208ed03a4586dc2c143c6759edbdc14d6341d90a/Yank/tests/test_examples.py). Closing.
