### ISSUE TITLE
Add explicit solvent tests

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#111]

**Comment by andrrizzi** [comment]
Is this a duplicate of #151?

**Comment by Lnaden** [comment]
Are these the tests you were thinking of?

https://github.com/choderalab/yank/blob/master/Yank/tests/test_yaml.py#L1301

https://github.com/choderalab/yank/blob/master/Yank/tests/test_yaml.py#L1415

**Comment by jchodera** [comment]
I think this can be closed!
