### ISSUE TITLE
Refactor alchemical factory to use PME offset feature

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1111]
We can greatly speed up energy calculations for exact PME by adding support for the recently-added [`offset` feature](https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/NonbondedForce.h#L452-L516) in OpenMM 7.3 to openmmtools.

(Adding this here for tracking purposes)

**Comment by andrrizzi** [comment]
No refactoring required! The `AlchemicalState` should hide the changes in the implementation details.
