### ISSUE TITLE
0.24.0 release

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1146]
@andrrizzi : What do you think about the following release plans?
- [x] Cut a 0.24.0 release (status file support) and a new conda package that requires `openmmtools >=0.17.0`
- [x] Cut a new `openmmtools` 0.18.0 release now that multistate samplers were brought in with https://github.com/choderalab/openmmtools/pull/398
- [ ] Switch `yank` to use the the multistate samplers from `openmmtools >=0.18.0` for a planned 0.25.0 release; test extensively before release in case we need to go to `openmmtools` 0.18.1

If this sounds good to you, I can start this process under your supervision.

**Comment by andrrizzi** [comment]
Sounds like a plan! We might as well add a warning in `multistate.__init__()` deprecating the module before releasing 0.24.0.

**Comment by jchodera** [comment]
Sounds good! Can you add that deprecation warning, @andrrizzi ?

**Comment by andrrizzi** [comment]
Will do!

**Comment by jchodera** [comment]
@andrrizzi : While you're working on adding multistate sampler tests to `openmmtools`, can you also make the changes here to `yank` to switch to using those multistate samplers, just so we don't get confused and edit anything here?

**Comment by andrrizzi** [comment]
Sounds good! To be clear, @hannahbrucemacdonald already ported the multistate sampler tests to openmmtools. I'm just adding another one specific to #1130 .

**Comment by jchodera** [comment]
Yes, of course! We had never created MPI tests for those classes.
