### ISSUE TITLE
Switch from Langevin dynamics to GHMC

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#115]

**Comment by kyleabeauchamp** [comment]
Can I tag this as a 2.0 milestone given the substantial performance penalty associated with GHMC and the fact that we will eventually re-visit optimizing GHMC?

**Comment by jchodera** [comment]
I'm going to take one more look at this for 1.0 before we definitely decide to bump to 2.0.

**Comment by Lnaden** [comment]
Move to 2.0

**Comment by jchodera** [comment]
We're now using BAOAB (#754), which has small enough configuration space error as to no longer require GHMC.
