### ISSUE TITLE
Reading NetCDF file for replica exchange runs

### ISSUE THREAD

**Issue by garrettameek** [choderalab/yank#1150]
Hello,

I'm interested in using the "test_sampling" example (https://github.com/choderalab/yank/blob/master/Yank/tests/test_sampling.py) as a template for running replica exchange simulations.  I've been able to use this example to successfully run replica exchange simulations and generate a NETCDF file as output.  Afterward, I've attempted to extract trajectory run information from the NETCDF file with the _analyze.dispatch_extract_trajectory()_ command, as follows:

_analyze.dispatch_extract_trajectory({'--checkpoint': 'test_storage_checkpoint.nc','--fulltraj': True,'--netcdf': 'test_storage.nc',
    '--output': 'traj1','--replica': 1,'--trajectory': 1,'--state': 1,'extract-trajectory': True,'--discardequil': False,'--distcutoff': None,
    '--end': None,'--energycutoff': None,'--format': None,'--serial': None,'--skip': None,'--skipunbiasing': True,'--start': None,
    '--imagemol': None,'--nosolvent': None,'--verbose': False})_

I get the following error message:

**python REMD_script.py > REMD_script.out**
_Traceback (most recent call last):
  File "REMD_script.py", line 92, in <module>
    '--imagemol': None,'--nosolvent': None,'--verbose': False})
  File "/mnt/d/software/anaconda3/lib/python3.7/site-packages/yank/commands/analyze.py", line 206, in dispatch_extract_trajectory
    trajectory = analyze.extract_trajectory(nc_path, **kwargs)
  File "/mnt/d/software/anaconda3/lib/python3.7/site-packages/yank/analyze.py", line 1072, in extract_trajectory
    reference_system = mmtools.utils.deserialize(metadata['reference_state']).system
KeyError: 'reference_state'_

I've tried printing metadata to see if I can understand the source of the problem.  Unfortunately, I'm uncertain whether the problem is related to the format of the 'metadata' dictionary, the composition of my NETCDF output file, or the input arguments I use to call _analyze.dispatch_extract_trajectory()_ (among other possibilities)?

My end goal is to identify a transferable procedure for extracting individual replica exchange trajectory data from the NETCDF file for further analysis.

Attached is a PDF file with the contents of the input script "REMD_script.py".
[REMD_script.pdf](https://github.com/choderalab/yank/files/2958752/REMD_script.pdf)

Thanks in advance for your help!

-Garrett

**Comment by andrrizzi** [comment]
Hi Garrett! The code in the `cli.py` module is just a wrapper for the command line and it's not the most user friendly. The library function is `yank.analyze.extract_trajectory()` and the [docstring](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L1035-L1074) should be much cleaner.

In general, however, that function was created to analyze YANK data, which adds extra metadata in the netcdf file. In particular, `extract_trajectory` needs a topology and to know whether the system is periodic or not. YANK reads it from the metadata, but you can just modify [these lines](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L1086-L1092) of that function to something like

```python
topology = PDBFile('mypdb.pdb').topology
is_periodic = True  # If you used PME.
```
and the function should work fine.

**Comment by garrettameek** [comment]
Hi Andrea,  

Thanks for your response!  As you indicated, I was referencing the incorrect version of "analyze.py" (was referencing the version in commands sub-directory).  After referencing the correct function I'm able to extract trajectories (in MDTraj format), however, I've had problems writing output files with certain formats, and had the following questions:

1.  Is the extract_trajectory function expected to work for systems that are **not** periodic?
2.  Are you aware of any limitations in the _trajectory_ object that is extracted from replica exchange output, in comparison with a standard mdtraj _trajectory_? Or would you expect the replica-exchange-generated version to have all the same properties as a trajectory object loaded from file (.pdb, .xtc, .h5, etc.) with mdtraj.load()?  (I've been able to write them in .xtc or .hdf5 format, but am unable to write trajectory objects to either .pdb or .xyz files at the moment.
2.  In order to extract the trajectory MDTraj is needed.  I've had some difficulty running select versions of Python (3.6,3.7) when I simultaneously import Yank, MDTraj, and OpenMM.  Have you found any particular Python version to be compatible with all of these?  So far I've found Python2.7 to be quasi-compatible with all three packages, but I'd prefer to use a version of python3 if possible.
3.  I understand how to use the MultiStateReporter to store output in NETCDF format, and then extract individual trajectory information from this file after the simulations are complete.  However, I was wondering if you can direct me to an example that shows how to use the MultiStateReporter (or a different function) to report the energies for individual trajectories **during the replica exchange simulation run**?
[REMD_script.pdf](https://github.com/choderalab/yank/files/2980361/REMD_script.pdf)

Thanks again for your help!

-Garrett

**Comment by andrrizzi** [comment]
Hi @garrettameek !

1. Yes, it should work. If your system is periodic, I'd suggest you set `extract_trajectory(image_molecuels=True)`.
2. I'm not aware of particular limitations. What are you observing exactly?
3. Hmm, it sounds like you have a conda environment problem. How are you installing YANK? When you install with `conda install yank`, `conda` should be able to figure out which combinations of packages are compatible with each other. We support Python 3.6 and 3.7.
4. You should be able to just run another Python script and use `MultiStateReporter('netcdf_file.nc', open_mode='r').read_energies()` while repex is running.

Hope this helps.

**Comment by garrettameek** [comment]
Hi @andrrizzi,

Thanks again for your help!

2.  Your answer to question 1 also resolved question 2.

3.  I was trying to use MDTraj with Python3.5 (because of a suggestion in installation notes) but it seems to work fine with Python3.7 when I install through conda.  Thanks for the suggestion!
