### ISSUE TITLE
Relative paths don't validate if yank is executed from a parent directory

### ISSUE THREAD

**Issue by jaimergp** [choderalab/yank#1163]
I am working through the examples in `yank-examples` and tried to do the following:

```
git clone https://github.com/choderalab/yank-examples
cd yank-examples
yank script --yaml=examples/binding/abl-imatinib/explicit.yaml
```

, which led me to this error:

``` 
===========================
== Small Molecule Schema ==
filepath:
- File is not one of frozenset({'csv', 'mol2', 'smiles', 'sdf'})
- File path input/2HYY-pdbfixer.pdb does not exist.

===========================

===========================
====== Peptide Schema =====
filepath:
- File path input/2HYY-pdbfixer.pdb does not exist.

```

Even though YAML considers relative input paths as discussed in #334, and the code [still reflects](https://github.com/choderalab/yank/blob/master/Yank/experiment.py#L695) that decision, seems that the validators [do not follow](https://github.com/jaimergp/yank/blob/master/Yank/schema/validator.py#L44-L52) that principle. I can't think of an easy way to pass the script base directory around, maybe adding a `_secret` global key to the dictionary returned by `yaml.load` before doing the validation to have that basedir around when needed?

**Comment by andrrizzi** [comment]
Nice catch! It might be easier to just call
```python
with moltools.utils.temporary_cd(self._script_dir):
    ...  # Call all validate options
```
right before validating the YAML syntax.

**Comment by jaimergp** [comment]
Nice, I am preparing a PR.

What entries in the YAML file can accept `filepath` keys? `molecules` is one of them, but are there any other keys that can point to external files?
