### ISSUE TITLE
Switch to double precision by default; add command-line precision option

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#118]
We should use double precision by default, since otherwise we may not achieve the necessary target accuracy for larger systems.  We can let the user set the precision with a command-line option.

Later, we can potentially add an `auto` model that tests energetics for the system in various precision modes and automatically selects the one for which potential energies are accurate to better than 0.1kT.

**Comment by Lnaden** [comment]
This should have been fixed by #441
