### ISSUE TITLE
yank , openmm and python version

### ISSUE THREAD

**Issue by sawstory** [choderalab/yank#1183]
Hi
i am trying to use yank for binding affinity calculation. my openmm 7.4 work well, but when i installed yank using conda as instruction says , yank did not work when i test it and give the following error, it seems that only python 3.6 is supported, if this is the case should i uninstall python 3.7 and install both openmm 7.4 and yank on python 3.6?
Thanks
![Screenshot from 2019-09-18 20-34-22](https://user-images.githubusercontent.com/50192860/65213581-5b746f00-daaf-11e9-8905-5ac3534d4346.png)

**Comment by andrrizzi** [comment]
Hi @sawstory . Could you post your conda environment? That problem was supposedly fixed both in YANK and OpenMMTools in 0.24.1 and 0.18.2 respectively. Python 3.7 should be supported, although we used to have problems shipping the osx version recently.

**Comment by sawstory** [comment]
This issue also resolved for me when I installed yank in separate environment, Thanks :)
