### ISSUE TITLE
Error running mpiexec.hydra

### ISSUE THREAD

**Issue by jadeshi** [choderalab/yank#1184]
Hi,
I'm trying to run the T4-lysozyme example across multiple GPUs via SLURM. I made the following configfile:

-np 1 -env CUDA_VISIBLE_DEVICES 0 yank script --yaml=p-xylene-explicit.yaml
-np 1 -env CUDA_VISIBLE_DEVICES 1 yank script --yaml=p-xylene-explicit.yaml
-np 1 -env CUDA_VISIBLE_DEVICES 2 yank script --yaml=p-xylene-explicit.yaml
-np 1 -env CUDA_VISIBLE_DEVICES 3 yank script --yaml=p-xylene-explicit.yaml

and submission script:

#!/bin/bash
#SBATCH --job-name=yank
#SBATCH --output=yank.out
#SBATCH --error=yank.err
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:4
#SBATCH --time=999:00:00

mpiexec.hydra -configfile configfile 

I installed mpi4py version 3.0.0 prior to this via conda, and I confirmed that the mpiexec.hydra executable being called is the one from conda. However, when I try to submit, I get an error:

**[mpiexec@node015] mpiexec_get_parameters (../../../../../src/pm/i_hydra/mpiexec/mpiexec_params.c:1233): assert (my_argv[1] != NULL) failed
[mpiexec@node015] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1745): error parsing parameters**

Wondering what this means and how to fix it. Thanks!

**Comment by andrrizzi** [comment]
Hi @jadeshi . HPC systems and MPI can have frustrating differences so I'm not sure I can help. From the error, I suspect your `mpiexec.hydra` call doesn't make it to YANK.

On our cluster, we generate config files that look like this
```
-np 1 -env CUDA_VISIBLE_DEVICES 0 yank --yaml=my_script.yaml :
-np 1 -env CUDA_VISIBLE_DEVICES 1 yank --yaml=my_script.yaml
```
note the colon at the end of the line. We also usually pass a `hostfile`, not just a configuration file. It may also a problem with your MPI local installation.

Hope this helps!

**Comment by jadeshi** [comment]
Yeah, I think you're right, the problem was that the configfile information wasn't getting read for some reason. I was able to get it to run by just pasting the configfile lines into the SLURM script itself separated by colons. Thanks for the help!

**Comment by andrrizzi** [comment]
No problem!
