### ISSUE TITLE
yank analyze, pymbar error

### ISSUE THREAD

**Issue by jadeshi** [choderalab/yank#1185]
Hi,
I'm running a protein+ligand system starting from a .prmtop and .inpcrd file I prepared using ambertools, and the FEP simulation seems to have completed all iterations successfully. However, when I run the analysis part, "yank analyze --store=experiments", I'm getting an error from pymbar:

pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 0.999809. 19 other columns have similar problems

Does this suggest that something went wrong during the FEP portion, even though the job seemed to complete successfully?

Alternatively, would it be possible to have pymbar ignore this error, since this is so close to 1 anyway that it possibly may not make a big difference?

Thanks!

**Comment by mrshirts** [comment]
That pymbar error usually indicates very poor overlap between alchemical states.  Can you look at the work distribution from states i->i+1 and i->i-1 for each state.

**Comment by andrrizzi** [comment]
Hi @jadeshi . It would also help if you could post the YAML file you used to run the calculation.

**Comment by jadeshi** [comment]
@andrrizzi Here's the yaml file I used. I based it off of the T4-lysozyme example:

options:
  minimize: yes
  verbose: yes
  temperature: 300*kelvin
  pressure: 1*atmosphere 
  platform: OpenCL
  output_dir: output
  
solvents:
  PME:
    nonbonded_method: PME
    nonbonded_cutoff: 1*nanometer
    switch_distance: 0.9*nanometer
    ewald_error_tolerance: 0.0003
    clearance: 10*angstroms
    positive_ion: Na+
    negative_ion: Cl-

systems:
  complex:
    phase1_path: [output.prmtop, output.inpcrd]
    phase2_path: [output.prmtop, output.inpcrd]
    ligand_dsl: resname LIG
    solvent: PME

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
        lambda_restraints:     [0.00, 0.25, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.90, 0.80, 0.70, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]

experiments:
  system: complex
  protocol: absolute-binding
  restraint:
    type: Harmonic

**Comment by andrrizzi** [comment]
Hi @jadeshi. It looks like there's no specification for the number of iterations. The default is 1 (see http://getyank.org/latest/yamlpages/options.html#default-number-of-iterations) so you're getting that error because MBAR simply doesn't have enough data to work with. You'll have to increase the number of iterations. I'd do at least 1000, but depending on your system, you'll probably need more for convergence.

**Comment by jadeshi** [comment]
@andrrizzi Ah, okay thanks, I'll give that a try. Finally just wondering, is expected runtime linear with the number of iterations? The simulation I just ran took around a day, so I'm hoping running a proper one with 1000 iterations won't take 3 years :)

**Comment by andrrizzi** [comment]
Yes, the runtime is linear with the number of iterations. How big is your system and on which hardware are you running? On a single GPU, I'd be surprised to see iterations lasting more than a few minutes.

**Comment by jadeshi** [comment]
Hmm, actually looking at the output file more closely, I think it may have defaulted to 5000. Here's a snippet of my output file

**Comment by andrrizzi** [comment]
It looks like you're right, @jadeshi . The default was recently changed, but the docs were not updated. I've fixed the docs now.

Did the iterations complete both for the complex and solvent phases? And does YANK's analysis crash on that error or is it just a warning? I think it's worth checking what @mrshirts suggested then. You might have to few lambda windows.

**Comment by jadeshi** [comment]
@andrrizzi I think you're right about too few lambda windows, or maybe my system was not sufficiently equilibrated before running YANK. I tried setting the alchemical path determination to "auto", and it ended up assigning around 400 lambda windows for the solvent phase such that the expected runtime was over 100 days. Is this indicative of an issue with the system itself? 

Also I meant to ask this earlier, but is it fine if I use the same prmtop and inpcrd files (protein + ligand system solvated in a TIP3P water box) for phase_1 and phase_2?  I noticed in the examples that these are usually named differently.

Thanks!

**Comment by andrrizzi** [comment]
> around 400 lambda windows for the solvent phase

Hmm. I'd say that's a lot and quite uncommon. How big is your ligand?

> Is it fine if I use the same prmtop and inpcrd files (protein + ligand system solvated in a TIP3P water box) for phase_1 and phase_2?

I'm not sure I understand. For a double decoupling calculation to work you need to simulate a protein+ligand+solvent system and a ligand+solvent system so you need two pairs of prmtop and inpcrd files (one pair for each system). If you simulate twice the same system the final free energy difference should be 0.0 (unless it's not converged).

**Comment by jadeshi** [comment]
Ah okay, maybe that's the reason. I've been using a protein + ligand + solvent system for both the complex and solvent phases, and I was assuming that YANK would somehow ignore or remove the protein in the second phase. So for phase 2, I should use a system with just the ligand solvated in water?

**Comment by andrrizzi** [comment]
> So for phase 2, I should use a system with just the ligand solvated in water?

Correct. And the ligand should also have residue name `LIG` (according to your `ligand_dsl` string).

**Comment by jadeshi** [comment]
Okay, seems to work fine now. Managed to get both the FEP and analysis to work without issue, and the binding free energies seem reasonable compared to experiment. Thanks for all the help!

**Comment by andrrizzi** [comment]
Glad it's working now!
