### ISSUE TITLE
Fix docs on implicit solvent salt concentration option

### ISSUE THREAD

**Issue by Teohoho** [choderalab/yank#1200]
When trying to set a default salt concentration, using the syntax written in the manual:
(implicit_solvent_salt_concentration: 0.15 * moles / liter)
I encounter the following error:

    raise YamlParseError(error.format(solvent_id, yaml.dump(solvent_validator.errors)))
    yank.experiment.YamlParseError: Solvent 'GBSA' did not validate! Check the schema error below for details
    implicit_solvent_salt_concentration:
    - unknown field

It seems the syntax is off. Has it been updated in the source without the manual page being updated?

**Comment by andrrizzi** [comment]
Hi @Teohoho . It looks like the option has always been `implicit_solvent_salt_conc` and the docs was incorrect to begin with. Thanks for catching it.
