### ISSUE TITLE
NaN encountered with hydration example in document.

### ISSUE THREAD

**Issue by kexul** [choderalab/yank#1218]
Hi guys, I started my trial with Yank by following the [example](http://getyank.org/latest/tutorial.html#a-first-example-hydration-free-energy). But the simulation fails with NAN. 
Here is my input file, yaml file and logs. Any help is appreciated!
[file.zip](https://github.com/choderalab/yank/files/4419878/file.zip)

**Comment by andrrizzi** [comment]
Hi @kexul . There is always a non-zero probability that your simulation will NaN, although I find it weird in this case. You can try using a `LangevinDynamicsMove` rather than the default sampling method. See here: http://getyank.org/latest/tutorial.html#changing-sampling-method .

**Comment by kexul** [comment]
I'm struggling about NAN these days. Your advice is precious! Thank you so much @andrrizzi .
