### ISSUE TITLE
Simulations of molecular melt

### ISSUE THREAD

**Issue by kadiliissaar** [choderalab/yank#1221]
How could one use Yank to set up a molecular melt where instead of being surrounded by e.g. water, the molecules are surrounded by themselves?

**Comment by andrrizzi** [comment]
We never tested YANK on crystals, and you won't be able to use the automatic pipeline, but it should be possible in principle if you prepare your own system and feed it to YANK. The tutorial has a section on it (on top of the YAML documentation) here: http://getyank.org/latest/tutorial.html#when-the-automatic-pipeline-won-t-do .

**Comment by kadiliissaar** [comment]
Thank you! I am trying out the approach of importing parameter and coordinate files generated in gromacs. It seems I need yank.multistate module for this - how can I get this? I've been running a .yaml script from the terminal.

**Comment by andrrizzi** [comment]
`yank.multistate` has been moved to `openmmtools.multistate` in the last release. If you are getting an import error, I suggest you update your openmmtools installation.
