### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by aysegulcayir** [choderalab/yank#1233]
mport pandas as pd
df = pd.read_csv('Book1.csv',sep=';')
df =df.drop(['HQ REGION','HQ COUNTRY', 'HQ CITY'],axis = 1)

edu_list = ['school','university','academy','training','nursery','tuition','learning','education',
           'institute','institution']
NGO_list = ['not-for-profit','non-profit','^govern']

for index, row in df.iterrows():
    for i in edu_list:
        for j in NGO_list:
            if i in df.iloc[index,0].lower():
                df.iloc[index,10] = 'university/school'
                #print(df.iloc[index,10])
            
            elif (j in str(df.iloc[index,2]).lower()) or (j in str(df.iloc[index,6]).lower()):
                df.iloc[index,10] = 'government/non-profit'
            elif int(df.iloc[index,7][:4]) < 1990:
                df.iloc[index,10] = 'mature company'
            elif int(df.iloc[index,7][:4]) >= 1990:
                df.iloc[index,10] = 'startsup'
            else:
                df.iloc[index,10] = 'unclassified'
                
                
print(df.head())
print(df.TYPE.value_counts()) # Count the number of university/school, government/NGO, mature companies

df['TYPE'].isna().sum() # Total number of companies

# Number of start-ups = total number of companies - number of university/schools 
#                                                 - number of government/NGO
#                                                 - number of mature companies

# Number of Unclassified = 0

df.to_excel("output.xlsx")

error is 

  File "C:/Users/pc/Desktop/untitled0.py", line 42, in <module>
    elif int(df.iloc[index,7][:4]) < 1990:

IndexError: invalid index to scalar variable.

How do I fix it

**Comment by Lnaden** [comment]
This appears to be an issue with Pandas (https://pandas.pydata.org/), not YANK. Please post the issue there unless this is a copy paste mistake

**Comment by aysegulcayir** [comment]
but pandas already installed

**Comment by Lnaden** [comment]
That may be, but the code block you posted above appears to be example code for working with Pandas, and has no bearing on this project, YANK. As we are not the developers or affiliated with Pandas, and the code you posted has no association with YANK's functionality, there is not much we can do to help you here. I would recommend visiting the Pandas GitHub page and asking the question there so you can get assistance from the developers of that program to help resolve your issue.

**Comment by aysegulcayir** [comment]
Thank you for your response
