### ISSUE TITLE
Clean up Analyze

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#128]
There's a lot of really messed up code in analyze. For example, there is a non-member function with a self argument, most likely copy pasted from newrepex: https://github.com/choderalab/yank/blob/master/yank/analyze.py#L451

There's also some major tabbing issues (https://github.com/choderalab/yank/blob/master/yank/analyze.py#L478).

**Comment by kyleabeauchamp** [comment]
I think we still need another round of cleanup in analyze.  For example, we are using hand-written PDB writers that produce non-compliant PDBs.  We may need to backport some of my rewritten mdtraj-based analyze routines from newrepex.

**Comment by pgrinaway** [comment]
@kyleabeauchamp +1.

**Comment by kyleabeauchamp** [comment]
Can delete `compute_torsion_trajectories`

**Comment by kyleabeauchamp** [comment]
OK, this is probably done once we finalize #172
