### ISSUE TITLE
Run pyflakes

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#129]
Lots of unused imports, unused code, possible bugs could be fixed by a round of pyflakes.

**Comment by bas-rustenburg** [comment]
Any use for a tool such as landscape.io?

**Comment by kyleabeauchamp** [comment]
Let's do it manually for now, this is something that only needs to happen twice a year IMHO

**Comment by bas-rustenburg** [comment]
Ok! Has this been done since the issue was opened?

**Comment by kyleabeauchamp** [comment]
No, but it doesn't make sense to run pyflakes until we finish all the large scale code changes that are pending.  I generally run pyflakes when we're closer to a release.

**Comment by bas-rustenburg** [comment]
Understood.

**Comment by jchodera** [comment]
Marking this as `yank 1.0` so we remember to run this once before release.

**Comment by jchodera** [comment]
Duplicate of #13.
