### ISSUE TITLE
Failures due to API changes in `openmmtools`

### ISSUE THREAD

**Issue by mattwthompson** [choderalab/yank#1299]
See for example: https://github.com/openforcefield/openff-evaluator/actions/runs/4685350308/jobs/8302368552?pr=509

It looks like the import path changed in https://github.com/choderalab/openmmtools/pull/669 without complete re-exporting of the old paths

**Comment by ijpulidos** [comment]
@mattwthompson that's correct, that changed upstream, a quick fix here is doing the ugly `from openmmtools.utils.utils import find_subclass`. But maybe we just want the complete re-export of all the elements in `utils.py`upstream.

**Comment by mattwthompson** [comment]
Yup that's what I did - re-exporting everything again might be a good idea, though. It looks like that was attempted (mostly successfully) in that PR.

I'm mostly raising this because it breaks (some part of) Yank, which I can't patch and fire off a release of

**Comment by ijpulidos** [comment]
upstream https://github.com/choderalab/openmmtools/pull/698 was already merged and there's a new 0.23 release of openmmtools in conda-forge. This should be solved now.
