### ISSUE TITLE
Run pyflakes and pep8 (syntax checking and style checking)

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#13]
I'm finding a lot of hidden syntax errors via pyflakes...

**Comment by Lnaden** [comment]
We are running Quantified Code on this repo now, would that be considered sufficient or do we want to have actually syntax validation and ensuring that all code is reached by tests?

**Comment by andrrizzi** [comment]
I think QuantifiedCode is good enough for style and simple mistakes. I'd create a new issue (or rename this one) to remind us to add test coverage though. I think that's useful to have around.
