### ISSUE TITLE
Switch to external repositories for Repex and TestSystems (when they are ready)

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#14]
Also, this means that we shouldn't invest too much time cleaning up those files in the current Yank repo.

PS: I think TestSystems is pretty much ready to integrate, so that should happen first.

**Comment by Lnaden** [comment]
Touching for YANK 1.0 release, this will be something handled after 1.0

**Comment by Lnaden** [comment]
Considering how much has changed since this issue has opened. I think we can close this.
OpenMMTools now handles many of the external functions + we have vastly overhauled the sampler code with the SAMS branch
