### ISSUE TITLE
Change README.md to point to Amazon S3 documentation

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#141]
Once the Amazon S3 documentation is working, we should change the `README.md` to mostly contain a pointer to this documentation.

I'm not sure what the current status of this is, though. I'm not sure how to access the URL for the bucket, and also unsure of how to configure this to point to some sort of sane URL so we can have `http://choderalab.org/yank/` point to this.

**Comment by Lnaden** [comment]
Looks like this was fixed some time ago, front page references the getyank.org page
