### ISSUE TITLE
Allow control over more repex options via command line

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#143]
We may want a more general way to specify arbitrary `repex` options via the command line.

For example, the user may want to set `nsteps_per_iteration`, or any of the other attributed saved to `metadata`:
```
['collision_rate', 'constraint_tolerance', 'timestep', 'nsteps_per_iteration', 'number_of_iterations', 'equilibration_timestep', 'number_of_equilibration_iterations', 'title', 'minimize\
', 'replica_mixing_scheme', 'online_analysis', 'verbose', 'show_mixing_statistics'] 
```
I'm unsure of the easiest way to allow these to be specified, however, especially since some of them have to be converted to `simtk.unit.Quantity` objects.

**Comment by pgrinaway** [comment]
Just going through and cleaning up the issues to decide what we need to work on for 1.0--is there a consensus here?

**Comment by kyleabeauchamp** [comment]
I think we concluded YAML + 1.0

**Comment by jchodera** [comment]
Sounds good!

**Comment by andrrizzi** [comment]
This has been implemented. Closing.
