### ISSUE TITLE
Find and delete obsolete files

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#157]
Some python scripts may be obsolete.  We should either delete them or support them.  

For example, we have stuff in attic whose origin is unknown
https://github.com/choderalab/yank/blob/master/examples/attic/p-xylene/tests/decoupling-test.py

**Comment by Lnaden** [comment]
I'll handle this as part of the systembuild and pep8 cleanup

1.0 touch

**Comment by Lnaden** [comment]
With the removal of systembuilder in #718, this should be done
