### ISSUE TITLE
Change ligand selection to use MDTraj DSL

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#161]
We should change from having the user specify the ligand residue name to allow the user to specify the ligand atoms via the MDTraj DSL:
http://mdtraj.org/latest/atom_selection.html

Closing #96 to implement this.

**Comment by jchodera** [comment]
We discussed that it may make sense for @andrrizzi to attempt this.

**Comment by andrrizzi** [comment]
Can we close this? Is there anything else we must implement to address this?

**Comment by jchodera** [comment]
This is done!

I'd love to switch to a PyMOL-like syntax, though, since it could be much more powerful.  But that would involve implementing a PyMOL-like selection syntax in either MDTraj or parmed.
