### ISSUE TITLE
Switch to new mdtraj S3 bucket push mechanism

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#170]
See https://github.com/mdtraj/mdtraj/blob/master/devtools/ci/push-docs-to-s3.py

**Comment by jchodera** [comment]
I've restricted S3 permissions for the `choderalab` user to the S3 `yank` bucket only.  Let me know if this causes trouble.

Eventually, perhaps we want separate users for each travis project, e.g. `yank-travis` for this project?

**Comment by pgrinaway** [comment]
I think this broke stuff...

**Comment by pgrinaway** [comment]
I can't push from my local machine anymore

**Comment by pgrinaway** [comment]
Can we wait to change permissions until the other issues are sorted out?

**Comment by jchodera** [comment]
Apologies!  Let me revert.

**Comment by jchodera** [comment]
Reverted.

**Comment by pgrinaway** [comment]
Ok,  I'll test first on my local machine. It might be easier to just prohibit EC2 and not mess much with specific S3 permissions for now--I do understand the need to not have the account with full permissions.

**Comment by pgrinaway** [comment]
Ok, looks good.

**Comment by jchodera** [comment]
> It might be easier to just prohibit EC2 and not mess much with specific S3 permissions for now--I do understand the need to not have the account with full permissions.

EC2 access is now explicitly denied.  Hopefully this didn't break things!

**Comment by pgrinaway** [comment]
Yeah, that's still fine.

**Comment by pgrinaway** [comment]
Resolved by #191
