### ISSUE TITLE
Add tests for Cython mixing code

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/yank#171]

**Comment by pgrinaway** [comment]
Addressed, for now, by #181. Reopen or create a new issue for further discussion

**Comment by jchodera** [comment]
One more idea here, though it isn't necessary to implement right now:

If we test the mixer on a small number of states---say 3 or 4---then the total number of permutations is sufficiently small (6 or 24) that we could run the mixer many times and see if each permutation is actually sampled with the expected probability, subjecting the number of times each permutation is sampled to the chi-squared test we discussed earlier.
