### ISSUE TITLE
Eliminate duplicated functions

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#18]
We should try to move as much as possible to a "standard" modules.  

For example, 

```
kyleb@kb-intel:~/src/kyleabeauchamp/yank$ cat yank/*.py|grep analyze_accept
def analyze_acceptance_probabilities(ncfile, cutoff = 0.4):
def analyze_acceptance_probabilities(ncfile, cutoff = 0.4):
```

I've seen other duplicated functions as well.  IMHO, one way to deal with this is to create `utils.py` and dump any "utility" functions there--until we find a better place to put them.

**Comment by Lnaden** [comment]
I will try to clean this up with the PEP8 work. Double check if there is anything that is still duplicate.

**Comment by kyleabeauchamp** [comment]
There is a tool called vulture that might help identify unused code.

**Comment by Lnaden** [comment]
Thanks! I'll look into it.

**Comment by Lnaden** [comment]
This appears to have been resolved by the overhaul'd API and the cleanup of the analyze module in #719
