### ISSUE TITLE
Indentation error in test_mixing.py

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#182]
Travis caught a bug!
https://travis-ci.org/choderalab/yank#L1160-L1161
```
Compiling /home/travis/miniconda/envs/_build/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/tests/test_mixing.py ...
Sorry: IndentationError: expected an indented block (test_mixing.py, line 48)
```
I think this is @pgrinaway's.

**Comment by kyleabeauchamp** [comment]
This is an [WIP] PR (#181) and does not need a separate issue.  I think the previous commit also happened to be broken due to the OpenMMTools issue.

**Comment by jchodera** [comment]
Oh, sorry---I must have accessed the wrong travis link...

**Comment by jchodera** [comment]
Huh.  Clicking the travis link from the main github page does indeed go to the travis-ci for the `master` branch, but it appears to check out the PR #181 instead of the master branch.

**Comment by kyleabeauchamp** [comment]
It looks like the link takes you to the most recent build.  Maybe the *icon* refers to master while the link always points to the latest?
