### ISSUE TITLE
Explicit solvent in yank 1.0?

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/yank#186]
I'm wondering what the current thought regarding explicit solvent in yank 1.0 is...if it's going to wait, then I think the SystemBuilders should also wait, due to the GB issue. If it's not, then I'll prioritize the SystemBuilder issues...

**Comment by jchodera** [comment]
Good point about the GB issue that remains with systembuilder. That may be
easy to add, but we still essentially need to add a GB parameter assignment
engine for that.

We do support explicit solvent right now through the Amber input files, but
it hasn't been extensively tested. Also, we don't have the anisotropic
dispersion correction stuff in yet.

System builder would be great to have, buy we'd need to solve the GB
reassignment issue first. Let me take a look at what is needed for that.

Dealing with repex is probably higher priority. If we can get that in, it
would be much much easier than replacing oldrepex later.

**Comment by pgrinaway** [comment]
Ok, that sounds good.

**Comment by jchodera** [comment]
I'm going to close this and create separate issues that address the actual things we have to do here.
