### ISSUE TITLE
Refactor analysis framework

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#205]
We need to make some decisions about how analysis should work in order to eliminate some massive  code duplication in the analysis code.  We have to figure out how analysis code should be apportioned among `yank.analyze` and `yank.repex.ReplicaExchange`.

Should analysis of replica-exchange simulations happen _within_ the `ReplicaExchange` object?  if so, how do we knit together estimates from multiple `ReplicaExchange` objects?  And should `ReplicaExchange` objects have to be initialized to bind to their store files before we can call `repex.analyze()`, or should there be class methods to analyze store files without binding to them?

**Comment by kyleabeauchamp** [comment]
Didn't I already refactor this in repex?  If so, then further changes to
yank master will actually push back our 2.0 release.

**Comment by jchodera** [comment]
Unclear on what you ate advocating here.

**Comment by jchodera** [comment]
Do you mean we just shouldn't touch the duplicated code now, or that we
should swap oldrepex out in favor of repex now?

**Comment by kyleabeauchamp** [comment]
I guess one possibility is that we should avoid major refactorings for 1.0 because we've already got a giant backlog of refactoring (e.g. repex) that we need to finish.  E.g. things that say "refactor" should be considered for punting until 2.0.

**Comment by Lnaden** [comment]
Rebooting this issue: Maybe move it to the Yank 1.1 

- What do we want analyze to output?
- Hard Coded iPython skeleton and reports generated
- Multiple calculations -> summary statistics
- Quick Progress Checks?

**Comment by Lnaden** [comment]
Some touch up is still on the 1.0 list

1.0 touch

**Comment by Lnaden** [comment]
The analysis framework has been reworked in #660. We can open new issues to support additional features as desired
