### ISSUE TITLE
Jenkins is now set up to run examples

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#210]
See here:

https://jenkins.choderalab.org/job/test-yank-linux-xeon-gtxtitan-jak/

It just grabs the latest `yank-dev` conda package and runs through all the examples that have `test.sh` scripts on `jak`.

**Comment by jchodera** [comment]
This is still running!  I think some of the examples might have too many iterations coded in `test.sh`:
https://jenkins.choderalab.org/job/test-yank-linux-xeon-gtxtitan-jak/23/console

**Comment by jchodera** [comment]
Looks like this is because the default number of iterations is 1000:
https://github.com/choderalab/yank/blob/master/Yank/yank.py#L93

Should I dial back the number of default iterations to 10, or should I code a fixed set of iterations (e.g. 10) into all of the examples?

**Comment by kyleabeauchamp** [comment]
I think it's fine to lower the number of iterations by default--people will also want to be able to run through the examples in a finite amount of time.

**Comment by jchodera** [comment]
Should be fixed by #211.

**Comment by jchodera** [comment]
Jenkins also now polls the `yank-dev` binstar summary page for changes to trigger this test:
https://binstar.org/omnia/yank-dev/files

**Comment by jchodera** [comment]
This hasn't been working due to a failure of travis-ci to get through the nosetests and upload working `yank-dev` packages.  I'm trying to speed up the nosetests now.
