### ISSUE TITLE
commands/run.py modifications

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#215]
In commands/run.py, line 58, shouldn't mpicomm = MPI be mpicomm= MPI.COMM_WORLD ?

Furthermore, yank.run(mpicomm, options=options) (line 61) should be changed to yank.run(mpicomm=mpicomm, options=options), otherwise niterations_to_run in yank.py is set to mpicomm.

**Comment by andrrizzi** [comment]
Thanks! This is fixed now.
