### ISSUE TITLE
Docs not being pushed to S3

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#219]
I'm trying to figure out why the docs are not being correctly pushed to the `getyank.org` S3 bucket.

Anybody have any ideas?

**Comment by rmcgibbo** [comment]
From the end of the log on https://travis-ci.org/choderalab/yank/builds/55597090
```
/home/travis/build/choderalab/yank
+python devtools/ci/push-docs-to-s3.py
devtools/ci/index.html -> s3://getyank.org/index.html  [1 of 1]
 81 of 81   100% in    0s  1210.69 B/s  done
Done. Uploaded 81 bytes in 1.0 seconds, 81.00 B/s. Copied 0 files saving 0 bytes transfer.
Done. Your build exited with 0.
```

I would try installing and building the docs on your workstation, setting your AWS credentials as environment variables, and then walking through the  `after_sucess.sh`, and fiddling with it. I suspect you will find a bug in the script.

**Comment by rmcgibbo** [comment]
The problem is that `push_docs_to_s3.py` is trying to find the docs in `docs/_build/html/`, but they're actually in `docs/build/` (not no `html`) subdirectory.

**Comment by jchodera** [comment]
Ah!  Thanks so much!

**Comment by jchodera** [comment]
Addressed in #218.

**Comment by jchodera** [comment]
OK, docs are being pushed, but stylesheet (?) issues.
http://getyank.org/latest/index.html

**Comment by kyleabeauchamp** [comment]
According to my debug console, I get the following error:

```
The stylesheet http://getyank.org/latest/_static/css/theme.css was not loaded because its MIME type, "text/plain", is not "text/css". index.html
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
```

**Comment by jchodera** [comment]
Maybe an S3 config issue?  Checking...

**Comment by kyleabeauchamp** [comment]
The file's content looks pretty reasonable.  Here is the diff to the mdtraj / msmb version, which has only slight customization:


```
diff theme.css yank 
1908d1907
< 
2563c2562,2564
< 
---
> .wy-table-responsive table td,.wy-table-responsive table th {
>     white-space:nowrap
> }
3738,3800d3738
< }
< 
< 
< 
< 
< /*
< 
< ==========================================================================
< RTM Customizations
< ==========================================================================
< */
< 
< #references .wy-table-responsive {
<     /* prevent the references section from having extra padding between 
<     entries */
<     margin-bottom:0px;
<     max-width:100%;
<     overflow:auto
< }
< /*table.docutils {
<     table-layout: fixed;
< }
< 
< table.docutils td {
<     word-wrap: break-word;
< }*/
< .wy-table-responsive table td,.wy-table-responsive table th {
<     white-space:normal;
< }
< .wy-menu-vertical li ul li a {
<     /* entries in the sidebar */
<     text-overflow: ellipsis;
<     white-space: nowrap;
<     width: 110%;
<     overflow: hidden;
< }
< 
< p.rubric {
<     font-weight: bold;
< }
< 
< table.docutils tr.field-odd th.field-name {
<     background: #F0F7FA;
<     white-space: nowrap;
< }
< 
< table.docutils.field-list > tbody > tr > td {
<     padding-left: 5px !important;
< }
< 
< table.docutils td.field-body, table.docutils th {
<     padding: 1px 8px 1px 5px;
<     border-top: 0;
<     border-left: 0;
<     border-right: 0;
< }
< body > div.wy-grid-for-nav > section {
<     background: #EFEFEF;
< }
< 
< div.warning-wrapper {
<     background-color: #ffaaaa;
<     text-align: center;

```

**Comment by rmcgibbo** [comment]
it's not the content. it's the mime type metadata attached to it. see e.g.
the --guess-mime-type option in http://s3tools.org/usage. you might be able
to change it on the s3 web ui too.

**Comment by jchodera** [comment]
Might be this:
http://stackoverflow.com/questions/14807702/amazon-s3-static-website-doesnt-serve-css-or-js-files

**Comment by jchodera** [comment]
Ah, that's it @rmcgibbo

**Comment by jchodera** [comment]
Did I break travis somehow?
https://travis-ci.org/choderalab/yank#L77-L93

**Comment by kyleabeauchamp** [comment]
Could it just be a long queue?

**Comment by jchodera** [comment]
It seems to be some sort of weird git `couldn't find remote ref` issue:
```
$ cd choderalab/yank
3.12s$ git fetch origin +refs/pull/220/merge:
fatal: Couldn't find remote ref refs/pull/220/merge
The command "eval git fetch origin +refs/pull/220/merge:" failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/220/merge
The command "eval git fetch origin +refs/pull/220/merge:" failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/220/merge
The command "eval git fetch origin +refs/pull/220/merge:" failed 3 times.
The command "git fetch origin +refs/pull/220/merge:" failed and exited with 128 during .
Your build has been stopped.
```

**Comment by kyleabeauchamp** [comment]
I clicked on rebuild to see if it happens again

**Comment by jchodera** [comment]
I've tried that a few times already...

**Comment by jchodera** [comment]
Maybe if I make a trivial commit to the main branch?

**Comment by kyleabeauchamp** [comment]
worth a try

**Comment by bas-rustenburg** [comment]
Travis cant build after pull request is merged I think.

**Comment by bas-rustenburg** [comment]
By which I mean, did you merge, but travis started the build of the PR (not the master) after that? Because that will fail to download to travis and give results like that.

**Comment by jchodera** [comment]
That sounds like exactly what happened.  This will keep me from being an
impatient idiot in the future.

**Comment by bas-rustenburg** [comment]
It should still build after merging, but it will be under the branches travis tab, not the pull requests.

**Comment by jchodera** [comment]
Right you are!

**Comment by jchodera** [comment]
Just wiped out contents of S3 bucket and restarted travis build of master branch

**Comment by jchodera** [comment]
It uploaded, but still no luck fixing the odd formatting.

**Comment by kyleabeauchamp** [comment]
Here's one idea:

1.  recursive wget of the getyank page
2.   load the files locally in browser
3.  Build docs manually and view in browser
4.  compare

**Comment by kyleabeauchamp** [comment]
So my local copy of `wget -r getyank.org` looks good.

**Comment by kyleabeauchamp** [comment]
My browser debug shell still finds this issue on getyank.org:

```
The stylesheet http://getyank.org/latest/_static/css/theme.css was not loaded because its MIME type, "text/plain", is not "text/css".
```

**Comment by kyleabeauchamp** [comment]
I imagine this means that fixing the MIME type on this one file will be sufficient for working docs.

**Comment by jchodera** [comment]
OK, I figured out how to change them manually in the S3 bucket browser.  Works now.

Very weird.
