### ISSUE TITLE
Add mpi tests

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#232]

**Comment by jchodera** [comment]
Just bumping this; we really do need to add MPI tests to catch issues.

**Comment by Lnaden** [comment]
Looks like MPI can be tested with travis.

Example someone made: https://d-meiser.github.io/2016/01/10/mpi-travis.html

Do we want this for 1.0 or post?

**Comment by andrrizzi** [comment]
Cool! I think the `repex` repo also have some examples.

**Comment by jchodera** [comment]
Good point! Here's an [example](https://github.com/choderalab/repex/blob/master/repex/tests-nose/test_replica_exchange_mpi.py), and some [utilities](https://github.com/choderalab/repex/blob/master/repex/mpinoseutils.py) that let `mpi4py` work with `nose`.

**Comment by jchodera** [comment]
In light of https://github.com/choderalab/yank/pull/555, we should ensure the MPI tests also test a combinatorial experiment.

**Comment by andrrizzi** [comment]
We now have an `mpi` module with its own tests, and both `test_repex` and `test_yank` should be able to work in an MPI environment too.
