### ISSUE TITLE
Solvation free energy example?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#233]
Is it currently possible to do solvation free energies with Yank? Perhaps an example could be provided? (I see several other helpful examples).

**Comment by davidlmobley** [comment]
We provided a set of input files to @jchodera via e-mail and are happy to do anything else we can to help with this.

**Comment by davidlmobley** [comment]
I just provided another set of input files by e-mail, this time with vacuum files as well.

**Comment by Lnaden** [comment]
This has been handled by the `yank-examples` repo
