### ISSUE TITLE
first iteration energies 0

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#234]
Is it true that in the current version the energies of the first iteration (iteration 0) are all 0? This was not the case in the previous version of yank. This gave trouble in my FEP calculation. I suppose it is not a problem for the MBAR calculation, since (with default settings) equilibration frames are discarded.

**Comment by luirink** [comment]
although.. how many iterations will be discarded is also based on iteration 0...

**Comment by jchodera** [comment]
Yes, that's correct!  The current version of YANK splits the calculation into a `yank prepare` phase (which creates the NetCDF store files) and `yank run`.  To do this without having `yank prepare` compute all the energies, the initial energies are set to zero.  I intend to have the first iteration overwrite these energies in a future update, which restore the old functionality.

You're right that the equilibration frames will be discarded when using automated equilibration detection from `pymbar.timeseries`.

**Comment by jchodera** [comment]
PR #276 discards the initial frame from analysis in a temporary fix, but we want to eventually fix this behavior by starting with non-zero energies.

**Comment by Lnaden** [comment]
We'll want to fix this as part of the larger API overhaul when we refactor repex. Might be post 1.0

1.0 touch

**Comment by Lnaden** [comment]
Fixed by #656
