### ISSUE TITLE
Yank analyze.py module. Filename error

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#237]
Hi There,

running the analyse module of Yank in the example folders after the completion of the simulations:

yank anayze -s output

an error is raised. In the created output directory two files are present  ‘complex-explicit.nc’ and ‘solvent-explicit.nc’. Actually, the program is looking in some points for ‘complex.nc’ and ‘solvent.nc’ therefore I ended up with the temporary solution to copy the files with the new filenames and therefore in the output directory I had four files (‘complex-explicit.nc’, ‘complex.nc’, ‘solvent-explicit.nc’, ‘solvent.nc’).  This problem seems to be present also in the anaconda installation of Yank.  
 
Cheers,

Gaetano

**Comment by jchodera** [comment]
I think #241 addresses this.
