### ISSUE TITLE
Use MDTraj for trajectory alignment / quaternions

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#24]
So Robert and I have done some work integrating RMSD and alignment features into MDTraj.geometry

We could possibly pull in some of the rotation stuff that's currently in Yank.  One advantage is that it could be easier to maintain there...

**Comment by Lnaden** [comment]
Leave this till post-1.0

**Comment by andrrizzi** [comment]
I'll migrate this issue in `openmmtools` as this code is now implemented in the rotation MCMC move.
