### ISSUE TITLE
Default constraints: None or HBonds?

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#244]
The help message says that the default for the argument --constraints is HBonds, but the function setup_binding_amber() in prepare.py actually sets the system's constraints to None when the argument is not specified in the command line.

I'm not sure whether there is a mistake in the documentation or in the code (or if I am just missing something).

**Comment by jchodera** [comment]
Good catch!  Fixing.

**Comment by jchodera** [comment]
Ah, it wasn't a bug after all.  `docopt` processes this line in the docstring to set the default to `HBonds`:
```
 --constraints=CONSTRAINTS     OpenMM constraints (None, HBonds, AllBonds, HAngles) [default: HBonds]                                                                                         
 ```
