### ISSUE TITLE
Implement ligand orientational restraints as per Boresch 2003

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#246]
In #245 , I raised the issue of restraints. Ideally we would also be able to use the restraints my group normally uses, orientational restraints as proposed by Boresch et al. (2003). These are restraints on one distance, two angles, and three torsions defining the six ligand-protein rigid-body degrees of freedom, as per:

Boresch, S., Tettinger, F., Leitgeb, M., & Karplus, M. (2003). Absolute Binding Free Energies: A Quantitative Approach for Their Calculation. The Journal of Physical Chemistry B, 107, 9535–9551.

I'm open to being convinced that other forms of restraints such as flat-bottom or simple harmonic distance restraints are preferable, though the only *study* of this I'm aware of is the one I did back in ~2006 which looked at simple harmonic distance restraints (without lambda exchange) and found them much less efficient. So unless there is work I'm not aware of, we probably need to look at the relative efficiency of the different forms of restraints - hence a need to implement these. 

Any thoughts? Have any of you looked at these restraints and are you open to having them implemented here?

**Comment by Lnaden** [comment]
Added in #500
