### ISSUE TITLE
Split off systembuilder into separate tool?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#247]
May be useful to split the `systembuilder` functionality off into a separate tool.

**Comment by kyleabeauchamp** [comment]
IMHO some of this stuff could potentially be moved into parmed or openmoltools, rather than creating another toolkit.

**Comment by kyleabeauchamp** [comment]
The key point is that we *need* the co-maintain these large infrastructure projects with other labs.  I think the Parmed Team is probably the right people to work with on such things.

**Comment by jchodera** [comment]
We had a discussion with @mrshirts and @davidlmobley about precisely this: Co-maintaining large infrastructure projects with other labs.

It's not yet clear whether an OpenMM ffxml-based route or parmed-based route will be the optimal way to do this.  A new thread will be opened to discuss.

**Comment by davidlmobley** [comment]
Yes, I'll start that now.

**Comment by Lnaden** [comment]
Depreciating in lieu of new SystemBuilder variation post 1.0
