### ISSUE TITLE
ModifiedHamiltonianExchange

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#26]
So should ModifiedHamiltonianExchange be replaced by a "regular" HamiltonianExchange object with a particular choice of MCMC moveset?  I'm trying to wrap my head around where each component belongs.

**Comment by Lnaden** [comment]
Re-touch this issue post API refactor, It will probably be resolved by that. But touched for pre 1.0

**Comment by andrrizzi** [comment]
This was addressed by the recent refactor. `ReplicaExchange` was generalized to handle efficiently HREX in #656 and make use of rotation/displacement MCMC moves, and `ModifiedHamltonianExchanged` was deleted in #663.
