### ISSUE TITLE
Add sanity checks to alchemical factory

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#263]
Given the trouble we're having with large systems causing alchemically-modified systems to give `NaN` energies, it will be useful to add a number of sanity checks that help debug which force component is causing the `NaN`. 

This is just a reminder to myself to implement this.

**Comment by jchodera** [comment]
We can add an optional argument to `AlchemicalFactor.__init__()` to compute the total potential energy for a given set of `positions` and if `NaN` is detected, compute the energy (on the `Reference` platform) by force component to pin down the culprit.

**Comment by Lnaden** [comment]
Is this something that should be moved to `alchemy`?

**Comment by andrrizzi** [comment]
+1

**Comment by Lnaden** [comment]
Moved to `alchemy`
