### ISSUE TITLE
Add possibility for MBAR calculation every x iterations to check convergence

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#266]
I think this would be very useful to add. I have added it now myself, but in my opinion it could be valuable addition.

**Comment by jchodera** [comment]
This would be useful because the current online analysis mode slows down the simulation considerably.

**Comment by jchodera** [comment]
Maybe we can keep updating a file with the current best estimate.

We can also record and plot the historical convergence.

**Comment by Lnaden** [comment]
General online analysis update post 1.0

**Comment by Lnaden** [comment]
Fixed by the online analysis #712
