### ISSUE TITLE
Update docs to make mpirun across multiple GPUs clearer

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#272]
It would help to update the docs to clarify our strategy for using multiple GPUs (especially when distributed across different nodes) in light of #269.

**Comment by Lnaden** [comment]
This is a doc update that should be fixed pre 1.0

**Comment by Lnaden** [comment]
It looks like this might have been taken care of here http://getyank.org/latest/running.html

Is this what you thought of for this documentation or do you think its not clear enough?

**Comment by jchodera** [comment]
> Is this what you thought of for this documentation or do you think its not clear enough?

We'll need to make some updates to the MPI part:
* You can use `build-mpirun-configfile` instead of `python build-mpirun-configfile.py`
* This only works for Torque or PBS right now because it [reads `$PBS_GPUFILE`](https://github.com/choderalab/clusterutils/blob/master/clusterutils/build_mpirun_configfile.py#L44)
* For slurm, you want to run `mpirun` directly

Eventually, we can improve this script and incorporate it into `yank` more transparently, maybe via `yank mpilaunch` or something.
