### ISSUE TITLE
Faster minimization

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#302]
It would be useful to explore schemes to speed up initial energy minimization.

**Comment by jchodera** [comment]
The [FIRE minimizer](https://github.com/jchodera/openmmtools/blob/fire/openmmtools/integrators.py#L187-L334) might work for this.

**Comment by Lnaden** [comment]
Post 1.0 issue, maybe 1.1 or 1.2

1.0 touch

**Comment by Lnaden** [comment]
This was added by 0.21.0
