### ISSUE TITLE
Decide how to designate molecule to be decoupled for "ambiguous" cases, if not already resolved

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#303]
In the context of solvation free energies ( #233 ) which are being implemented, sometimes one will need to designate which solute to be decoupled - i.e. if I have 10 molecules of toluene in 100 of cyclohexane and I want to decouple one of the toluene molecules. The same issue arises sometimes in protein-ligand binding (i.e. if I'm looking at a trimer with ligands in three sites and want to decouple just one). 

Is there already a mechanism for designating one particular molecule for decoupling? If not, we need to settle on a convention for doing so. In GROMACS we have been dealing with this by singling out a specific residue name (and giving the molecule we want to decouple, only, that residue name).

**Comment by jchodera** [comment]
As of #259, we currently support the [MDTraj DSL selection language](http://mdtraj.org/latest/atom_selection.html) which offers the flexibility to do this.  I'd love to implement a more flexible [PyMOL-like selection language](http://pymol.sourceforge.net/newman/user/S0220commands.html) in the future, though.

**Comment by jchodera** [comment]
We think the DSL works for this, so closing for now.
