### ISSUE TITLE
Unify analysis framework

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#304]
Things are a bit scattered now, between:
- [`yank.analyze`](https://github.com/choderalab/yank/blob/master/Yank/analyze.py)
- [`Yank.analyze()`](https://github.com/choderalab/yank/blob/master/Yank/yank.py#L438)
- [`repex.analyze()`](https://github.com/choderalab/yank/blob/master/Yank/repex.py#L2293)

**Comment by Lnaden** [comment]
Part of the larger `analyze.py` discussion.

1.0 touch

**Comment by Lnaden** [comment]
I think this has been fixed with the main API overhaul, and also with #660, #692, #714, and #717
