### ISSUE TITLE
Store serialized OpenMM Topology objects in NetCDF store files

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#309]
It would be helpful for generating visualizations and trajectories to store the OpenMM `Topology` objects corresponding to each phase as serialized objects in the NetCDF store files.

**Comment by andrrizzi** [comment]
So, the only way I see it possible to implement this, is to change the signature of `Yank.create()` and `ReplicaExchange.create()` to add also a `topology` argument. Is that correct? Is there a way/is it safe to extract topologies from the `BondForce`s?

**Comment by andrrizzi** [comment]
Actually, I guess that for `ReplicaExchange` we can pass the topology as an attribute of the `ThermodynamicState`s.

**Comment by jchodera** [comment]
I think of the Topology object as being invariant with choice of
thermodynamic state.

I think it would be useful to add it as an optional (or maybe required?)
argument to the ReplicaExchange class and subclasses.

**Comment by andrrizzi** [comment]
I see. Currently repex does not need the topology at all, and I think we need to be a little careful to change things if we plan to attach the new repex repo in the future to minimize time spent reimplementing. What if we passed it to `ReplicaExchange` as `metadata` instead?

**Comment by jchodera** [comment]
That sounds like it will work for now!

**Comment by andrrizzi** [comment]
As far as I can tell, `Topology` objects cannot be serialized like `System`s. I'm thinking about serializing the `mdtraj` topology converted to `pandas` dataframe because it sounds more stable that just pickling the `Topology` object. Better solutions?
