### ISSUE TITLE
Add option to control replica exchange frequency

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#317]
It would be useful to add an option such as `mixing_frequency` that controls the number of iterations between mixing phases in replica-exchange simulations.  This would allow us to collect several iterations worth of trajectory data between exchange attempts.

**Comment by Lnaden** [comment]
Post 1.0 issue and part of api refactor.

**Comment by andrrizzi** [comment]
Ah! Sorry, I've just found this old thread, and I created a duplicate (#843). I'll close this one in favor of the new one.
