### ISSUE TITLE
Restraint type and randomize ligand don't work

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#324]
I searched through the whole project but I can't find any place in which the options ``'restraint_type'`` and ``'randomize_ligand'`` (which are set in ``prepare.py``) are used. As a consequence, they always assume the default values set in ``Yank.__init__()`` (``self.randomize_ligand = False`` and ``self.restraint_type = 'flat-bottom'``).

Is this a bug or am I missing something?

**Comment by andrrizzi** [comment]
This should be fixed now, closing.

**Comment by jchodera** [comment]
Thanks!
