### ISSUE TITLE
Some Yank options not being parsed correctly

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#326]
It looks like numerical options like `self.nsteps_per_iteration` are not being converted to numbers correctly.  I think this might be an issue with the NetCDF storage.

For example, `self.nsteps_per_iteration` ends up being of type `<type 'numpy.ndarray'>` instead of `int`.

Working on a fix.

**Comment by andrrizzi** [comment]
Can you tell me more or less how to reproduce it? Maybe it's caused by something I've recently implemented and I can help.

**Comment by jchodera** [comment]
Whoops! I meant to say this was fixed by #327. Sorry!
