### ISSUE TITLE
YANK termination for NaNs

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/yank#328]
It might be a good idea to have YANK terminate more gracefully and not print out pages of NaNs in the out put!

**Comment by jchodera** [comment]
Yank should actually back up an iteration when we get NaNs.

**Comment by Lnaden** [comment]
There may be more more critical issues here that will require time to pin down and may not be fixable by 1.0 with the other issues we want to get through. 

Thoughts?

1.0 touch
