### ISSUE TITLE
Rename yank.commands module?

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#330]
Continuing the discussion in #329 .

I found a weird import chain when trying to run doctest on Yank/yamlbuild.py

[``yank.yamlbuilder: import openmoltools``](https://github.com/andrrizzi/yank/blob/yaml-builder-basics/Yank/yamlbuild.py#L24) -> [``openmoltools:__init__: from openmoltools import utils``](https://github.com/choderalab/openmoltools/blob/master/openmoltools/__init__.py#L28) -> [``openmoltools.utils: from commands import getoutput``](https://github.com/choderalab/openmoltools/blob/master/openmoltools/utils.py#L18)

The last line search in ``yank.commands`` instead of the [standard library commands](https://docs.python.org/2/library/commands.html) and the test stops. Should we **rename the ``yank.commands`` module into something that doesn't clash with standard libs**?

It should be noted that the standard ``commands`` module **has been deprecated** since python 2.6 and it has been removed in python 3. So, as **an alternative solution we could stop using ``commands`` in openmoltools** instead. The ``subprocess`` module has been there since python 2.4 .

**Comment by jchodera** [comment]
> It should be noted that the standard commands module has been deprecated since python 2.6 and it has been removed in python 3. So, as an alternative solution we could stop using commands in openmoltools instead. The subprocess module has been there since python 2.4 .

We should definitely make that change.  Let's try that first, and also rename `yank.commands` if that doesn't work?

**Comment by andrrizzi** [comment]
Yeah, that's definitely the cleanest way. We'll have to define a custom work-around function though because there is no ``getoutput()`` function yet in the python2 ``subprocess`` module.

Also, what is the minimum python2 version supported by openmoltools? If it is 2.7 we can easily fix it by using ``subprocess.check_output()`` (which still have a slightly different signature) but that's not available in 2.6 so we would have to use something like
```python
def work_aroung_getoutput(cmd)
    process = subprocess.Popen(['ls', '-a'], stdout=subprocess.PIPE)
    out, err = process.communicate()
    return out
```
and then
```python
try:
    from subprocess import getoutput  # If python 3
except ImportError:
    from utils import work_around_getoutput  # If python 2
    getoutput = work_around_getoutput
```

**Comment by jchodera** [comment]
All `omnia` packages should support 2.7, 3.4, and 3.5.

**Comment by jchodera** [comment]
We don't need to worry about python 2.6.

**Comment by andrrizzi** [comment]
Awesome. I'll fix it as soon have I time.

**Comment by rmcgibbo** [comment]
(FWIW I stopped caring about Python 2.6 after I read this blog post from one of the CPython core developers: http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html)

**Comment by andrrizzi** [comment]
Thanks, that was I nice reading.

**Comment by andrrizzi** [comment]
This has been pushed to ``openmoltools``. Closing.

**Comment by jchodera** [comment]
Thanks!
