### ISSUE TITLE
Activate travis for `osx`?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#332]
We should be able to activate travis for `osx` now too.

**Comment by Lnaden** [comment]
We might be able to get this in for 1.0. We will need to have a way to get GNU compilers (or something) enabled on the osx for AmberMini. 

We'll look at this if there is time before the 1.0 release, otherwise it may have to wait.

1.0 touch

**Comment by jchodera** [comment]
> We might be able to get this in for 1.0. We will need to have a way to get GNU compilers (or something) enabled on the osx for AmberMini.

I'm not sure what you mean. We are already [building `ambermini` 16.16.0](https://anaconda.org/omnia/ambermini/files) on `osx`.

I'll create a PR to activate travis for `osx`.

**Comment by jaimergp** [comment]
Closed by #1244
