### ISSUE TITLE
Working directory when executing YAML script

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#334]
Should the file paths in the YAML script be relative to the user working directory, or to the script directory?

Even if it's a little trickier to program, I like the second solution more because it doesn't change the result of the script if you execute it from a different folder, but maybe there are things I didn't consider.

**Comment by jchodera** [comment]
I like the idea of being relative to the script directory!

**Comment by bas-rustenburg** [comment]
:+1: for script dir. Much easier for keeping track of what files are being used. 

It would require copying the file if you're running the same protocol in multiple directories. I suppose that setup could also be defined in the yaml file itself though.

**Comment by andrrizzi** [comment]
Great! I'll implement the script directory then.

I think we should be able to avoid copying files by writing a function that convert a path to be relative to a different working directory. I'll give it a go.

**Comment by andrrizzi** [comment]
Oh, look: https://docs.python.org/2/library/os.path.html#os.path.relpath

I love Python.

**Comment by andrrizzi** [comment]
> It would require copying the file if you're running the same protocol in multiple directories. I suppose that setup could also be defined in the yaml file itself though.

Sorry, I just got this, you're right. Alternatively, we can always specify absolute paths if we want to run from multiple directories.

**Comment by bas-rustenburg** [comment]
I suppose it would be pretty easy to detect whether a path is absolute or relative (leading `/` character, and/or whatever windows uses).

**Comment by bas-rustenburg** [comment]
Looks like [`os.path.isabs`](https://docs.python.org/2/library/os.path.html#os.path.isabs) does that job.

**Comment by andrrizzi** [comment]
Thanks for the suggestion! I ended up using exactly that function in the PR.
