### ISSUE TITLE
Add neutralizing counterion(s) to alchemical atom indices for explicit solvent

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#345]
As discussed this morning, for charged ligands in explicit solvent, we should make sure to add a set of minimally neutralizing counterions to the alchemical atom index set fed to `AbsoluteAlchemicalFactory` so that the whole alchemical system is net neutral.

**Comment by jchodera** [comment]
We could either expose an option to do that or just do it automagically.

**Comment by andrrizzi** [comment]
I think doing it automagically should be easy. I can work on this.

**Comment by andrrizzi** [comment]
This should be implemented now. Closing.
