### ISSUE TITLE
Generalizing restraints code

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#348]
@luirink and @davidlmobley both want to contribute code to add new restraint types.  @luirink would like to use `CustomCompoundBondForce` to allow restraints centered in a binding site defined by multiple residues, while @davidlmobley would like to add Boresch-style restraints involving torsions, angles, and bond lengths.

It would be great to get both in the main YANK code, but to make it easier for people to add new restraints, it would be great to modify the `restraints.py` code a bit to make things general.

We already have a `ReceptorLigandRestraint` base class from which other restraint classes are derived, but there are some things that prevent easy generalization:
- These classes are imported by name in [yank.py](https://github.com/choderalab/yank/blob/master/Yank/yank.py#L34)
- The text `restraint_type` selection selects the restraint type in (an explicit `if/elif` structure](https://github.com/choderalab/yank/blob/master/Yank/yank.py#L324-L330)

Instead, what if we simply [found all subclasses of the `ReceptorLigandRestraint` class using Python introspection](http://stackoverflow.com/questions/3862310/how-can-i-find-all-subclasses-of-a-given-class-in-python)?  Each subclass could be forced to define a `getName()` method or `.name` property (or something similar), and we could simply use this to select which class we want.  That way, all someone needs to do is to create a new subclass and give it a unique name and they've succeeded in adding a new restraint type without changing any other code.

Also CCing #305, where we were thinking about standard state issues.

**Comment by andrrizzi** [comment]
> what if we simply found all subclasses of the ReceptorLigandRestraint class using Python introspection?

I guess an alternative could be something like (with appropriate exception handling)
```python
import restraints
...
# the restraint_type option becomes the name of the class instead of 'flat-bottom', 'harmonic', etc.
# or maybe just the first part of the name (i.e. 'Harmonic' for 'HarmonicReceptorLigandRestraint')
LigandRestraintsCls = getattr(restraints, self._restraint_type + 'ReceptorLigandRestraint')
restraints = LigandRestraintsCls(thermodynamic_state, reference_system, ...)
```
we could even use introspection with ``inspect.getargspec(LigandRestraintsCls.__init__)`` to figure out if initialization requires different arguments.

**Comment by davidlmobley** [comment]
@nividic should see this too. Gaetano, this would be relevant to you.

**Comment by jchodera** [comment]
I'm not 100% sure, but I think the advantage of using the trick of finding all subclasses (instead of `getattr`) is that these subclasses just have to be imported into the interpreter but could be defined anywhere (e.g. in user-provided files imported before `Yank` is run) if someone is calling `Yank` via the Python API.

**Comment by andrrizzi** [comment]
> these subclasses just have to be imported into the interpreter but could be defined anywhere

I see, that would be great! If that doesn't work we can still use ``getattr()`` and let the user specify the module (which would default to ``yank.restraints``) together with the class name in the restraints option.

**Comment by jchodera** [comment]
@luirink and I were discussing how to incorporate her binding site restraints that use the center of the binding site, and we thought it might be useful to incorporate the general feature of letting the user specify for the receptor two items:
* atoms to restrain
* flat-bottom distance `r0`

I think it would be simplest if we add this support directly into the `ReceptorLigandRestraint` class (which maybe should be called `IsotropicRestraint` or `RadialRestraint` since it just restrains a single distance).  We would want to add two YAML parameters that could be attached to each entity (receptor or ligand) called something like:
* `restraint_atom_selection` - use [MDTraj DSL](http://mdtraj.org/latest/atom_selection.html) to select atoms
* `restraint_distance_scale` - if specified for harmonic restraint, this would be used as `sigma` to determine the spring constant `K`; if specified for flat-bottom restraint, this is used as the `r0` for the flat-bottom portion

Does this sound reasonable, @andrrizzi?  If so, I can quickly add this in.

**Comment by andrrizzi** [comment]
Sounds great!

I'm not entirely sure about this, but the only problem I can see is that the atom selection may not be straightforward, as tleap may modify the order of atoms or chain ids when putting everything together and creating the prmtop file.

**Comment by jchodera** [comment]
I'm starting to implement this now. Will post some questions about design decisions soon.

**Comment by Lnaden** [comment]
Still being worked on. Probably won't be resolved till after 1.0  but the framework is in place at least.

1.0 touch

**Comment by Lnaden** [comment]
#588 may address this, but there also might be some outstanding issues.

**Comment by Lnaden** [comment]
With #738, I think this issue can be closed. We can re-open or create a new one if we missed anything.
