### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#35]
I'd like to change the license of yank to be LGPL as well.  Any objections?

**Comment by pgrinaway** [comment]
Sounds good!

**Comment by pgrinaway** [comment]
This is a duplicate issue, though-- see #12. Closing.

**Comment by jchodera** [comment]
Let's change the license to the same LGPL as OpenMM

**Comment by kyleabeauchamp** [comment]
Done by #169
