### ISSUE TITLE
Build dev packages for osx for yank-dev and dependencies

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#363]
Currently we cannot `conda install yank-dev` on osx because the `-dev` packages of `alchemy`, `openmoltools` and `yank` are only for `linux-64`.

**Comment by jchodera** [comment]
I've been trying to figure out what to do about this.  We can
* upgrade the dev frameworks for everything to build on both `linux` and `osx`
* move the dev packages to http://github.com/omnia-md/conda-dev-recipes, though this only builds nightly and can only support a few packages before timing out travis

I think we just have to bite the bullet and add `osx` build/test branches to everything.  Let's try to do so in a uniform manner.

What project is the best one to model the `osx` branches off of?  Are there any `omnia` projects that do a good job of this now?  The [`openmm` travis config](https://github.com/pandegroup/openmm/blob/master/.travis.yml) does this but is very complex. Is there a simpler project we can model this from, or should we just refine a stripped-down version of the `openmm` config?

Whatever we do, we should make sure to update the guidelines and recommended skeleton `.travis.yml` in https://github.com/omnia-md/devtools

**Comment by jchodera** [comment]
This is a bigger `omnia` issue we are still sorting out.

**Comment by jchodera** [comment]
We're doing frequent releases now, so we don't need this at the moment.
