### ISSUE TITLE
Time to cut 0.8.0 release

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#369]
Issue #364 was fixed some time ago, but we haven't cut a new release since then. Since `alchemy` has now been updated to 1.2.0 and there have been a number of other improvements, it's time to cut an 0.8.0 release.

The release will use OpenMM 7.0 (technically on `conda` as `7.0rc1`), but since `openmm-dev` has some API-breaking changes added, I am going to first temporarily revert the `devtools/conda-recipe/meta.yaml` requirements to release requirements so we can test the 0.8.0 release in travis.

**Comment by andrrizzi** [comment]
+1

Let me know if I can help.

**Comment by jchodera** [comment]
I've just merged the `alchemy` 1.2.0 release conda recipe. Once that is built, I'll check in the updated `devtools/conda-recipe/meta.yaml` and we can fix any issues with the pinned version numbers in the recipe.

**Comment by jchodera** [comment]
This is done!
