### ISSUE TITLE
Peptide ligand does not have "net_charge"

### ISSUE THREAD

**Issue by juliebehr** [choderalab/yank#372]
Re: convo with @andrrizzi yesterday; I expect this would happen with any setup with a peptide, but I can provide my input files if they are specifically needed to recreate the error!  

Error message:
```
Traceback (most recent call last):
  File "/home/behrj/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1270, in build_experiment
    self._run_experiment(combination, output_dir)
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1858, in _run_experiment
    system_pars, ligand_descr['net_charge'])
KeyError: 'net_charge'
```

**Comment by jchodera** [comment]
Can you at least list the input YAML file?  It sounds like this might be going through the small molecule setup pipeline rather than the protein setup pipeline.

**Comment by andrrizzi** [comment]
Thanks! This is easily fixable. I'll just have to find a way to easily compute the net charge of the peptide.

**Comment by jchodera** [comment]
I've you're preparing the system in `leap`, you can just write `charge peptide` and it will spit out the net charge to the leap output file.

**Comment by jchodera** [comment]
From [here](http://ambermd.org/tutorials/advanced/tutorial8/loop4.htm):
```
> charge mol
Total unperturbed charge: 2.00
Total perturbed charge: 2.00
```

**Comment by andrrizzi** [comment]
Thanks! I guess I'll parse the leap output file if I won't be able to find a more programmatic way. The only reason we need the net charge is to determine how many counterions we have to alchemically modify during the simulations.

Maybe I can find a way to get the net charge right after loading the `prmtop` into an OpenMM System by summing all the `NonBondedForce` parameters? Or maybe I can use parmed. Meanwhile we've found a temporary fix that works for uncharged peptides.

**Comment by jchodera** [comment]
> Maybe I can find a way to get the net charge right after loading the prmtop into an OpenMM System by summing all the NonBondedForce parameters? 

That would definitely work!

**Comment by andrrizzi** [comment]
That the automatic pipeline still doesn't support peptide ligands. But it should now possible to skip the pipeline and start from a `prmtop` file without incurring in this error.

Support for peptide ligands in the automatic pipeline will be added later.
