### ISSUE TITLE
Examples should autodetect batch queue system

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#377]
It turns out that `slurm` automatically sets `CUDA_VISIBLE_DEVICES` appropriately if `srun` is used to launch individual processes, so we don't need to use `build_mpirun_configfile` in this case---the hydra `mpirun` does the right thing automatically (or can be forced to with `mpirun -rmk slurm -launcher slurm ...`).

We should have the examples autodetect whether the mpirun configfile needs to be built manually.

**Comment by Lnaden** [comment]
Moving this to the [yank-examples](https://github.com/choderalab/yank-examples) repo.
