### ISSUE TITLE
Add feature to allow extraction of replica or state trajectories for visualization

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#379]
@luirink has written a script to extract trajectories from NetCDF store files into XTC format (either by replica or state) to make them easier to visualize in PyMOL or VMD.  I'd like to add this as a CLI feature via `yank write-trajectory` or some related name.

Any suggestions?

**Comment by andrrizzi** [comment]
An alternative would be to make it an argument of an existing, more flexible command. Maybe something like `yank analyze --writetrajectory`.

**Comment by andrrizzi** [comment]
#309 should be implemented first so that we won't have to rely on a `pdb` file to extract the topology.
