### ISSUE TITLE
Add support for atom-by-atom alchemical intermediate definition

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#38]
We can easily add an alternative alchemical intermediate generator based on this scheme:
http://dx.doi.org/10.1002/jcc.21829

**Comment by Lnaden** [comment]
Leave for post 1.0

**Comment by jchodera** [comment]
Relocate this to http://github.com/choderalab/alchemy?

**Comment by Lnaden** [comment]
Good call.

**Comment by Lnaden** [comment]
Moved to alchemy
