### ISSUE TITLE
Supported GPUs?

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#399]
Im sorry if this is the wrong place to post this (it most likely is), but is there a list of GPUs that are supported for YANK? I'm looking at getting some new GPUs and it seems that a lot of testing has been done on some cards (e.g. Titan X), but their FP64:FP32 ratios are quite bad (1:24), as opposed to Tesla cards (usually  1:3). Has there been any testing done on how the FP64 performance affects free energy calculations?

**Comment by jchodera** [comment]
YANK runs on [OpenMM](http://openmm.org), so the OpenMM benchmarks are your best guide here:

http://openmm.org/about.html#benchmarks

You can always ask on the [OpenMM forums](https://simtk.org/plugins/phpBB/indexPhpbb.php?f=161) if you have questions about specific cards.

YANK runs in "mixed" precision by default, where it primarily benefits from fast single-precision (FP32) performance.

**Comment by andrrizzi** [comment]
Closing this to keep issue tracker clean. Feel free to reopen if you have more questions!
