### ISSUE TITLE
Create YANK docker image

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#400]
This is just a reminder to create a YANK docker image on [docker hub](https://hub.docker.com/) for testing on [GPU-enabled AWS instances](http://tleyden.github.io/blog/2014/10/25/running-caffe-on-aws-gpu-instance-via-docker/).

More [docker basics on EC2](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html).

**Comment by drthock** [comment]
Has YANK been tested on EC2 yet? I'm in the process of running the abl-imatinib-explicit example on a g2.2xlarge instance, and it looks like the 1 calculation will take ~4.5 days to complete. Have you seen anything on that time scale? On my personal 1080 gtx, the same calculation took ~10h.

**Comment by Lnaden** [comment]
Post 1.0 issue probably once we get a fully stable cut.

**Comment by jchodera** [comment]
Actually, already done and merged:

https://github.com/choderalab/yank/pull/499
