### ISSUE TITLE
Find ways to reduce file sizes

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#41]
Michael Shirts mentioned that his datasets for T4 lysozyme using old YANK were 44GB total for about 20 ligands.  For his work on larger sets of proteins, he is generating ~4TB of data.

We should explore ideas for cutting down file sizes.  Some obvious ones:
- Enabling NetCDF compression by default
- Saving checkpoint data less frequently, but energy data more frequently

**Comment by Lnaden** [comment]
Handle in post yank 1.0

**Comment by Lnaden** [comment]
Do we think this can be closed now as #675 has added the checkpointing feature, or should we do more to reduce file sizes?

**Comment by andrrizzi** [comment]
Maybe we should keep this around and rename it to something like "Quantize floats to reduce file size"? The updated link to the mdtraj issue is mdtraj/mdtraj#287 (the one above gives a not found error).

**Comment by jchodera** [comment]
I believe #704 has greatly helped with reducing file sizes for the analysis file. We can reopen/revisit as needed.
