### ISSUE TITLE
Yank.create() API changes

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#418]
After implementing both #410 (need to pass the "sign" of the phase) and #309 (need to pass the topology object associated to the phase) the signature of `Yank.create()` will become something like
```python
def create(self, phases, cycle_directions, systems, topologies, positions, atom_indices, thermodynamic_state, protocols):
   ...
```
That's 7 dictionaries `phase -> value` that we need to build. Since we have to break the API anyway, what do you think about creating a `Phase` class instead? Something like
```python
# Definition of Phase type
Phase = namedtuple('Phase', ['name', 'direction', 'system', 'topology', 'positions', 'atom_indices', 'thermodynamic_state', 'protocol'])

# New Yank.create() signature
def create(self, *phases):
   # access phases info (e.g. phases[0].name, phases[0].system, phases[1].topology

# Example of phase creation
complex_phase = Phase('complex', '+', complex_system, complex_topology, ...)
solvent_phase = Phase('solvent', '-', solvent_system, solvent_topology, ...)
yank.create(complex_phase, solvent_phase)
```

**Comment by jchodera** [comment]
This sounds great, and is probably something we should have done long ago anyway.

I think the `namedtuple` is extensible, in that we can add more components to it later, but a class might be a better option since it allows us to set default arguments on additional arguments added later in a manner that `namedtuple` doesn't.

**Comment by jchodera** [comment]
And maybe we want to call it `AlchemicalPhase` or something to make it clear that it is a "leg" of the calculation. (I never liked the term "leg", though I'm not sure if "phase" is much better.)

**Comment by andrrizzi** [comment]
Sounds great. Thanks for feedback!
