### ISSUE TITLE
How should we feed input to YANK?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#42]
We have to make some decisions about how we tell YANK what we want it to do.

To be specific, we need to tell it:
* What input to use for the **ligand**, which might be a mol2 file, SDF file, IUPAC or common name, AMBER prmtop/inpcrd pair, etc.  
* What input to use for the **receptor**, which might eventually be a PDB file, a PDB ID, an AMBER prmtop/inpcrd pair, or even another small molecule (as in the host-guest case).  
* If anything isn't parameterized, we need to tell YANK how to assign parameters.
* There are some other things we may need to tell YANK about how to set up systems in explicit solvent or build in missing atoms/residues.
* There are some run parameters too, like how many iterations to use, what kind of restraints, etc.  Most of this should eventually be fully automated, but there are a few parameters right now.

We have a few options for how to specify this:
* Python scripts that use the `Yank` module.  All parameters are coded in Python.
* Command-line scheme, perhaps using Robert's commandline tool, so we can say something like
  * `yank setup` to set up a calculation
  * `yank run` to run/resume a calculation
  * `yank info` to get some quick info on progress
  * `yank analyze` to analyze a calculation
* Some sort of input parameter file format, like XML or JSON

Thoughts?

**Comment by andrrizzi** [comment]
All of this is implemented.
