### ISSUE TITLE
Pipeline for non-example workflows

### ISSUE THREAD

**Issue by drthock** [choderalab/yank#422]
Hello 

Fantastic project you have! I'm looking through the example scripts/calculations, and everything seems to be working for me, but I am a little confused about the workflow for getting non-packaged workflows to run. 

It appears that `setup.sh` in setup does a lot of the work (in terms of getting everything parameterized), but I'm not sure where the actual complex is taken into account. If I have an example system that I have a docked pose for, and would like to calculate the free energy of binding for, what are the steps to getting into the proper input format? 

Thanks!

**Comment by andrrizzi** [comment]
Hi!

I think the easiest way you have to set up a calculation is to break your docked pose into two files
# a `.pdb` file with your clean protein (i.e. no ions, no water molecules, no ligand)
# a `.mol2` file with your ligand in the docked pose
and then write a YAML script similar to [this one](https://github.com/choderalab/yank/blob/0.8.0/examples/abl-imatinib-explicit/yank.yaml) and run on the console `yank script --yaml your_yaml_script.yaml`.

Apologies if we still have to write good documentation, but you can find some more info about the YAML script syntax [here](https://github.com/choderalab/yank/tree/0.8.0/examples/yank-yaml-cookbook).

Be aware though that YANK is still _very experimental_ and it will change quite a bit until it's 1.0 release (which should not be too far away).

Hope this helps!

**Comment by spadavec** [comment]
@andrrizzi Thank you so much for all the help! This looks to be working for me perfectly; just to clarify, it looks like running that yaml script will just run the entire process, without having to go through the intermediate steps outlined in your documentation (e.g. `yank prepare binding amber ...` and `yank run`) manually?

**Comment by andrrizzi** [comment]
> yaml script will just run the entire process, without having to go through the intermediate steps outlined in your documentation

That's exact. That process has been automatize with the last release, but we haven't had time to write the documentation yet.

Again, be aware that we are still working to validate the calculations and solve few problems. For starters, if your ligand is charged, the created system won't be neutralized correctly (this is a bug I'm fixing now, but it won't be available until the next YANK release). Even if your ligand is neutral, we are still working to correct for long range interactions during the calculation of free energies (see #339).

**Comment by spadavec** [comment]
Thanks for the clarification! I'm aware this is all pretty new software and there are challenges to overcome, but I'm still very thankful for all you've done so far! Can't wait to see how far I can push it in its current state :)

**Comment by andrrizzi** [comment]
I'll close this to keep the issue tracker clean, but feel free to reopen if you need more help.
