### ISSUE TITLE
Split out yank examples into separate yank-examples package?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#426]
It may be useful to split out the yank `examples/` directory into a separate `yank-examples` conda package to keep the standard `yank` package quick and easy to install.

I think this would just involve maintaining separate `yank` and `yank-examples` conda recipes that would stay in sync with version number. Examples would still be installed to `$PREFIX/share/yank/examples`

It should be very easy for me to do this if people think this is a good idea.

**Comment by andrrizzi** [comment]
I'd wait to do this until the examples are all fixed. With the new YAML syntax require very few input files, so probably it won't be as bad when I'll clean up everything. We can create a new repo if things are still quite slow.

**Comment by jchodera** [comment]
I don't think we need to create a new repo---we can just create separate `conda` recipes:
* `yank` installs just `yank`, using the `build.sh`:
```bash
#!/bin/bash
pip install .
```
* `yank-examples` installs just the examples, using the `build.sh`:
```bash
mkdir $PREFIX/share/yank
cp -r examples $PREFIX/share/yank/
```

**Comment by andrrizzi** [comment]
Oh! Sorry, I read that too quickly. That's a great idea!

**Comment by andrrizzi** [comment]
What if instead we remove the installation of the examples from the `dev` version, but we keep it in the omnia release?

**Comment by jchodera** [comment]
I was thinking we would test both recipes (yank and yank-examples) in
travis? We would only build yank-examples in one branch of travis tests.

**Comment by andrrizzi** [comment]
We can still test the examples in travis even if they are not copied in the `share/` folder, right? They should still be in the conda `egg` directory. Or am I missing something?

**Comment by jchodera** [comment]
They're also in the `examples/` directory, since we have the cloned github repo too!

But it's good to test that we can correctly build and install the examples package in one of the travis branches.
