### ISSUE TITLE
Running YANK with OpenCL or CUDA

### ISSUE THREAD

**Issue by a-palyanov** [choderalab/yank#432]
I have installed anaconda, YANK, and everything from the "Required" list - OpenMM, NetCDF, HDF5, netcdf4-python, numpy and scipy (under Ubuntu 16.04).
"yank selftest" command outputs the following:
# 

Running doctests for all modules...
/home/andrey/anaconda2/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
2016-07-23 13:43:16,888: Setting up the system for T4lysozyme, vacuum and p-xylene
All doctests pass.
# 

Seems quite ok.
next, "python -m simtk.testInstallation" seems to work properly too:
# 

There are 4 Platforms available:
1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces
Median difference in forces between platforms:
Reference vs. CPU: 1.98032e-05
Reference vs. CUDA: 2.15064e-05
CPU vs. CUDA: 1.55407e-05
Reference vs. OpenCL: 2.15046e-05
CPU vs. OpenCL: 1.5525e-05
CUDA vs. OpenCL: 1.33674e-07
# 

"yank platforms" indicate the same 4 platforms available (OpenCL and CUDA drivers are installed).

And now the problem:
Using the option " --platform=OpenCL" or "--platform=CUDA" added to the default command 
"# Run the simulation with verbose output:
echo "Running simulation..."
yank run --store=output --verbose"
in the file run.sh (of the p-xylene-explicit example), results in the work of the program during a dozen of seconds (with the output which is attached to this message) which doesn't seems to be a proper way of functioning.
[yank.output.txt](https://github.com/choderalab/yank/files/379442/yank.output.txt)
At the same time, if I run the original example, it seems to work correctly (during many hours) which finally results in calculated free energy value. And during this work the program for sure uses my GPU according to its power consumption and fans speed, which stops when calculations are complete.

Any suggestions on what I'm probably doing wrong?
Thanks!

**Comment by Lnaden** [comment]
We have added the platform option through #518 and it should let you select which one you want. If none is chosen, YANK tries to figure out which is the fastest at run time and runs with that.

We are also removing the old CLI in favor of YAML files with the upcoming 1.0 release, but the ability to choose platform will remain. 

Hopefully this resolves the issue
