### ISSUE TITLE
Running yank on a node with multiple GPUs in serial.

### ISSUE THREAD

**Issue by jlerche** [choderalab/yank#436]
I'm running yank on a machine that has 3 GPUs, I would like to launch 3 calculations in parallel with the goal that 1 GPU will run 1 job. Can I use CUDA_VISIBLE_DEVICES masking prior to launching each job to specify which one it uses or does yank determine that dynamically?

Using 0.9.0

**Comment by jchodera** [comment]
Yes, absolutely! Each distinct job would just set `CUDA_VISIBLE_DEVICES` to a different integer (0, 1, or 2) for each job. YANK just uses the default GPU for each process, so this should result in each process using a separate GPU.

We'll add some information about this to the documentation.

**Comment by Lnaden** [comment]
Note to self to update documentation on this

1.0 touched

**Comment by Lnaden** [comment]
Resolved back on #439, including in the "running yank" documentation now.
