### ISSUE TITLE
yank selftest failed

### ISSUE THREAD

**Issue by Laura412** [choderalab/yank#440]
FATAL: Error inserting nvidia (/lib/modules/../weak-updates/nvidia.ko): No such device
Segmentation fault
This error message occurs even though nvidia.ko exits in this directory.
How can I make yank work?

**Comment by jchodera** [comment]
You must be trying to run from the head node (which does not have GPUs).

Follow the instructions for getting an interactive GPU job:
```bash
qsub -I -l walltime=02:00:00,nodes=1:ppn=1:gpus=1:exclusive -l mem=4G -q active
```

See more docs here:
https://github.com/cBio/cbio-cluster/wiki/MSKCC-cBio-Cluster-User-Guide#submitting-gpu-jobs-to-the-batch-queue-system

**Comment by jchodera** [comment]
Note that this is a cluster-specific issue. The yank docs only contain general instructions. Different clusters (like ours) will have different batch queue systems and different schemes for running interactively or via the batch mode.

We are still revision the docs on running yank, but do let us know if you can complete the self test!

**Comment by Lnaden** [comment]
@Laura412 Is this issue still occuring for you? There have been major improvements to the `selftest` command with recent updates which should provide somewhat more helpful information when run if this problem is still occurring.

**Comment by Laura412** [comment]
No, it's working fine! Thank you
