### ISSUE TITLE
Fix platform and precision options in Yank

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#441]
Currently they can be passed but they are not attached to anything.

**Comment by andrrizzi** [comment]
OpenMM uses `single` by default, so we want to set our default value to `mixed` when possible.

**Comment by Lnaden** [comment]
This is also a good time to unify this option's handling. Right now in `commands/prepare.py` you can specify a precision mode with the `--precision` flag. However, Im not sure you can do it in YAML syntax. By the same token, you can specify a platform in the command line, but not in YAML. We should fix this at this time too

**Comment by jchodera** [comment]
Should we go exclusively with YAML or exclusively with command-line, or have some sort of precedence scheme?

**Comment by andrrizzi** [comment]
@Lnaden You are right, both those options cannot be specified with the YAML syntax, and that's because you can pass them to `Yank` but they are not attached to anything, so even those in `prepare.py` don't work at the moment.

> Should we go exclusively with YAML or exclusively with command-line, or have some sort of precedence scheme?

Currently, YAML and `prepare` commands are exclusives so we wouldn't need a precedence scheme. Unless you're suggesting modifying the YAML-invoking command to something like
```bash
yank script --yaml=yank.yaml --platform=CUDA --precision=mixed  # platform and precision are not currently in
```

**Comment by jchodera** [comment]
I think precision should definitely be encoded in the YAML file.

Should platform? This is probably the single most common thing users will want to change. Most users will just have YANK select the default platform automatically. Some users will want to force a specific platform for a specific reason. Should they change the YAML file, or should they change the command-line?

I could see us doing a combinatorial experiment over precision models, but not sure if we'd ever want to do that over platforms.

**Comment by andrrizzi** [comment]
Good point! I like the idea of having both with command line option having priority over YAML script.

**Comment by Lnaden** [comment]
-1 on having both. I think the command line and yaml file should be mutually exclusive. This is a bit elitist of me, but I think if you are going to have a file which can set all the options, you should not be able to specify them another way, and having multiple ways to set it is ambiguous and confusing.

**Comment by andrrizzi** [comment]
Hmm, you're probably right! I can add `precision` to the YAML file and `platform` to the command as John suggested then.
