### ISSUE TITLE
Error running exclusive instead of shared GPU mode.

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#443]
When I run on the cluster with `exclusive` GPU instead of `shared` I get

```
Traceback (most recent call last):
  File "/cbio/jclab/home/andrrizzi/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.1.dev0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/cli.py", line 118, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 41, in dispatch
    yaml_builder.build_experiments()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1280, in build_experiments
    self._run_experiment(combination, output_dir)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 2254, in _run_experiment
    yank.run()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yank.py", line 510, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/repex.py", line 832, in run
    self._initialize_resume()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/repex.py", line 1077, in _initialize_resume
    self._minimize_and_equilibrate()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/repex.py", line 1420, in _minimize_and_equilibrate
    self._minimize_replica(replica_index)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/sampling.py", line 583, in _minimize_replica
    self._cache_context()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/sampling.py", line 378, in _cache_context
    self._fully_interacting_context = openmm.Context(state.system, integrator, self.platform)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 14073, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible CUDA device is available
```

It looks like this can be related to pandegroup/openmm#1501: We have already a cached context for the alchemical system and maybe when we create another one for the fully interacting system we run out of GPU memory.

**Comment by jchodera** [comment]
Is it that we are running out of memory (seems unlikely!) or that we are
not allowed to have more than one Context open on the GPU at once in
exclusive mode?

Also, what happens with OpenCL?

**Comment by andrrizzi** [comment]
Good questions! Will look into it tomorrow.

**Comment by andrrizzi** [comment]
You were right! This script fails with the same error on the cluster in exclusive mode, and it can't be a memory issue here
```python
from simtk import openmm, unit
from openmmtools import testsystems

def main():
    timestep = 2 * unit.femtoseconds
    platform = openmm.Platform.getPlatformByName('CUDA')

    ho1 = testsystems.HarmonicOscillator()
    integrator1 = openmm.VerletIntegrator(timestep)
    context1 = openmm.Context(ho1.system, integrator1, platform)

    ho2 = testsystems.HarmonicOscillator()
    integrator2 = openmm.VerletIntegrator(timestep)
    context2 = openmm.Context(ho2.system, integrator2, platform)

if __name__ == '__main__':
    main()
```
I guess either we are stuck with `shared` mode or we can't cache contexts.

For optimization in the future we could think of caching positions of the previous `n` steps and compute all the fully interacting energies only once every `n` iterations, so that we don't destroy/recreate contexts at every iteration.

**Comment by jchodera** [comment]
The current scheme should be caching two contexts and not recreating them
every iteration. If it isn't doing this, let me know!

Do you think it is OK if we insist people use shared mode, or do we have to
provide an option for only using one Context at a time (that will run
slower)? I think we might suggest this on the issue tracker as an option we
can add in the future and only address it if we have users who require it.

Also, did OpenCL have the same trouble in your test?

**Comment by andrrizzi** [comment]
> I think we might suggest this on the issue tracker as an option we can add in the future and only address it if we have users who require it.

Sounds good. We could also add an option to not compute the fully interacting energies which would be directly compatible with `exclusive` mode.

> Also, did OpenCL have the same trouble in your test?

Sorry, I forgot to add this. OpenCL still gave me problems with a slightly different error: `Exception: Error initializing context: clCreateContext (-33)`

**Comment by jchodera** [comment]
> Sounds good. We could also add an option to not compute the fully
interacting energies which would be directly compatible with exclusive mode.

You mean just skip it completely, or do it during the analysis instead?

**Comment by andrrizzi** [comment]
I mean skip it completely. I was under the impression that for solvation free energies the contribution of the fully interacting state may not be that important.

**Comment by jchodera** [comment]
It would be for PME, and potentially other cases as well.

**Comment by andrrizzi** [comment]
So we want to make it mandatory even when we use `CutoffPeriodic`? I'm not saying we shouldn't, I'm just trying to understand since it could give us a good speed up (by running in exclusive mode + not having to destroy/create contexts + not having to compute more energies).

**Comment by jchodera** [comment]
For us, the speedup will be minimal to nonexistent. We really just have to
worry about users who may not have control about whether they are locked
into exclusive more or not.

I think it's fine to have a power user option to disable it but I think our
default protocols should be to "do the right thing" and include it.

**Comment by andrrizzi** [comment]
I see, thanks.

What do you think about automatic detection of mode instead of adding an extra option (i.e.
try to cache two contexts, if exception is raised then switch to create/delete contexts every time)?

**Comment by jchodera** [comment]
That would be ideal!

**Comment by andrrizzi** [comment]
Great! I think I can easily add this in #442 .

**Comment by jchodera** [comment]
We can just use `shared` mode right now on our local cluster, so this may not actually be high priority.

**Comment by Lnaden** [comment]
Leaving this open since it is a persistant issue, but removing 1.0 fix due date.

1.0 touch

**Comment by jchodera** [comment]
I think this is just a documentation issue. We need to make sure people use their GPUs in "shared" mode.
