### ISSUE TITLE
Yank allows purely numeric mol2 filenames as input, but tleap throws syntax error

### ISSUE THREAD

**Issue by jlerche** [choderalab/yank#465]
When a mol2 file, for example '5343.mol2', is used as an input file name, yank proceeds just fine until the tleap step which then throws a syntax error. [Pull request 464](https://github.com/choderalab/yank/pull/464) offers a prototype check (most likely not in the right place though) to catch these kind of filenames and provides an error message.

found in yank 0.9.0

**Comment by jchodera** [comment]
Thanks!

As noted in #464: I think the better way to handle this is to ensure that we write an intermediate filename that tleap can read, rather than not be able to deal with numeric names.

**Comment by jlerche** [comment]
Agreed, that is probably a better way of handling it.

**Comment by jlerche** [comment]
It also seems that tleap does not allow variable names where the first and last character are digits

534E56 throws error but 534E5T is fine.

**Comment by andrrizzi** [comment]
Hmm, this is weird. The [wrapper of `TLeap`](https://github.com/choderalab/yank/blob/master/Yank/utils.py#L1247) I wrote actually works only on hardcoded filenames that are copied to a temporary folder exactly to avoid problems with file names/paths, so this should not come up unless you try to run the `tleap` script manually.

I'll try to dig into why this happens. And thanks for the PR! I'll review it after I understand better what's happening.

**Comment by jlerche** [comment]
The pull request is outdated but it's a matter of checking fname[0].isdigit() and fname[-1].isdigit(), maybe. I didn't exhaustively test the possibilities.

re tleap: If the original mol2 filename is kept as the intermediate one (which I believe it does, at least judging by the tleap scripts that were created) then the issue will still persist. A possibility might be to append an alphabetical character or string to the filename depending on how many mol2s there are.

**Comment by andrrizzi** [comment]
> at least judging by the tleap scripts that were created

The tleap scripts that are saved for logging contains the original file names, but the tleap script that is actually _executed_ by Yank substitute those names with `molecule1.mol2`, `molecule2.mol2` names so it should not have that problem.

**Comment by Lnaden** [comment]
@andrrizzi do you know if this is still an issue and/or if it got fixed from other updates to YAML since then?

1.0 touch

**Comment by andrrizzi** [comment]
Ah! Thanks for reminding me about this. It should be still there. I'll check it today.

**Comment by andrrizzi** [comment]
I was able to reproduce this. The problem is not with file names which are hardcoded in the executed script, but with the name of the group which is set to the molecule id. For example, having
```yaml
molecules:
  534E56:
    filepath: 534E56.mol2
```
will result in a line in the executed tleap script like
```
534E56 = loadMol2 moli1.mol2
```
which tleap doesn't like.

**Comment by jchodera** [comment]
Is this simply rectified by prepending with a string character?

**Comment by andrrizzi** [comment]
Yep, that works for the `loadMol2` directive! That's how I'm currently planning to solve it.
