### ISSUE TITLE
Compute entropies and enthalpies in analyze.py using MBAR

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#466]
Currently, `analyze` does not use MBAR to compute entropies and enthalpies:

https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L229-L314

We should replace this with a call to [`mbar.computeEntropyAndEnthalpy()`](https://github.com/choderalab/pymbar/blob/master/pymbar/mbar.py#L1096).

**Comment by Lnaden** [comment]
Fixed by #470
