### ISSUE TITLE
Add instructions to installation docs to test optional OpenEye install

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#467]
We should add a section to the OpenEye installation docs to have the user check if they were installed correctly, should they install them.

**Comment by jchodera** [comment]
Better yet, perhaps `yank platforms` or `yank --version` or `yank status` or something should report on whether the OpenEye tools are installed and working correctly.

**Comment by Lnaden** [comment]
I added the check to the `yank selftests` command and online documentation in #484, hopefully this is sufficient tests.
