### ISSUE TITLE
Implement automated hydration free energy calculations / test with FreeSolve dataset

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#47]
Might be nice if we could do fast automated hydration free energies via OpenMM /  Yank

**Comment by davidlmobley** [comment]
I think I reawakened this issue by e-mail with John recently. It sounded like he is close.

**Comment by jchodera** [comment]
Spent the last few days fixing some important bugs.  Stay tuned!

**Comment by Lnaden** [comment]
This has been resolved with the hydration free energies and the `yank-examples` now has a mini FreeSolv database

**Comment by davidlmobley** [comment]
Thanks, @Lnaden ! Are we close to having it work for SMIRFF FFXML forcefields as well? Should I create a separate issue for that?

**Comment by Lnaden** [comment]
I think that a new issue would be good for that. Getting new FF's in is something on the todos, but we are super dependent on the amberff's for now.

**Comment by Lnaden** [comment]
@davidlmobley I went ahead and opened a general FFXML issue for post 1.0 release. Feel free to add to that discussion as you like!
