### ISSUE TITLE
Current conda recipe installs both openmm and openmm-dev

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#473]
The current recipe has both `openmm-dev` and non-dev `openmoltools`/`openmmtools`/`alchemy` as dependencies. I think the last ones install `openmm`.

Log:
```
bash-4.1$ conda install yank-dev
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /cbio/jclab/home/andrrizzi/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.2            |           py27_0          26 KB
    openmm-7.0.1               |           py27_0        11.5 MB  omnia
    openmm-dev-0.0.0           |           py27_0        11.6 MB  omnia
    alchemy-1.2.0              |           py27_0          36 KB  omnia
    parmed-2.5.1               |           py27_0         1.0 MB  omnia
    openmmtools-0.8.2          |           py27_1         7.8 MB  omnia
    openmoltools-0.7.1         |           py27_3         4.3 MB  omnia
    yank-dev-0.0.0             |           py27_0        27.8 MB  omnia
    ------------------------------------------------------------
                                           Total:        64.0 MB

The following NEW packages will be INSTALLED:

    alchemy:      1.2.0-py27_0 omnia
    openmm:       7.0.1-py27_0 omnia
    openmm-dev:   0.0.0-py27_0 omnia
    openmmtools:  0.8.2-py27_1 omnia
    openmoltools: 0.7.1-py27_3 omnia
    parmed:       2.5.1-py27_0 omnia
    yank-dev:     0.0.0-py27_0 omnia
```

If this is expected behavior, **we need to decide whether we want to use all dev versions or all non-dev versions**. Mixing causes problems.

**Comment by jchodera** [comment]
> The current recipe has both openmm-dev and non-dev
openmoltools/openmmtools/alchemy as dependencies. I think the last ones
install openmm.

Yikes! We should only be using openmm. We are migrating away from -dev
packages, and the current up to date openmm dev packages are actually
called "openmm" and uploaded to the dev channel label.

> bash-4.1$ conda install yank-dev Fetching package metadata .........
Solving package specifications: .......... Package plan for installation in
environment /cbio/jclab/home/andrrizzi/miniconda: The following packages
will be downloaded: package | build
---------------------------|----------------- conda-env-2.5.2 | py27_0 26
KB openmm-7.0.1 | py27_0 11.5 MB omnia openmm-dev-0.0.0 | py27_0 11.6 MB
omnia alchemy-1.2.0 | py27_0 36 KB omnia parmed-2.5.1 | py27_0 1.0 MB omnia
openmmtools-0.8.2 | py27_1 7.8 MB omnia openmoltools-0.7.1 | py27_3 4.3 MB
omnia yank-dev-0.0.0 | py27_0 27.8 MB omnia
------------------------------------------------------------ Total: 64.0 MB
The following NEW packages will be INSTALLED: alchemy: 1.2.0-py27_0 omnia
openmm: 7.0.1-py27_0 omnia openmm-dev: 0.0.0-py27_0 omnia openmmtools:
0.8.2-py27_1 omnia openmoltools: 0.7.1-py27_3 omnia parmed: 2.5.1-py27_0
omnia yank-dev: 0.0.0-py27_0 omnia
>
> If this is expected behavior, we need to decide whether we want to use
all dev versions or all non-dev versions. Mixing causes problems.

We should be using non-dev versions throughout!

**Comment by andrrizzi** [comment]
Ok! I'll fix the recipe with the next PR.
