### ISSUE TITLE
Update analyze.py to be able to extract just hydration free energies

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#49]

**Comment by Lnaden** [comment]
Does the ability to do hydration free energy simulations resolve this, or did you mean a more general solvation free energies of arbitrary solvents, or hydration free energies while also getting binding free energies?

1.0 touch

**Comment by jchodera** [comment]
I think we can close this since YANK now supports hydration free energy calculations, though we still need a programmatic API to extract the free energy estimates via Python.
