### ISSUE TITLE
Fix test_yaml.test_expand_molecules test

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#490]
Current test relies on literal strings to compare molecule names in YAML structure. Py3 however uses generators to get keys from dictionaries, these result in non-regular name patterns that make it hard to compare nested dictionaries as the test is currently structured. 

The test is disabled for now (called `notest_expand_molecules test` in the file) until we come up with a better test.

**Comment by andrrizzi** [comment]
Thanks for opening the issue!
