### ISSUE TITLE
Design a better test for test_order_phases in test_yaml.py

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#493]
Because of random ordering:

`assert list(parsed['absolute-binding'].keys()) != ordered_phases`

can fail because the two lists are in the same order. We need to come up with a better control test.

**Comment by andrrizzi** [comment]
This should be fixed when #491 is implemented. I'm tackling it now.

**Comment by andrrizzi** [comment]
Implemented in #503 .
