### ISSUE TITLE
Add more complete documentation for every options/key that can be set in the `.yaml` files.

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#496]

**Comment by Lnaden** [comment]
Possibly template off the [conda meta.yaml documentation](http://conda.pydata.org/docs/building/meta-yaml.html) so not a single feature is missed.

**Comment by jchodera** [comment]
I think it would be awesome if we could hyperlink the cookbook recipe. I don't think we can do that in github-flavored markdown, but sphinx may have a way to do that.

**Comment by Lnaden** [comment]
Well right now the cookbook recipe is just a pointer at the file which just loads a raw dump of the text in the file. Since the cookbook is not formatted in any kind of sphinx way, I'm not sure what we would be pointing at besides the literal file.

**Comment by jchodera** [comment]
Obviously, we'd have to change that and format the links by hand, but this is an alternative to the conda meta.yaml-style documentation, which I'm not actually a huge fan of.

**Comment by Lnaden** [comment]
What don't you like about the conda meta.yaml style? Are you suggesting doing something like this:

One page has the links, each category is its own page which is a subpage of the main one.

![markup](http://i.imgur.com/tnKx0CA.png)

**Comment by Lnaden** [comment]
@jchodera would this work instead of having everything on one page?

**Comment by jchodera** [comment]
Sure!

**Comment by Lnaden** [comment]
Reopening due to typo in pr which closed it on accident
