### ISSUE TITLE
Add ability to estimate extrapolated free energy differences with perturbed systems

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#50]

**Comment by Lnaden** [comment]
@jchodera has this been resolved with the expanded cutoff systems?

**Comment by Lnaden** [comment]
Bumping this as we are doing this for the expanded cutoff systems already, does this sufficiently fix this problem @jchodera?

**Comment by jchodera** [comment]
I think the original idea was something along the lines of "allow extrapolation to different GBSA models" or something, but that's something likely better handled via post-processing at this point.
