### ISSUE TITLE
Performance tuning parameters like number of iterations and replicas

### ISSUE THREAD

**Issue by jlerche** [choderalab/yank#502]
I was wondering if there were guidelines for determining the values of those parameters that affect the length of a simulation without sacrificing (too much) accuracy, namely iterations and replicas. The examples seem to stick to around 1000, but ideally we're looking for a way to determine them programmatically if that's possible.

**Comment by jchodera** [comment]
We're working on ways to add automatic convergence diagnostics and automated checking if the code has reached prespecified precision goals, but this ability isn't in the code yet. The code is still very much in pre-release cleanup phase, with a lot of work left to do on the analysis side to accurately estimate the statistical error and whether the simulation has signs of poor convergence. Please bear with us as we work toward a 1.0 release!

**Comment by andrrizzi** [comment]
Unfortunately, to optimally choose the number of replicas, there is nothing that is currently supported and we are still working on it.

One suggestion I could give you on determining simulation length is to check the beginning of the output of `yank analyze` which should be something like
```
Read 2500 iterations, 19 states
Reading energies...
Done.
Deconvoluting replicas...
Done.
[500, 2048.4004]
...
```
The first line here tells you how many iterations you run, the last one tells you the number of initial equilibration iteration (i.e. 500), which is detected by [an heuristic that maximizes number of effectively uncorrelated samples](https://github.com/choderalab/pymbar/blob/master/pymbar/timeseries.py#L726). Also the final given estimation of the free energy comes with an estimated statistical uncertainty.

If you see that the system has just equilibrated and/or uncertainties are still big, you can just resume and extend your simulation to get more data.

Hope this helps.

**Comment by Lnaden** [comment]
Post 1.0 issue.

**Comment by spadavec** [comment]
@andrrizzi (apologies for digging up old cases) -- In you example above, are there any guidelines regarding what multiple of your equilibrium iteration # should be relative to your total iteration number (i.e. in your case 500 vs. 2500, or 1/5)?

**Comment by jchodera** [comment]
Right now, if you can use 0 equilibration iterations and get a stable simulation, this is the recommended approach. That way, the automated equilibration detection used in data analysis will use as much data as it can in estimating binding affinities.

Equilibration iterations use a smaller timestep and are intended for the case where minimization is insufficient to produce a stable simulation. We are hoping to get rid of the need to manually mess with equilibration iterations in future updates, replacing it with a more automated retry and timestep adjustment scheme.

@lnaden, maybe you can put this in the best practices docs?
