### ISSUE TITLE
Have analyze module cache MBAR solution

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#52]

**Comment by Lnaden** [comment]
Was this resolved by #470 when the MBAR object is created an carried through, or did you want to actually store the `f_k` array to file to be used as an initial guess next time `analyze` has been called?

**Comment by jchodera** [comment]
At some point, I experimented with storing `f_k` each iteration, initializing the MBAR estimate from the previous iteration (if one was available). There were some practical iterations:
* It could slow things down unless we figure out how to do this asynchronously (e.g. using [dynamic process management](http://pythonhosted.org/mpi4py/usrman/overview.html#dynamic-process-management) in `mpi4py` with MPI-2)
* Re-analyzing the trajectory for equilibration start and statistical inefficiency is slow, so we could either use all the data for the online estimate of `f_k` or update the estimates of equilibration start and statistical inefficiency each `nupdate` iterations.
* Estimates after 1 or a few iterations don't make much sense, though I think they can still be computed

**Comment by Lnaden** [comment]
In my own experience, MBAR initializes faster if you feed it an `f_k` even from just a few samples, and even if you add more states on after the fact. That said, the more samples you have, the slower it gets, so I really think we would have to do some type of parallelization to have a practical implementation.

> re-analyzing the trajectory for equilibration start and statistical inefficiency is slow,

Yes, but for the on-the-fly analysis we can probably skip that part. It will change the answer, but more by bias than anything. We just have to tell the user that the numbers are inaccurate and to run proper statistical analysis on it later.

As a side thought, would the `timesereies` module benefit from some attempted cython speedup (I say attempted so as not to make it mandatory for `pymbar`).

> Estimates after 1 or a few iterations don't make much sense, though I think they can still be computed 

Both are true, low sampling is garbage for stats. It could just be as simple as adding a `if iteration < min_iteration` or something.

**Comment by Lnaden** [comment]
Depends on analyze.py refactor, touched for 1.0

**Comment by Lnaden** [comment]
Implemented as part of the online analysis in #712, and cached for the API calls on #660
