### ISSUE TITLE
MBAR analysis: Actual column sum for state 0 was 4731.000000

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#520]
After running calculations with the new scheme for the fully interacting energy, the analysis gives:

```
Traceback (most recent call last):
  File "/cbio/jclab/home/andrrizzi/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.11.1', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/cli.py", line 74, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/commands/analyze.py", line 63, in dispatch
    analyze.analyze(args['--store'])
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/analyze.py", line 502, in analyze
    (Deltaf_ij, dDeltaf_ij) = estimate_free_energies(ncfile, mbar = mbar)
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/analyze.py", line 270, in estimate_free_energies
    (Deltaf_ij, dDeltaf_ij) = mbar.getFreeEnergyDifferences()
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/pymbar-2.1.0b0-py2.7-linux-x86_64.egg/pymbar/mbar.py", line 410, in getFreeEnergyDifferences
  File "/cbio/jclab/home/andrrizzi/miniconda/lib/python2.7/site-packages/pymbar-2.1.0b0-py2.7-linux-x86_64.egg/pymbar/mbar.py", line 1665, in _computeAsymptoticCovarianceMatrix
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 46930.000000. 1 other columns have similar problems
```

**Comment by andrrizzi** [comment]
The first column of the energy in the nc file is (for frame 1)
```python
>>> u_kln, N_k, u_n = analyze.extract_ncfile_energies(nc_file)
>>> print u_kln[:, 0, 1]
[  0.00000000e+00   9.96920997e+36   9.96920997e+36   9.96920997e+36
   9.96920997e+36   9.96920997e+36   9.96920997e+36   9.96920997e+36
   9.96920997e+36   9.96920997e+36   9.96920997e+36   9.96920997e+36
   9.96920997e+36   9.96920997e+36   9.96920997e+36   9.96920997e+36
   9.96920997e+36   9.96920997e+36   9.96920997e+36   9.96920997e+36]
```
I'm now using the serialized systems (reference, LJ only, LJ only expanded) to figure out where all this energy is coming from.

**Comment by jchodera** [comment]
@Lnaden Can you take a look at this?

**Comment by andrrizzi** [comment]
Weird. The energies for the first 10 frames computed by my script (i.e. not the ones saved in the ncfile) for the deserialized `reference_system`, `LJ_only_system` and `LJ_only_expanded_system` are very reasonable:
```
reference energies[:10] (kT): [-27080.99265357 -26974.02275803 -26959.81661475 -26968.08427595 -27082.44583904 -27462.99028068 -27371.47663495 -27529.81622539 -27709.21269983 -27946.90050954]
LJ only energies[:10] (kT): [ 4323.71727797  4229.66143066  4401.25089419  4124.79823846 4211.20810415 4275.57901825  4147.58286215  4265.91595648  4189.35246594  4335.46441865]
LJ only expanded energies[:10] (kT): [ 4319.24518392  4225.23551218  4397.43984306  4121.38808925  4208.01743866 4272.53063944  4145.49646956  4263.38781532  4186.98593688  4333.36938048]
```
I'm not sure how we can get orders of magnitude of `e+36`. We are probably doing something fishy with how we compute the energies in `sampling.py`.

If you want to take a look at the script I'm using to test this, it's on the cluster at `andrrizzi/test_full_energy.py`.

**Comment by jchodera** [comment]
The elements of `fully_interacting_energies` are only filled in if [these conditions are true](https://github.com/choderalab/yank/blob/master/Yank/sampling.py#L877-L879):
```python
        # Only the root node will write data.
        if self.mpicomm is not None and self.mpicomm.rank != 0:
            return

        if (self.reference_LJ_state is not None) and (self.reference_LJ_expanded_state is not None) and (self.reference_state is not None):
            self.ncfile.variables['fully_interacting_energies'][self.iteration, :] = self.u_k[:]
            self.ncfile.sync()
```
Perhaps there is something wrong with this? Can you confirm that this variable is being filled in?

Also, we can move this writing to be before the `super` call and avoid the need to call `self.ncfile.sync()` again, I bet.

**Comment by Lnaden** [comment]
Ill take a look at it when i can. Im stuck in dmv lines tonight apparently. :/

**Comment by andrrizzi** [comment]
> Can you confirm that this variable is being filled in?

I think it is because the standard deviation of the difference between expanded energies and reference energies is 0 up to 3 decimal points. I'll test it explicitly.

My first guess is instead that we are passing a `numpy.float` type, but we are saving it in the ncfile as a different one. I'll test this too.

**Comment by andrrizzi** [comment]
@jchodera you are right! When restoring the `fully_interacting_state` [we check for `LJ_only_state`](https://github.com/choderalab/yank/blob/master/Yank/sampling.py#L345) group in the nc file which doesn't exist. I'll fix this and see if it changes.
```python
# Fully interacting state
if 'LJ_only_states' in ncfile.groups:
    ncgrp_stateinfo = ncfile.groups['fully_interacting_states']
```
