### ISSUE TITLE
Remove redundant storing of reference system in nc file

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#522]
With the new scheme for the fully interacting state, we are currently store the reference system twice: one in `Yank` and one in `ModifiedHamiltonianExchange`. We should probably remove the one in `Yank`.

**Comment by Lnaden** [comment]
Post 1.0 issue and part of writer API refactor. Will help with #41

**Comment by Lnaden** [comment]
I think the API fixes, the Repex Reporter, and OpenMMTools changes have fixed this. There should only be a minimum number of reference system objects stored, the rest are are stored as pointers. 

@andrrizzi can correct me if I am wrong though and reopen this issue
