### ISSUE TITLE
Do not pass fully interacting state to repex for NoCutoff scheme

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#523]
I didn't test this, but looking at the code I think we are still computing the energies for `reference_system`, `LJ_only_system` and `LJ_only_expanded_system` also for `NoCutoff` nonbonded method. We should probably pass only `None` to `simulation.create()` for these parameters if that's the case.

**Comment by Lnaden** [comment]
post 1.0 issue

**Comment by jchodera** [comment]
Could this lead to incorrect results in implicit solvent? If so, we need to address this for 1.0.

**Comment by andrrizzi** [comment]
I don't think it will. I think in this case we'd just reweight the lambda=1 to the same state, since there's no periodic electrostatics and expanding the LJ cutoff does not affect energies. It's probably just an optimization.

**Comment by jchodera** [comment]
OK, thanks!
