### ISSUE TITLE
Fix validation of combinatorial options

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#524]
I introduced a regression while implementing `schema` validation where combinatorial options are validated before expansion, which means that they are always rejected. I need to fix it and add tests for this situation.

**Comment by Lnaden** [comment]
Post 1.0 issue? @andrrizzi

**Comment by andrrizzi** [comment]
Sounds good.

**Comment by andrrizzi** [comment]
I'm actually having second thoughts on this. We can already have combinatorial options in the experiments section and there are several options that are complicated to expand/don't make much sense (e.g. `output_dir`, `resume_setup`, etc.).

I'll close this for now, but feel free to reopen if you think this is still worth implementing.
