### ISSUE TITLE
Analyze compute the energy difference between the wrong states

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#528]
The function `analyze.analyze()` extracts from the ncfile the number of states without taking into account the presence of the fully interacting state, and ends up computing the free energy difference between the fully interacting state and the next to last state for each phase [here](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L501-L508)
```python
# Accumulate free energy differences
entry = dict()
entry['DeltaF'] = Deltaf_ij[0,nstates-1]
entry['dDeltaF'] = dDeltaf_ij[0,nstates-1]
entry['DeltaH'] = DeltaH_i[0,nstates-1]
entry['dDeltaH'] = dDeltaH_i[0,nstates-1]
entry['DeltaF_restraints'] = DeltaF_restraints
data[phase] = entry
```
In general, since we treat the fully interacting state as special, we need to be careful during the analysis.

I'll soon open a PR with the fix.

**Comment by Lnaden** [comment]
Ah, yes, good catch. It may be better to just replace `[0,nstates-1]` with [0,-1] to make it independent of how much shifting we do at the head of the row.

**Comment by jchodera** [comment]
Can we also add the decomposition into restraining, charging, and nonbonded free energies (if those states are present)?

**Comment by Lnaden** [comment]
crap, I didn't see your post there John, the checks update but not comments on the same page

**Comment by andrrizzi** [comment]
Good idea! I think we can close this anyway and open a new issue for that.

**Comment by andrrizzi** [comment]
Closing this to open a better titled issue.
