### ISSUE TITLE
Add getter and setter decorators for `yank.something` simulation parameters

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#53]
Right now, many parameters in yank are set via the following scheme:

``` python

yank = Yank()
yank.n_iterations = 10
yank.timestep = 1.0
yank.other_thing = other_thing
```

To prevent insane combinations of these objects, it might be nice for us to use getter and setter decorators for _all possible_ properties.

**Comment by jchodera** [comment]
Might be partly tackled by switching out `repex`.

**Comment by Lnaden** [comment]
I might have time to handle this with PEP 8 cleanup, but this will probably wind up at 2.0

**Comment by andrrizzi** [comment]
This was addressed by the recent refactoring.
