### ISSUE TITLE
mc_displacement_sigma is misspelled in YAML docs

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#531]
See [here](http://getyank.org/latest/yamlpages/options.html#mc-displacemnt-sigma).

**Comment by jchodera** [comment]
Also [`randomize_ligand`](http://getyank.org/latest/yamlpages/options.html#randomize-liand).

We should probably each just take a pass through to see if we can spot more typos.

**Comment by Lnaden** [comment]
Not to self to fix pre 1.0
