### ISSUE TITLE
Control ligand Monte Carlo displacement/rotation during sampling from YAML?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#532]
We will want to disable Monte Carlo ligand displacement/rotation trials when using the Boresch restraints, but I don't see an option to disable those from the YAML file. Can we add that?

**Comment by andrrizzi** [comment]
Right! For the record, currently the way to set this through the API is to set `mc_atoms=None` in `ModifiedHamiltonianExchange.create()` but there's a bug in `ReplicaExchange`, and with Python3 it crashes on resuming.

**Comment by Lnaden** [comment]
Post 1.0 issue

**Comment by jchodera** [comment]
We need to be able to turn off MC rotation/translation in 1.0.
