### ISSUE TITLE
Allow user-specified integrator in YAML file

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#533]
If we're not going to get general MCMC into YANK 1.0, we should see if it would at least be easy to let the user select from a panel of integrators available in OpenMM and OpenMMTools. The important ones would be:
- `VelocityVerlet` - velocity Verlet
- `VVVR` - Langevin integrator
- `GHMC` - like VVVR, but Metropolized

There's a chance I may also finish a version of the [Leimkuhler g-BAOAB integrator](http://rspa.royalsocietypublishing.org/content/472/2189/20160138), which may permit much larger step sizes.

**Comment by Lnaden** [comment]
Post 1.0 Issue

**Comment by jchodera** [comment]
This should be a 1.0 issue.

**Comment by Lnaden** [comment]
This was partially implemented in #747 where the `LangvinSplittingIntegrator` was brought in and allows customizing `V R O` splittings with optional HMC evals. It does not implement everything requested in this issue, but does implement most of it. 

The question: Does #747 do enough to consider this issue closed?

**Comment by jchodera** [comment]
This should be sufficient!
