### ISSUE TITLE
GTX-1080 temporary workaround

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#537]
FYI, we may want to temporarily implement this: https://github.com/pandegroup/openmm/issues/1651#issuecomment-256186878

**Comment by Lnaden** [comment]
How long do we think this issue will persist?

1.0 touch

**Comment by jchodera** [comment]
We're trying to fix it before the OpenMM 7.1.0 release, though the preview builds still have the issue.

**Comment by Lnaden** [comment]
I think this got solved. We can re-open it if I'm wrong
