### ISSUE TITLE
Set up examples / test cases for SystemBuilder

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#55]
We want the following test cases to work initially:
- **T4 lysozyme L99A + p-xylene** (to compare to `prmtop/inpcrd` route)
  - T4 lysozyme: PDB file, to be parameterized with `app.ForceField` with specified forcefield file(s) and implicit/explicit solvent choice
  - p-xylene: mol2 file, to be parameterized with `gaff2xml`
- **CB[7] host-guest system**
  - CB[7] host: mol2 file
  - hosts: list of IUPAC names
- **ligand design**
  - RCSB ID with chain identifiers, to be parameterized with `app.Forcefield` with specified forcefield file(s) and implicit/explicit solvent choice
  - Chemdraw file containing one or more molecules, to be parameterized with `gaff2xml`

**Comment by jchodera** [comment]
Some of this might be punted to 2.0.

**Comment by Lnaden** [comment]
Test system have been moved, but systembuilder may need removed

**Comment by Lnaden** [comment]
Depreciating for new SystemBuilder post 1.0
