### ISSUE TITLE
Resume phases in deterministic order for MPI parallel processes

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#554]
`Yank.resume()` looks in the store directory for `.nc` files of the two phases, but we don't define an order in which they are executed. With Python 2 dictionary implementation, this order was random but deterministic, so parallel MPI processes were always running the same phase. With Python 3 this got broken. I'll open a PR with the fix soon.

**Comment by jchodera** [comment]
Thanks for catching this!
