### ISSUE TITLE
Parallelize setup of molecules and experiments via MPI if available

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#557]
Currently, [`YamlBuilder._setup_experiments()`](https://github.com/choderalab/yank/blob/master/Yank/yamlbuild.py#L1997-L2037) just has the first node set up all the experiments, but when we are charging numerous druglike ligands, this can take a while. It would be simple to parallelize this setup over the MPI processes with a simple idiom by changing
```python
        for _, experiment in self._expand_experiments():
            # set up experiment
```
to something like
```python
        if self._mpicomm is not None:
            [rank, size] = [self._mpicomm.rank, self._mpicomm.size]
        else:
            [rank, size] = [0, 1]
        experiments = [ experiment for (_, experiment) in self._expand_experiments() ]
        for experiment_index in range(rank, len(experiments), size):
            experiment = experiments[experiment_index]
            # set up experiment
```
There may be useful things like [itertools](https://docs.python.org/2/library/itertools.html) that make this even simpler...

**Comment by jchodera** [comment]
@andrrizzi : I believe setup is parallelized now---is that correct?

**Comment by andrrizzi** [comment]
Not yet! It's still performed on a single node, although it should be pretty easy to change that with the new MPI feature.
