### ISSUE TITLE
--nosolvent argument to 'yank analyze extract-trajectory` should include ions

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#559]
We should probably retain the counterions when `--nosolvent` is used.
We can provide a separate `--noions` argument to drop the counterions.

**Comment by andrrizzi** [comment]
Just bumping up this thread since we're discussing the final changes to the storage format. We should probably add ions to the solute-only trajectory if we want to implement this.

**Comment by Lnaden** [comment]
Thanks, I'll self assign and take care of this

**Comment by andrrizzi** [comment]
Actually, if you don't plan to do it today or tomorrow, do you mind if I take care of this myself? I need this ASAP to run the SAMPL reference calculations.

**Comment by Lnaden** [comment]
Eh, i can just knock it out now. just a sec

**Comment by andrrizzi** [comment]
No rush! I won't need this before tomorrow night.
