### ISSUE TITLE
Add --periodicbox option to yank analyze extract-trajectory

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#562]
When enabled we apply periodic boundary conditions to the trajectory positions. From the first tests I'm running, this considerably slows down the extraction, so we may want to make it optional instead of default behavior.

**Comment by jchodera** [comment]
I think we want to add the box vectors to periodic systems by default, but have an `--image-molecules` option that tries to center the macromolecule in the box if desired. Or is that what you meant

**Comment by andrrizzi** [comment]
Yes, sorry, that's what I meant.

**Comment by andrrizzi** [comment]
Fixed in #566 .
