### ISSUE TITLE
Changing to MIT license

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#563]
We are looking to change the YANK license from LGPL v3 to MIT. We need approval from all contributors Because this code has been contributed to from multiple sources, explicit approval from all code contributors.

Please reply with either +1 or explicit approval if this is acceptable.
Please post your objections otherwise.

No reply by the end of Nov 18, 2016 will be considered approval.

You have been added to this list as you have contributed code to YANK at some point in the past. 
@andrrizzi 
@lnaden (this is my +1)
@jchodera 
@kyleabeauchamp 
@bas-rustenburg 
@pgrinaway 
@steven-albanese 
@mrshirts
@ihaque
@kim-branson

**Comment by andrrizzi** [comment]
I grant my permission.

**Comment by kim-branson** [comment]
+1

**Comment by kyleabeauchamp** [comment]
+1

**Comment by pgrinaway** [comment]
+1
