### ISSUE TITLE
Restraint are set to use periodic conditions whether the system is periodic or not

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#567]
[Here](https://github.com/choderalab/yank/blob/master/Yank/restraints.py#L369) and [here](https://github.com/choderalab/yank/blob/master/Yank/restraints.py#L935).

Is this a problem for implicit solvent simulations? Do the periodic conditions simply get ignored in this case?

**Comment by Lnaden** [comment]
Hmm... good question, I'm not sure to be honest. From what I can see [of the code](https://github.com/pandegroup/openmm/blob/f7935fef719ed0cd8292afef676c39d881b6a960/platforms/reference/src/SimTKReference/ReferenceForce.cpp#L80-L109), it tries to compute the periodic distance between the boxes independent of if there are periodic boundary conditions, which could be an issue. Or I am reading the code wrong

That should not be too hard to fix if the PBC of the `System` is set prior to calling any restraints.

**Comment by andrrizzi** [comment]
> That should not be too hard to fix if the PBC of the System is set prior to calling any restraints.

Ok! It should be set before calling it. I can easily add this as part of PR #565 .

**Comment by andrrizzi** [comment]
Fixed as part of #565 .
