### ISSUE TITLE
Ensure that resuming a simulation does not change restraints

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#589]
We just noted that resuming a simulation may change which atoms are restrained, invalidating the precomputed standard state correction and shifting the sampled distribution.

**Comment by Lnaden** [comment]
It should be noted that this is just a possibility, but something to double check to be sure

**Comment by Lnaden** [comment]
Can confirm, not a bug. The restraint tests use an identical phase for phase1 and phase2, so there are 2 restraints that are created, but they are cached, stored, and correctly reloaded on resume correctly.

**Comment by jchodera** [comment]
Weird! Are both standard state corrections stored in the NetCDF? If so, are we sure the right one is being loaded and compared to the free energy for that leg?

**Comment by Lnaden** [comment]
Each phase has its own file, with its own standard state, no overwriting is occurring (checked that too),
