### ISSUE TITLE
What's the current method for extending a simulation?

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#591]
Incrementing `number_of_iterations:` in the YAML file and re-running doesn't seem to actually increase the number of iterations. Since this is a fairly common operation, we should facilitate and document this.

**Comment by andrrizzi** [comment]
I just tested this with the implicit phenol example, and it works fine for me.

**Comment by jchodera** [comment]
Weird! Thanks for testing. Will reopen if I can't get this to work.
