### ISSUE TITLE
Add support for gaff2

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#610]
see http://archive.ambermd.org/201605/0281.html

**Comment by jchodera** [comment]
@andrrizzi : Do we have a way to select whether the default antechamber pipeline uses gaff or gaff2? This might just be an issue of adding how to select between these (and our recommended best practice) to the documentation.

**Comment by andrrizzi** [comment]
We still have to make the pipeline changing the [`gaff_version` argument of `run_antechamber()`](https://github.com/choderalab/openmoltools/blob/master/openmoltools/amber.py#L287) to support this. We should already be able to specify `leaprc.gaff2` in the leap parameters section.
