### ISSUE TITLE
Problems with Yank docs relating to parallel jobs

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#611]
The link to running in MPI mode on this page is broken: http://getyank.org/latest/quickstart.html

**Comment by davidlmobley** [comment]
Also, the link to `build-mpirun-configfile` from this page is broken: http://getyank.org/latest/running.html#id3

I'm not conda installing since I need the latest `solvent_dsl` stuff Andrea added; though now that I think of it I'll try `yank-dev` as presumably that has the latest.

**Comment by davidlmobley** [comment]
Nope, I just tried conda installing yank-dev and this seems to be incorrect:

> build-mpirun-configfile is automatically installed with YANK when you use the conda installation route.

I'll go hunting for it.

( @Lnaden - I know you're very interested in issues with the docs; there seem to be a couple here. I'm trying to sort out how to get Yank to recognize multiple GPUs per node on my cluster under the SLURM queueing system; I've got Exxact nodes with 8x Nividia Titan II's and so far can only get it to see one at a time; I'm trying to sort out the MPI issues necessary.)

**Comment by davidlmobley** [comment]
Well, I found the file, which has been moved to https://github.com/choderalab/clusterutils/blob/master/clusterutils/build_mpirun_configfile.py rather than the https://github.com/choderalab/clusterutils/blob/master/scripts/build-mpirun-configfile.py mentioned in the docs. However, superficially, it doesn't look useful to me as it seems to be PBS-specific and I'm on SLURM (on one cluster) and Torque (on the other) and this appears to raise an exception if it's not PBS... 

Any advice?

**Comment by davidlmobley** [comment]
Also, I would note that the [http://getyank.org/latest/running.html#running-in-mpi-mode](documentation) lists the command for running Yank in MPI mode as identical to the command for running it in serial mode, which is probably not the case.

**Comment by jchodera** [comment]
You want to conda install yank, not yank-dev. That should automatically install the cluster utilities.

In fact, you probably want to install yank-examples to bring in the examples, yank, and all dependencies. This contains example batch scripts for Torque.

We don't have a slurm cluster to test on, but if you can give us access to one, we can add slurm batch queue script examples as well.

**Comment by davidlmobley** [comment]
I can get you access to our slurm cluster; I'll have to create a collaborator account at UCI for you guys. Who would be the best person, you, @Lnaden , or @andrrizzi , @jchodera ?

**Comment by davidlmobley** [comment]
I can also see about the Torque cluster if you're interested in that as well. It's at SDSC.

**Comment by Lnaden** [comment]
@davidlmobley I made a PR to fix the broken links. Does the documentation at http://getyank.org/latest/running.html#mpi-mode help for getting YANK to see multiple GPUs on the SLURM queue? If not, getting access to the SLURM cluster would be very helpful for making a more general solution.

**Comment by jchodera** [comment]
Won't the hydra `mpirun` figure this out automatically if you just use `mpirun -rmk slurm`?

**Comment by jchodera** [comment]
Actually, [according to this](https://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager#Resource_Managers_and_Launchers), it will automatically autodetect `slurm` so you don't even need `-rmk slurm`.

**Comment by davidlmobley** [comment]
It will be a few days before I can try this out, but @nividic might find it helpful. Thanks!

**Comment by Lnaden** [comment]
Closing this for now, we can open it if things are unclear or don't work right
