### ISSUE TITLE
New error when attempting to run from GROMACS files

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#623]
I'm trying to run a solute-in-cyclohexane solvation free energy calculation (e.g. as in #613 ) from GROMACS input and am running into a new issue (on valid GROMACS input which runs in GROMACS); specifically, on `createSystem` I get an error relating to one of the torsional parameters for the solvated system:

```
    periodic.addTorsion(baseAtomIndex+atoms[0], baseAtomIndex+atoms[1], baseAtomIndex+atoms[2], baseAtomIndex+atoms[3], int(params[7]), float(params[5])*degToRad, k)
ValueError: invalid literal for int() with base 10: '2.00000000e+00'
```

Inputs attached. This is with the latest version I just checked out from GitHub.

I'm guessing it might be something specific to handling of the larger solute in this system, as @jchodera mentioned earlier my methane-ethanol example in #613 was working properly (though yielding large energies). I'm going to look at that next.

[dl.tar.gz](https://github.com/choderalab/yank/files/705548/dl.tar.gz)

**Comment by davidlmobley** [comment]
Ah, I'm thinking that it's that the GROMACS topology files here use a format like this for some of the torsions:
```
      1       2       3       4     1    1.80000080e+02    1.51670000e+01    2.00000000e+00
```
and it seems to be failing to convert `2.00000000e+00` to the integer `2`. The topology file I had for ethane/methanol previously does not use this format and only has things like:
```
      3      2      1      6     1  180.00008  0.83680  1
      3      2      1      6     1  180.00008  1.04600  2
```

I'm not actually sure why this particular topology file uses scientific notation (I'd have to dig back into its history) but it IS a valid GROMACS topology file which runs in GROMACS, suggesting a fix is needed here.

**Comment by jchodera** [comment]
I think @mrshirts mentioned this was a bug in parmed too. Can you suggest a PR to the gromacs reader in OpenMM to fix?

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/gromacstopfile.py

**Comment by davidlmobley** [comment]
See https://github.com/pandegroup/openmm/pull/1721, @jchodera .

**Comment by jchodera** [comment]
That should fix it! Let us know if it didn't.

**Comment by jchodera** [comment]
We think this is resolved. Please reopen if not.
