### ISSUE TITLE
Online analysis for iteration estimation

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#624]
Is running `online_analysis` the only way to get a feel for how many iterations are needed to get a reasonably accurate estimate for free energy of binding? I've noticed that the `number_of_iterations` value has switched from 1000 to 500 in recent builds (for example calculations), so I am just curious if there is any kind of _a priori_  guidelines for setting this value for a diverse set of ligands.

**Comment by jchodera** [comment]
We don't yet have a good idea of the number of iterations required to get reasonable statistical errors yet, but it will probably be *much* larger than 500 iterations. With implicit solvent, we've found that tens of ns/replica were necessary to reach good convergence for small ligands; much longer simulations are likely required for explicit solvent.

We've switched to a smaller default, but have added [options to extend the number of iterations](http://getyank.org/latest/yamlpages/options.html#number-of-extension-iterations) in chunks.

We're still planning to add more features to allow the simulation to automatically analyze the data periodically and terminate when a prespecified statistical error threshold is reached, but it's not yet clear when we'll get this feature in.

I don't think `online_analysis` actually works at this point yet, either.
