### ISSUE TITLE
YANK with two "ligands"

### ISSUE THREAD

**Issue by daveminh** [choderalab/yank#627]
We've had issues running YANK with two small molecules in the system, even if only one is designated as the "ligand". However, we are not 100% sure whether this is due to having two small molecules. This is something worth looking into.

**Comment by jchodera** [comment]
Can you share your input files?

**Comment by bingxie4** [comment]
Attached here are the compressed input files and the error report [setup.zip](https://github.com/choderalab/yank/files/717675/setup.zip)
[run.txt](https://github.com/choderalab/yank/files/717705/run.txt)

The yank command I used is: 
echo "Cleaning up previous simulation..."
yank cleanup --store=output

echo "Setting up binding free energy calculation..."
yank prepare binding amber --setupdir=setup --ligand="resname UNN" --store=output --iterations=5000 --restraints=FlatBottom --gbsa=OBC2 --initialize_with_multi_comple
x_poses --verbose

echo "Running simulation..."
yank run --store=output --verbose --iterations=5000 --use_HMC

Thanks!

**Comment by Lnaden** [comment]
What version of YANK are you using? We stopped supporting (and recently removed entirely) the `prepare` and `run` commands in favor the doing simulations by YAML files through `yank script`. 

Apologies for the confusion, we should have scrubbed the docs of that information some time ago unless you got it from the command line doc string. Did you find the info for those commands somewhere?

**Comment by bingxie4** [comment]
We downloaded the development version '0.15.0dev0.dev-24dc0f' YANK from the GitHub about one month ago. At that time there were prepare and run commands in it, so that I ran the yank in that way. Yes, I found the info for the commands and prepare to run the latest YANK with YAML files.

**Comment by jchodera** [comment]
We've deprecated the CLI some time ago, so can no longer support command-like use.
If you still have trouble with the YAML input and recent versions of YANK, please open a new issue!
