### ISSUE TITLE
output of exchange rate between nearest neighbour states

### ISSUE THREAD

**Issue by nguyentrunghai** [choderalab/yank#630]
Gaps in exchange rates can severely affect calculation convergence. It would be nice to diagnose the problem and make it known to the user, or at least output the exchange rates between nearest neighbour states. 
We used the function bellow to output the exchange rates after the simulation is done.

`
import numpy as np
import netCDF4 as nc
import mdtraj as md

def _nearest_pair_ex_counts(nij):
    nstates = nij.shape[0]
    counts = np.zeros([nstates - 1], dtype=float)
    for i in range(nstates - 1):
        counts[i] = nij[i, i+1]
    return counts

def exchange_rate(yank_nc_file):
    """
    """
    nc_handle = nc.Dataset(yank_nc_file, "r")
    proposed = nc_handle.variables["proposed"]
    accepted = nc_handle.variables["accepted"]

    niterations = proposed.shape[0]
    nstates = proposed.shape[1]

    proposed_counts = np.zeros([nstates - 1], dtype=float)
    accepted_counts = np.zeros([nstates - 1], dtype=float)

    for i in range(niterations):
        proposed_counts += _nearest_pair_ex_counts( proposed[i,:,:] )
        accepted_counts += _nearest_pair_ex_counts( accepted[i,:,:] )

    nc_handle.close()
    return accepted_counts / proposed_counts
`

**Comment by Lnaden** [comment]
We actually have those functions built in already which should show both at runtime, and in the analyze script.

If you have `show_mixing_statistics` set in [the YAML file](http://getyank.org/latest/yamlpages/options.html#yaml-options-show-mixing-statistics) it should show you the matrix of swaps between states during the run.

You can also re-generate this matrix in the `analyze` part of YANK. You can either run the whole analysis from the command line, or you can `from yank import analyze` and use the `analyze.show_mixing_statistics` [function directly on the NetCDF file](https://github.com/choderalab/yank/blob/master/Yank/analyze.py#L46) to get the same result.

The matrix itself shows how many swaps were made from any one state to another based on state index.

**Comment by jchodera** [comment]
We have added two approaches to help the user here:
* Notebook output during analysis helps identify poor mixing; see also [this video](http://getyank.org/0.17.0/yamlpages/protocols.html#protocols-how-to-video)
* The [`auto` option](http://getyank.org/0.17.0/yamlpages/protocols.html#yaml-protocols-auto) for alchemical path generation should fix this for most systems

Please reopen if this issue is still a problem.
