### ISSUE TITLE
Phenol hydration energy in YANK example

### ISSUE THREAD

**Issue by j3mdamas** [choderalab/yank#631]
Did you assess the energies obtained against experimental data? From the yank calculation, I've got:

```
2017-01-27 21:24:00,840: Free energy of solvation:           -9.077 +- 0.199 kT (          -5.411 +- 0.119 kcal/mol)
2017-01-27 21:24:00,840:
2017-01-27 21:24:00,840: DeltaG solvent1                  :           35.364 +- 0.199 kT
2017-01-27 21:24:00,840: DeltaG solvent2                  :           26.288 +- 0.000 kT
2017-01-27 21:24:00,840:
2017-01-27 21:24:00,840: Enthalpy of solvation:           94.125 +- 61.465 kT (          56.114 +- 36.643 kcal/mol)
```

So, an hydration energy of -5.411 kcal/mol.

I saw [this paper](http://pubs.rsc.org/en/Content/ArticleLanding/1971/J2/J29710000533#!divAbstract), and they derive the free energy of hydration from water solubility, leading to a value of -0.05 kcal/mol. Using the solubility in https://pubchem.ncbi.nlm.nih.gov/compound/phenol, I've got a value of 0.07 kcal/mol. Any of these values are very different from what I got with YANK. Force-field to blame?

**Comment by andrrizzi** [comment]
Hi! I don't think we have verified the hydration free energy of phenol yet. Is that the explicit or implicit solvent calculation?

**Comment by j3mdamas** [comment]
Explicit. That was the script I used.

**Comment by andrrizzi** [comment]
Ok, I'll try to test the example this week and get back to you. Thanks for reporting!

**Comment by Lnaden** [comment]
The paper you linked looked at substituted phenols, not phenol itself in any detail. In fact, the only thing I can pick out is in that paper's Figure 1 where they look at Hydration free energy as a function of Hammett sigma-parameter. If I am reading the chart right, the `H` entry may be phenol where the 4-site is substituted by an `H` and that has a hydration free energy around -4.8 or -4.9 kcal/mol. I'm not sure where you are getting the -0.05 kcal/mol?

If we also look at David Mobley's [FreeSolv](https://www.ncbi.nlm.nih.gov/pubmed/24928188) database, [here](http://escholarship.org/uc/item/6sd403pz), they calculate that phenol has a hydration free energy of -4.60 +- 0.10. So the calculations you show are on the correct order. The two force fields should be the same (GAFF based with AM1-BCC charges), so the difference makes me question what might be going on. If I had to guess, it would either be an undersampling problem, or it might be that the example is running in NPT ensemble, and the FreeSolv number is run in NVT (although equilibrated to 1atm box), so we are comparing Gibbs to Helmholtz free energies here.

@andrrizzi He is using the phenol examples from [yank-examples](https://github.com/choderalab/yank-examples/blob/master/examples/hydration/phenol/explicit.yaml)

**Comment by j3mdamas** [comment]
I edited the paper, I linked the wrong one. This is the one I was looking at: http://pubs.rsc.org/en/Content/ArticleLanding/1971/J2/J29710000533#!divAbstract (table 3)

Anyway, thanks for the reference of the FreeSolv database. Maybe deriving the free energies from solubility is not accurate? I would have to check that and see where the experimental values are coming from. Of course, comparing with other computed values is the way to go.

I also need to check the code and see what YANK is doing because I was using it out-of-the-box. Do you have some code to assess convergence?

**Comment by Lnaden** [comment]
Ah. I think I see what went wrong there. Table 3 of that paper is solubility of the solid phase of the  of the phenols, they used that to derive the hydration of phenols in table 6, which for phenol they compute as -4.72 kcal/mol.

We don't actually have convergence code directly in YANK or MBAR right now, it is one limitation we acknowledge and have plans to include as YANK evolves. We will be drawing from [this page](http://nbviewer.jupyter.org/github/choderalab/simulation-health-reports/blob/master/examples/yank/YANK%20analysis%20example.ipynb) and its citations int he future as we move to a more general MCMC framework.

**Comment by j3mdamas** [comment]
sorry @Lnaden, that was really sloppy of me. I was trying to check this quick and I got it wrong. Thanks for your help.

**Comment by Lnaden** [comment]
Not a problem! YANK still has a number of issues that we are working on like the convergence checks, so its always worth checking when numbers don't line up
