### ISSUE TITLE
Cut new release for openmm >=7.1.0 and alchemy >=1.2.3

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#636]
Our [yank conda recipe](https://github.com/omnia-md/conda-recipes/blob/master/yank/meta.yaml) currently pins [`openmm >=7.0.1`](https://github.com/omnia-md/conda-recipes/blob/master/yank/meta.yaml#L22) and [does not pin `alchemy`](https://github.com/omnia-md/conda-recipes/blob/master/yank/meta.yaml#L30). We need to update this for
* `openmm >=7.1.0` (no more NaNs)
* `alchemy >=1.2.3` (bugfix release)

Make sure to update both the `build:` and `run:` sections!

**Comment by jchodera** [comment]
cc: #635, where the NaNs may or may not be caused by this.

**Comment by andrrizzi** [comment]
As a reminder for the next release, `alchemy` is not not a requirement anymore, but we need to pin `openmmtools >=0.9.1`.

**Comment by Lnaden** [comment]
This has been fixed with the release of 0.16.0 in  #687
