### ISSUE TITLE
Add unit tests to SystemBuilder

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#64]
All modules should have unit tests for classes and methods.

**Comment by bas-rustenburg** [comment]
I noticed that there is a "test" at the bottom of [`systembuilder.py`](https://github.com/choderalab/yank/blob/de1f0676ff0dadc1d1b0da1dff23dbfa43776fc4/Yank/systembuilder.py#L1085-L1139)

Should this be translated to a test, or perhaps an example?

**Comment by jchodera** [comment]
This looks like it belongs in the test_alchemy.py nosetest, though I think I might already have a similar test there.

**Comment by bas-rustenburg** [comment]
It could maybe serve as an integration test for `systembuilder`.

I can't get that particular test to run right now because of some relative imports not working when running it as `main`. Maybe @pgrinaway will have some thoughts on it (after the weekend), I think he wrote that part originally.

**Comment by Lnaden** [comment]
Depreciating for new SystemBuilder post 1.0
