### ISSUE TITLE
lambda_restraints parameter not documented in YAML syntax

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#640]
The YAML syntax detailed documentation does not mention `lambda_restraints:`:

http://getyank.org/0.15.0/yamlpages/protocols.html#yaml-protocols-example

**Comment by andrrizzi** [comment]
This is documented here: http://getyank.org/0.15.0/yamlpages/protocols.html#alchemical-path-lambda-electrostatics-lambda-sterics-and-lambda-restraints
