### ISSUE TITLE
Adding IUPAC and Chemdraw support to systembuilder

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/yank#66]
I have written two system builder classes that can handle IUPAC names and ChemDraw files as input. I'm planning to use these with the host-guest systems. It uses the OpenEye libraries but only checks for them when these particular classes are instantiated. 

I also added an option to overrule the default antechamber net charge, which it sums up from the input file if not specified with the nc flag. This is necessary when the input file generated by OpenEye does not have any charges. I'm sure there will be other cases where this comes in handy.

I don't want to cause any incompatibilities, so I will merge changes into my branch when #62 is completed before submitting a pull request. 

Current state in https://github.com/bas-rustenburg/yank/tree/new-driver.

**Comment by Lnaden** [comment]
Depreciating for new SystemBuilder post 1.0
