### ISSUE TITLE
Rename YamlBuilder module and classes

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#665]
We discussed renaming our application classes to untying them to be specific to YAML.

**How should we call the application module (currently `yamlbuild`)?** I'd like to keep it short if possible. Possible names: `builder` (maybe too generic?), `expbuilder`, `experiment`, `experimentbuilder`, `app`, others?

Also, these are the renaming changes I'd like to do shortly.
- move `systembuilder.py` to `archive/systembuilder.py`
- rename `YamlBuilder` to `ExperimentBuilder`
- move `yamlbuild.SetupDatabase` to `pipeline.SetupDatabase` (this is the class that actually implements the setup pipeline).

Let me know if you have other suggestions.

**Comment by jchodera** [comment]
I think we should fully remove `systembuilder.py` at this point. We can always resurrect it from the git history later, but it will probably become part of the new setup workflow outside of this repo.

**Comment by andrrizzi** [comment]
Ok! I'll rename `yamlbuild` to `expbuilder` in the next couple of days if there aren't particular objections or better alternatives.
