### ISSUE TITLE
some state potential energy blows up

### ISSUE THREAD

**Issue by bingxie4** [choderalab/yank#676]
After running several iterations, we found that some of the states potential energies went up to very high values. I tried YANK simulations with Langevin integrator and simulations with Hamiltonian Monte Carlo method (verlet integrator). Both of them have the state energy increasing dramatically problem. Is there probably an energy postprocessing issue? 

Attached here are the T4 lysozyme simulations states energy graphes (for easier looking, the graph energy cutoff is 0, above this value won’t show).  The first two graphes (Langevin and HMC) protocols setup like this:
lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
lambda_sterics: [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]

The last one graph (Langevin) protocol setup:
lambda_electrostatics: [1.0, 0.974, 0.949, 0.923, 0.897, 0.872, 0.846, 0.821, 0.795, 0.769, 0.744, 0.718, 0.692, 0.667, 0.641, 0.615, 0.59, 0.564, 0.538, 0.513, 0.487, 0.462, 0.436, 0.41, 0.385, 0.359, 0.333, 0.308, 0.282, 0.256, 0.231, 0.205, 0.179, 0.154, 0.128, 0.103, 0.077, 0.051, 0.026, 0.0]
lambda_sterics: [1.0, 0.974, 0.949, 0.923, 0.897, 0.872, 0.846, 0.821, 0.795, 0.769, 0.744, 0.718, 0.692, 0.667, 0.641, 0.615, 0.59, 0.564, 0.538, 0.513, 0.487, 0.462, 0.436, 0.41, 0.385, 0.359, 0.333, 0.308, 0.282, 0.256, 0.231, 0.205, 0.179, 0.154, 0.128, 0.103, 0.077, 0.051, 0.026, 0.0]

It seems that the last protocol has less high energies showing up, but the problem is still there.
![t4_langevin](https://cloud.githubusercontent.com/assets/8743225/25813150/25791592-33de-11e7-95a2-bfbf658e5052.png)
![t4_hmc](https://cloud.githubusercontent.com/assets/8743225/25813155/2826a75a-33de-11e7-9e9b-1ca7af4ccd15.png)
![t4_langevin_lambda_ simultaneously](https://cloud.githubusercontent.com/assets/8743225/25813162/2c21c40c-33de-11e7-8e4b-dfa90ac84805.png)

**Comment by jchodera** [comment]
Thanks for posting this!

Are these the energies of one configuration evaluated at a *different* thermodynamic state? If so, these high potential energies are totally expected---when the ligand is mostly annihilated, the potential energy in a fully-interacting state will be very large. This is totally OK for analysis with MBAR.

If, however, these are the potential energies of a configuration evaluated at its *current* thermodynamic state, this is a serious problem. If that's the case, we'll want to figure out how to get either your input files or some of your NetCDF files to examine in more detail.

**Comment by bingxie4** [comment]
These energies are from their current thermodynamic states. It seems that after replica exchanging, if a configuration gets a very high energy at the begining state, it would get a very high energy in its current state too, except when there is a weak interaction in current state.
Attached here are the input files.
[T4-indole.zip](https://github.com/choderalab/yank/files/984448/T4-indole.zip)

**Comment by jchodera** [comment]
That's odd. 

@andrrizzi : Could you take a look into this, since this would affect our validation as well?

**Comment by andrrizzi** [comment]
Sure! I can take a look.

@bingxie4 can you also post/link the script you are using to check the energies and the version of YANK you are using?

**Comment by bingxie4** [comment]
Yes, the YANK version is 
short_version = '0.15.2'
version = '0.15.2.dev0'
full_version = '0.15.2.dev0'

Attached here is the script for checking state energies: (.py isn't supported, converted to .txt format)
[state_energies.txt](https://github.com/choderalab/yank/files/986903/state_energies.txt)

**Comment by Lnaden** [comment]
Thanks for providing the script you used to make those charts! I think I found your problem: you need to de-convolute the replica from the state space

Energies are stored in dimensions of `[iteration, replica, state]`, the states are then swapped between replicas, so although the replica index wont change, the state it is sampling will (for the second index). So to get the energies in terms of `[iteration, state, state]`, you should change your script to add something like this:

```python
directory = 'output/experiments'

import netCDF4 as nc
import matplotlib.pyplot as plt
ncfile = nc.Dataset(directory+'/complex.nc')
energies = ncfile.variables['energies']
niterations  =energies.shape[0]
nstates = energies.shape[1]

#-----------
# Deconvolute code here (I'm adapting from our analyze.py file)
import numpy as np
deconvolute_energies = np.zeros([niterations, nstates, nstates], np.float64)
for iiteration in range(niterations):
    state_indices = ncfile.variables['states'][iteration,:]
    deconvolute_energies[iteration, state_indices, :] = energies[iteration, :, :]
energies = deconvolute_energies
#-----------

colors = plt.get_cmap('rainbow')(np.linspace(0, 1.0, nstates))
plt.clf()

for i in range(nstates):
  en = energies[1:,i,i]
  #  print i, en.std()
  en[en>1E3] = 0
  plt.plot(en,label=str(i),color=colors[i])
#plt.show()
plt.ylabel('potential energy')
plt.xlabel('number of iteration')
#plt.legend(bbox_to_anchor=(1, 1),bbox_transform=plt.gcf().transFigure)
plt.savefig(directory.split('/')[0]+'/energy_plot.png')
```

**Comment by bingxie4** [comment]
Right. I see the problem. After de-convoluting the energies, there is no crazy energies any more.

Thanks for the help!
![energy_plot](https://cloud.githubusercontent.com/assets/8743225/25911626/321bb3c0-357a-11e7-9614-9dc7fd1da53b.png)

**Comment by Lnaden** [comment]
Excellent! There are functions in the `analyze` module of YANK which should help you do the deconvolution and other common functions yourself if this is something you are doing often. 

Let us know if you have other issues!
