### ISSUE TITLE
Anisotropic dispersion cutoff: automatic determination(?) and support for non-rectangular box

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#690]
Until #336 is implemented, we have no way to specify through the YAML script a different dispersion cutoff for the complex and solvent phase. This can be problematic when starting from system files prepared by other groups. Should we allow something like
```yaml
options:
  anisotropic_dispersion_cutoff: auto
```
that pushes the cutoff as much as it can based on the initial box_vectors (to a maximum of 16A)?

Also, currently we check that the given cutoff won't cause problems with
```python
box_vectors = system.getDefaultPeriodicBoxVectors()
min_box_dimension = min([max(vector) for vector in box_vectors])
if min_box_dimension < 2.25 * expanded_cutoff_distance:
  raise Exception
```
but I don't think this way of determining `min_box_dimension` works for non-rectangular boxes. I believe we should instead determine the minimum norm of the box vectors.

**Comment by jchodera** [comment]
Both ideas sound great.
