### ISSUE TITLE
Have solvent simulation run before (or in parallel with) complex simulation

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#70]
This will allow us to monitor free energies of binding as the complex simulation is running.

**Comment by jchodera** [comment]
Alternatively, chunks of the solvent phase calculation could be interleaved with the complex calculation in order to allow online analysis to produce useful information.

**Comment by Lnaden** [comment]
Post 1.0 issue

**Comment by andrrizzi** [comment]
> chunks of the solvent phase calculation could be interleaved with the complex calculation 

This was implemented in #662 with the addition of the keyword `switch_phase_every` that became `switch_phase_interval` in #682 .
