### ISSUE TITLE
Fix netcdf string compression

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#702]
Just opening an issue to record my experiments for reference.

With the current way we save strings, the `zlib` compression doesn't work. I was able to make it work by saving strings the old way as a character array.

```python
str_out = netcdf.stringtochar(np.array(python_string, 'S4'))

dimension = len(str_out)
dimension_name = 'string' + str(dimension)
if dimension_name not in self._storage_dict[storage].dimensions:
    self._storage_dict[storage].createDimension(dimension_name, dimension)

nc_variable = self._storage_dict[storage].createVariable(name, 'S1', (dim_name,), zlib=True)

nc_variable[:] = str_out
```
With this code the resulting nc file that contained the serialization of alchemically modified Src got reduced from 52M to 32K!!

I didn't test the restoring so we may have to tweak it a little. Also, with this implementation it may be impossible to update strings since I'm not sure you can change the dimension of a variable after its creation. The point is that maybe netcdf doesn't support the compression of the new variable-length `str` type variables.

Worse case scenario, we could save permanently the expensive bits (thermodynamic states, topology, ...), and save as vlen strings the things that need to be updated (i.e. mcmcmoves statistics).

**Comment by jchodera** [comment]
Whoa!

> The point is that maybe netcdf doesn't support the compression of the new variable-length str type variables.

What about raising an issue in the [`netcdf4-python`](https://github.com/Unidata/netcdf4-python) Github issue tracker?

**Comment by andrrizzi** [comment]
The first snippet I posted was truncating the string, that's why the compression was so extreme (thanks @Lnaden for figure it out). Assuming we add a `compress` argument to `openmmtools.states.ThermodynamicState.__getstate__()` that uses `zlib` to reduce the size of the serialization, this should work for writing
```python
data_dict = openmmtools.utils.serialize(thermodynamic_state, skip_system=True, compress=True)
data_str = yaml.dump(data_dict, Dumper=_DictYamlDumper, default_flow_style=True)
len_data = len(data_str)
data_char_array = np.array(list(data_str), dtype='S1')

dimension_name = 'string' + str(len_data)
if dimension_name not in self._storage_dict[storage].dimensions:
    self._storage_dict[storage].createDimension(dimension_name, len_data)
nc_variable = netcdf_dataset.createVariable('state', 'S1', dimension_name, zlib=True)

nc_variable[:] = data_char_array
```
and for reading
```
data_char_array = nc_variable[:]
data_str = data_char_array.tostring().decode()
data_dict = yaml.load(data_str, Loader=_DictYamlLoader)
thermodynamic_state = openmmtools.utils.deserialize(data_dict)
```
For the alchemically modified `openmmtools.testsystems.SrcExplicit` (the uncompressed serialized string is ~38MB), this takes about 4-5 seconds, and the final dimension of the nc file containing only the state is 1.1MB.

If we implement this, we'd have to add a `compress` argument to `Reporter.write_dict()` so that we'll be able to modify the dictionary for MCMCMoves.

**Comment by Lnaden** [comment]
I like this approach better. I think it would need to take 2 separate changes:

1. OpenMMTools change which brings in the `compress` argument.
2. YANK change to `write_dict` to create char variables of unique dimensions instead of the generic 'scalar'

I think I can get those changes in by the end of today if this looks good to you

**Comment by andrrizzi** [comment]
Sounds great!

**Comment by Lnaden** [comment]
After adding both the OpenMMTools and the YANK fixes, here are some numbers for an explicit solvent setup of FXR, with anisotropic dispersion correction, 0 iterations taken (so initial file size)

|File       | Pre-comp Size | Post-comp. Size | Factor Reduction
|------- |----------------|-----------------|------------------------
|Solvent.nc |    16 MB      |    1.1 MB       |      14.5x   
|Complex.nc |   184 MB      |     16 MB       |      11x

Speed of Serialization step
Pre-comp : 195 s
Post-comp :  49 s
Factor   : ~4x 

I think this makes strong progress towards fixing this. The file sizes are still a bit large, but if acceptable, we can probably close this issue.

**Comment by andrrizzi** [comment]
I bet a good chunk of those 16MB come from the topology serialization, which is still stored uncompressed as part of `metadata`.

**Comment by Lnaden** [comment]
Looks like the `cyaml` changes shave a few seconds (~8-10) off the store of thermodynamic states (relative to table above), but we get about another 30s saved from storing the uncompressed `metadata`, string, so hey, free optimizations!

**Comment by andrrizzi** [comment]
Nice! At this point I hope that the bottleneck for the serialization step is the actual OpenMM `System` serialization rather than the YAML dumping.

**Comment by Lnaden** [comment]
My thoughts exactly.

**Comment by Lnaden** [comment]
I think this issue can be closed for now. If it becomes a problem again or we want to try and find a better compression method, we can reopen this or a new issue.
