### ISSUE TITLE
Problem in result analysis (CUDA versus OpenCL)

### ISSUE THREAD

**Issue by mmagithub** [choderalab/yank#723]
Hi,
I was trying to run YANK on a protein-ligand complex prepared by AMBER. What I have observed is that when I set up the platform to CUDA (faster in the cluster I am working with, NIVIDIA), the analysis ends by giving this error:
###################################
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/analyze.py", line 76, in dispatch
    analyze.analyze_directory(args['--store'])
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/analyze.py", line 1151, in analyze_directory
    phase = get_analyzer(phase_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/analyze.py", line 74, in get_analyzer
    reporter = Reporter(file_base_path, open_mode='r')
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/repex.py", line 116, in __init__
    self.open(open_mode)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/repex.py", line 221, in open
    primary_ncfiles['analysis'] = netcdf.Dataset(self._storage_file_analysis, mode, version='NETCDF4')
  File "netCDF4/_netCDF4.pyx", line 1873, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13852)
  File "netCDF4/_netCDF4.pyx", line 1579, in netCDF4._netCDF4._ensure_nc_success (netCDF4/_netCDF4.c:12638)
IOError: No such file or directory
###################################

However, when I use OpenCL, the analysis runs without a problem and prints the final results. I have checked what is different in the output and I found that the solvent.nc and solvent_checkpoint.nc are not generated when using the CUDA platform, I am not sure if this is the reason for this problem.
OpenCL looks significantly slower in running the simulation on my cluster, so, I will need to use CUDA for sure.
I am not sure if YANK should be specifically used with a specific version of CUDA, and I am using the most recent version (cuda8).
Any clue?
Also, what is the format of the nc trajectories generated by YANK, are these files normal netcdf trajectories that can be loaded with VMD 

Regards,
Marawan

**Comment by Lnaden** [comment]
The platform should not have any impact on the storage file creation and strikes me as very, very odd behavior. Is this repeatable on your cluster? Can you zip your log files and post them here?

All the YANK code is pure python and should not use CUDA/OpenCL at all, only the OpenMM parts use the GPU code. The only thing I can think of off the top of my head is that whatever node your cluster has its CUDA devices on does not have access to the file space where you set your output directories, but even that seems like a stretch if the simulations actually ran.

**Comment by andrrizzi** [comment]
It sounds like your simulation crashed before calculating the solvent phase. Can you take a look at the log in `output/experiments/` folder?

> what is the format of the nc trajectories generated by YANK, are these files normal netcdf trajectories that can be loaded with VMD?

You can use the command
```
yank analyze extract-trajectory --netcdf=output/experiments/complex.nc --state=0 --trajectory=output_traj.pdb --imagemol --nosolvent
```
The last flag removes water molecules to reduce the size of the pdb file.

**Comment by mmagithub** [comment]
It seems that you are right Andrea. When I run shorter runs (10 iterations), I can see that both CUDA and OpenCL could produce the solvent.nc and solven_checkpoint.nc files. This suggests that the longer runs that had problems in CUDA might have crashed indeed.
Unfortunately, I have accidentally deleted those files and I need to run them again. Once this finish and the same problem persist, I will send you the log files to have a look.
Please keep this thread open, I will let you know what happens once I got the data.

Thanks

**Comment by jchodera** [comment]
Closing this, presuming that the problem did not persist. If it is still a problem, please reopen!
