### ISSUE TITLE
Run combinatorial experiments in parallel

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#725]
Since the YANK 1.0 paper will involve running a lot of molecules, I'm also thinking of adding a way to run multiple experiments on single nodes. This way we won't have tens of nodes in idle while we write on the disk and/or perform the online analysis.

With the new feature in the MPI library (PR coming) it will be very easy to implement both of these:
- add a YAML option `options:nodes_per_experiment:2` that allows to spawn a job on multiple MPI processes and allocate (in this case) 2 nodes per experiments by splitting the mpicomm.
- add two options to the `yank script` command `--job_id=2` and `--n_jobs=10` that (in this case) will run only one tenth of the experiments on whatever number of processes.

Personally, I would implement them both (it would take me only an hour at this point). The second one could be very helpful for having parallelization even on systems that with no MPI, or simply in times where the cluster is busy and it's not possible to gather a lot of gpus at the same time.

What do you think?

**Comment by jchodera** [comment]
My feeling is that splitting the MPI communicator would be easiest, but I wonder if you've already isolated things sufficiently well that we could add a celery backend that uses your MPI interface that would permit adding more workers dynamically...

**Comment by jchodera** [comment]
Note also that we can probably double or triple up on how many experiments are running on each GPU for small systems and get a decent speedup if they are not using the full capacity of the GPU, so this might be a good opportunity to allow that. It could help for hydration free energies, implicit solvent free energy calculations, and maybe even host guest explicit solvent binding free energies.

**Comment by andrrizzi** [comment]
> My feeling is that splitting the MPI communicator would be easiest

I think I can actually add them both in less than an hour, so it's more of a question of whether we want also the second or not. I found it very useful on the cluster at times, but I've always had to write an external script on top of `ExperimentBuilder` to do it so far.

>  I wonder if you've already isolated things sufficiently well that we could add a celery backend that uses your MPI interface that would permit adding more workers dynamically

I'm not 100% sure, but we're definitely close, maybe some tweakings are still needed. It would still take a couple of weeks to make everything work though, so I'd push it for post-1.0. When we do it, we could extend `nodes_per_experiment` to accept `auto` to allow for a dynamic allocation?

**Comment by jchodera** [comment]
> I think I can actually add them both in less than an hour, so it's more of a question of whether we want also the second or not. I found it very useful on the cluster at times, but I've always had to write an external script on top of ExperimentBuilder to do it so far.

If it would be useful, go for it, as long as it would be optional!

**Comment by andrrizzi** [comment]
Ok, thanks!
