### ISSUE TITLE
Is PDB resSeq output busted in analyze?

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#73]
It looks like analyze outputs resSeq to column 27 in PDB files.  This causes errors in the MDTraj and OpenMM PDB parsers.  

The wwPDB is pretty ambiguous about what's correct here.  They _say_ that the resSeq should belong in columns 23-26 (http://www.wwpdb.org/documentation/format32/sect9.html).  However, on the very same page shows examples with the resSeq offset into column 27, so it's not clear what's correct.

**Comment by Lnaden** [comment]
Is this still an issue?

1.0 touch

**Comment by andrrizzi** [comment]
I think we are using mdtraj to write pdbs now. Closing. Reopen if I'm wrong.
