### ISSUE TITLE
Add CHARMM input scheme

### ISSUE THREAD

**Issue by leelasd** [choderalab/yank#760]
Hi,

 I have been using Parmed/OpenMM to implement OPLS-AA FF based simulations. Is there anyway to use these systems for performing hydration free energy/binding free energy calculations. Any suggestions are appreciated.

**Comment by davidlmobley** [comment]
You would need to be more specific about what you want to know. There certainly is a way to do this, yes.

**Comment by jchodera** [comment]
@leelasd : Can you provide more information about what you're hoping to do here? Are you already able to set up systems with these forcefields in some other program, like gromacs?

**Comment by leelasd** [comment]
@jchodera @davidlmobley Sorry for the late reply.

I am trying to calculate binding free energy for Lysozyme-Benzene system. I am using PSF and PRM files (generated with VMD) to perform MD with Parmed/OpenMM. 
I attached the PSF, PDB and Parameter files used to do MD. 
[OMM_MD.zip](https://github.com/choderalab/yank/files/1275419/OMM_MD.zip)

I want to know if I can use the same Parmed/OpenMM with Yank to do binding FEP calculation. 
Any suggestions would be great.

**Comment by jchodera** [comment]
We don't currently have a CHARMM reader, but it should be easy to add one so you can use these files! I'll change of the title of the issue to reflect this.

**Comment by leelasd** [comment]
@jchodera can you point me to the module where you create Yank/OpenMM system from Gromacs file. I can contribute that part

**Comment by jchodera** [comment]
Contributions would be welcomed!

I believe you would need to do the following:
* Add a section to [this function](https://github.com/choderalab/yank/blob/master/Yank/experiment.py#L1285-L1294) to make YANK aware of CHARMM system files
* Add a schema to let the user specify a sufficient combination of `pdb`, `psf`, and `prm` files [here](https://github.com/choderalab/yank/blob/master/Yank/experiment.py#L1332-L1353)
* Add a section to [this function](https://github.com/choderalab/yank/blob/master/Yank/pipeline.py#L381-L478) to handle loading of [CHARMM files using OpenMM](http://docs.openmm.org/latest/userguide/application.html#using-charmm-files)

@andrrizzi can help review your work if you run into trouble!

**Comment by leelasd** [comment]
Thanks !! I will start working on that !!

**Comment by davidlmobley** [comment]
Of course, the other approach is to see this as a ParmEd issue and not a Yank issue and just convert your files to a format Yank DOES support using ParmEd.

**Comment by jchodera** [comment]
Whichever you like! But OpenMM definitely supports reading CHARMM files and the total effort here is <50 lines to save having to ever convert from CHARMM again, so it may be worth it.

**Comment by andrrizzi** [comment]
> I believe you would need to do the following:

That should work! Let me know if I can help.

**Comment by jeffcomer** [comment]
I tried @davidlmobley's suggestion of using ParmEd to produce Amber-format files from the original CHARMM format, but OpenMM gives an error that says something about not being able to use Chamber prmtop files. I then decided to modify Yank to use CHARMM-format files directly.

**Comment by andrrizzi** [comment]
Implemented in #1207 .
