### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#761]
We need to come to a firm answer on this. If we choose not to support, we don't have to purge all of the 2/3 compatibility code right out, we can do it later, just say 2 is not supported

**Comment by jchodera** [comment]
Let's see what @andrrizzi thinks, but I'd be happy to go Python 3.x only for 1.0 release so we don't have the 2.8 support burden for all YANK 1.x releases.

**Comment by Lnaden** [comment]
I'm personally for this, I raised my concerns for this on markovmodel/PyEMMA#1140, but I think forcing people to stop using Python 2.7 BEFORE it is officially dropped is a good thing.

**Comment by jchodera** [comment]
I think we should drop python 2.7 support. Even if we don't make code changes aside from not building for python 2.7, this prevents us from having to support 2.7 throughout the YANK 1.x lifecycle.

**Comment by andrrizzi** [comment]
No objections here!
