### ISSUE TITLE
Auto-path function does not run in parallel

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#762]
The auto-path function does not run in parallel. It throws an error about incorrect number of states between the alchemical path. Running a single process through either serial or through MPI does not throw the error.

The problem appears to be that the protocol generation procedure is not a blocking action, or its not being distributed correctly. For now users can run a 0 iteration serial to setup the process, then a production run with more iterations.

@andrrizzi I think the line [is here](https://github.com/choderalab/yank/blob/dfc99fb725c489be08e01cd785b1ff54b2395619/Yank/experiment.py#L1798) and I think it needs a `sync_nodes=True` flag. Is that right or do I need to do something else?

**Comment by andrrizzi** [comment]
Sorry! I thought I tested this on multiple nodes. I'll try to fix it ASAP.
