### ISSUE TITLE
Crash with automatic convergence detection

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#771]
When `number_of_iterations` is `null` and a target statistical error is specified, YANK crashes at [this line](https://github.com/choderalab/yank/blob/master/Yank/experiment.py#L398) because it tries to subtract an integer from `None`.

I'll push a fix today.

**Comment by Lnaden** [comment]
Ah, I missed this! Sorry. I have the check [here in repex](https://github.com/choderalab/yank/blob/0f7fc1ee268274f383cedb4783f8d68796bb148e/Yank/repex.py#L1538-L1539), but missed the check in experiment.

**Comment by andrrizzi** [comment]
This was fixed in #773 .
