### ISSUE TITLE
how to set up experiments in yaml when you prepared the system yourself

### ISSUE THREAD

**Issue by luirink** [choderalab/yank#774]
YANK will allow users to specify arbitrary free energy calculations with systems they have prepared themselves. However, if you use it this way, it complains of the "experiments" not containing components (receptor, ligand, solvent). How do you go around this issue?

for example, when this is your systems:
systems:
  cyp-tes:
    phase1_path: [gromacstop/complex.prmtop, gromacstop/complex.inpcrd]
    phase2_path: [gromacstop/solvent.prmtop, gromacstop/solvent.inpcrd]
    ligand_dsl: resname TES
    solvent_dsl: resname WAT
    solvent: pme

and this experiments:
experiments:
  system: cyp-tes
  protocol: absolute-binding
  restraint: flat-bottom

It gives the following error:
    raise YamlParseError('Cannot find components for {}'.format(exp_name))
yank.yamlbuild.YamlParseError: Cannot find components for experiments. Which makes sense, I did not specify them in system. (I followed this protocol: http://getyank.org/0.17.0/yamlpages/systems.html and then Arbitrary Phase Free Energies Setup by User

**Comment by andrrizzi** [comment]
Hi @luirink! Your syntax for the `systems` section should be fine. I believe it's the restraint specification that is throwing YANK off. See [this example](http://getyank.org/0.17.0/yamlpages/experiments.html#experiments-syntax).

**Comment by luirink** [comment]
hi! Changed it to this:
experiments:
  system: cyp-tes
  protocol: absolute-binding
  restraint:
    type: FlatBottom

and I still get the same error..

**Comment by luirink** [comment]
hi! Changed it to this:
experiments:
  system: cyp-tes
  protocol: absolute-binding
  restraint:
    type: FlatBottom

and I still get the same error.. The same happens if I do not use specify the restraint in experiments.

**Comment by jchodera** [comment]
Hi @luirink! Can you zip up your input YAML file and attach it?

**Comment by andrrizzi** [comment]
Ah! I see now that you're not using the latest release. On which version are you (so that I can pin down the YAML syntax you should use)?

**Comment by jchodera** [comment]
What about just upgrading to the latest release?

**Comment by luirink** [comment]
I am using version 0.17.0 . Isn't that the latest stable release?

**Comment by jchodera** [comment]
Yes, that should be the latest version!

**Comment by andrrizzi** [comment]
It is, but your error comes from the module `yank.yamlbuild` which doesn't exist anymore in 0.17.0. I bet you have a conda environment problem. I would try uninstalling yank, then `conda clean -itps --yes`, and installing it again. If you are installing from source, be sure to remove the `build/` folder since that may still contain a `yamlbuild` module.

**Comment by andrrizzi** [comment]
I'll close this issue to keep the tracker clean, but feel free to reopen if you still have issues!
