### ISSUE TITLE
YANK tries to solvate a system in LEaP with TIP4P-Ew even if TIP3P is used

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#776]
cc: https://github.com/choderalab/yank-examples/issues/61

We currently use `solvent_model: tip4pew` by default, but don't bother to check if the appropriate leaprc file is used or vice-versa. This leads to quite non-intuitive error messages when extra sites are added or missing when they are not expected.

**Comment by davidlmobley** [comment]
I seem to have run into this issue even though I'm specifying (or attempting to specify) to use gbsa -- I'm getting errors relating to "Could not find bond parameter for: EP - OW" in my log file. I ultimately traced this back to this leap.in being used:
```
# Load parameters
loadAmberParams data/setup/molecules/input_molecule/input_molecule.frcmod
source leaprc.gaff
source leaprc.protein.ff14SB
source leaprc.water.tip3p

# Load molecules
input_molecule = loadMol2 data/setup/molecules/input_molecule/input_molecule.gaff.mol2

# Solvate systems
solvateBox input_molecule TIP4PEWBOX 8.0 iso

# Check charge
check input_molecule

# Save prmtop and inpcrd files
saveAmberParm input_molecule data/setup/systems/hydration-tip3p/solvent1.prmtop data/setup/systems/hydration-tip3p/solvent1.inpcrd
savePDB input_molecule data/setup/systems/hydration-tip3p/solvent1.pdb

quit
```
so for some reason it's trying to use a TIP4PEW box with a tip3p leaprc. 

Presumably I have something wrong in my YAML, but it is not obvious what it is (I'm trying to adapt the yaml we had used for the FreeSolv experiments on Orion early this year), and I'm using a fresh conda install of yank, with the `ExperimentBuilder` approach for setup/running.

Here's what I have:
hydration_yaml = """\
---
options:
  minimize: yes
  resume_simulation: yes
  checkpoint_interval: 50
  timestep: %(timestep)f*femtoseconds
  nsteps_per_iteration: %(nsteps_per_iteration)d
  number_of_iterations: %(number_of_iterations)d
  temperature: %(temperature)f*kelvin
  pressure: %(pressure)f*atmosphere
  anisotropic_dispersion_cutoff: 9*angstroms
  output_dir: %(output_dir)s
  verbose: %(verbose)s

molecules:
  input_molecule:
    filepath: %(output_dir)s/input.smiles
    antechamber:
      charge_method: null

solvents:
  tip3p:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 8*angstroms
    ewald_error_tolerance: 1.0e-4
  gbsa:
    nonbonded_method: NoCutoff
    implicit_solvent: OBC2
  vacuum:
    nonbonded_method: NoCutoff

systems:
  hydration-tip3p:
    solute: input_molecule
    solvent1: tip3p
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip3p]
  hydration-gbsa:
    solute: input_molecule
    solvent1: gbsa
    solvent2: vacuum
    leap:
      parameters: [leaprc.gaff, leaprc.protein.ff14SB, leaprc.water.tip3p]

protocols:
  protocol-tip3p:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.75, 0.50, 0.25, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00]


  protocol-gbsa:
    solvent1:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]
    solvent2:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.00]
        lambda_sterics:        [1.00, 0.00]

experiments:
  system: hydration-%(solvent)s
  protocol: protocol-%(solvent)s
""" % options

with
```python

input_molecule = 'test.smi'

# Key settings to fill in in the template
timestep = 2 #femtoseconds
nsteps_per_iteration = 500 #Number of timesteps per iteration
# Will use 5000, but use 100 now for testing purposes...
#number_of_iterations = 5000 #How many iterations
number_of_iterations = 100 #How many iterations
temperature = 298.15 # kelvin
pressure = 1 #atmosphere
output_dir = 'data'
verbose = 'yes' # yes or no
solvent = 'gbsa' # gbsa or tip3p

options = {
    'timestep' : timestep,
    'nsteps_per_iteration' : nsteps_per_iteration,
    'number_of_iterations' : number_of_iterations,
    'temperature' : temperature,
    'pressure' : pressure,
    'solvent' : solvent,
    'verbose' : 'yes' if verbose else 'no',
    'output_dir': output_dir,
}
```

**Comment by davidlmobley** [comment]
I've determined that if I specify the solvent as `gbsa` in the YAML manually and remove everything relating to TIP3P, it works, but this still doesn't help understand what the problem is.

I also tried adding back in the TIP3P sections without actually using them -- e.g. specifying:
```
experiments:
  system: hydration-gbsa
  protocol: protocol-gbsa
```
and when I do so, I manage to trigger an error `yank.experiment.YamlParseError: System hydration-tip3p: Missing keys: 'phase2_path', 'phase1_path'` which is very opaque since (a) I'm not actually DOING anything with the TIP3P sections, and (b) neither the GBSA sections (which work) nor the TIP3P sections (which I'm not using) specify `phase1_path` and `phase2_path`.

@andrrizzi , any pointers?

**Comment by davidlmobley** [comment]
Ah, I figured that one out. It seems if I omit the section defining `tip3p` solvent, I get an error about missing `phase1_path` and `phase2_path`.

Honestly, I think it would be better not to give an error at all than to give an error which has nothing to do with the actual problem.

**More  importantly**: I seem to have uncovered an additional bug which is related but warrants a separate issue. I'll open one.

**Comment by jchodera** [comment]
@davidlmobley : Can you post a ZIP archive with a complete set of input files (YAML, SMILES input file) generated by your script? You've only posted a script fragment here, so we can't try to reproduce the whole thing.

**Comment by davidlmobley** [comment]
Well, it seems to be ANY input -- I get the same thing with any .mol2 from FreeSolv, as well as any smiles file. But see attached archive (I just posted the same in the other thread as well).

[Archive.zip](https://github.com/choderalab/yank/files/1443747/Archive.zip)

[test.smi.zip](https://github.com/choderalab/yank/files/1443749/test.smi.zip)

**Comment by jchodera** [comment]
OK, I'm able to use the `test.smi` with `setup_hydration.py` and LEaP is failing with
```
Could not find bond parameter for: EP - OW
```
Looking into this.

**Comment by jchodera** [comment]
The `solvateBox` leap command is simply using the wrong box:
```
solvateBox input_molecule TIP4PEWBOX 8.0 iso
```

**Comment by jchodera** [comment]
Looks like you just forgot to specify `solvent_model: tip3p` in the `tip3p:` section of `solvents:`:
http://getyank.org/0.18.0/yamlpages/solvents.html#solvent-model

The default is `tip4pew`. Just naming the section `tip3p:` isn't enough to get yank to use TIP3P---you also need to tell it that the `solvent_model:` is `tip3p`. The heading for each solvent block is just an arbitrary name.

**Comment by jchodera** [comment]
So, to be clear, I think you need to change
```YAML
solvents:
  tip3p:
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 8*angstroms
    ewald_error_tolerance: 1.0e-4
```
to
```YAML
solvents:
  tip3p:
    solvent_model: tip3p
    nonbonded_method: PME
    nonbonded_cutoff: 9*angstroms
    clearance: 8*angstroms
    ewald_error_tolerance: 1.0e-4
```

**Comment by jchodera** [comment]
I've confirmed this fixes the setup issues for me.

Aside from "better error messages", which is something we can definitely add, can you help us think of a better way to minimize these errors? I'd say our best bet is just to explicitly include `solvent_model:` in these examples so users can see they are supposed to change that.

**Comment by davidlmobley** [comment]
Always explicitly stating the solvent model would  make it clearer, yes.

I was really just trying to directly adapt the example you'd put together for the Yank cubes, e.g. https://github.com/oess/openmm_orion/commit/9bb2f55d416acae8b6f31647e918a520c624bc6e#diff-cdedf5c1907393a4a32c04a3bbd455daR47 . Possibly I pulled the wrong commit (maybe the one I pulled was problematic for the same reason).

**Comment by jchodera** [comment]
Sorry about that---that was quite some time ago, and @andrrizzi and @Lnaden have been making additions/changes to the YANK behavior since then. Wasn't this being travis-tested with nightlies to catch upstream changes that trigger failures?

What about using the current [freesolv example](https://github.com/choderalab/yank-examples/tree/master/examples/hydration/freesolv) as a template?

**Comment by Lnaden** [comment]
>   I get an error about missing phase1_path and phase2_path

Sorry about that, the error is related to #795. We have had related discussions about having a better error. That happens because all the possible valid schema syntax's fail, but it only reports the last error. We have ideas for making that better, but nothing concrete yet.
