### ISSUE TITLE
Ensure the ion of charged alchemical ligands is never restrained

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#785]
This thought occurred to me at our Merck meeting today. As restraint atoms are selected, we must make sure the counter-ion(s) for charged alchemical ligands are not restrained, otherwise we may see some very unexpected behavior.

**Comment by andrrizzi** [comment]
I'm almost entirely sure this is the case.

**Comment by Lnaden** [comment]
Can you point me at the code where this logic is enforced?

**Comment by andrrizzi** [comment]
When we [apply the restraint](https://github.com/choderalab/yank/blob/master/Yank/yank.py#L553-L554), we pass the `topography` and decide which atoms to restrain based on `topography.receptor_atoms` and `topography.ligand_atoms`, which don't include ions.

**Comment by Lnaden** [comment]
Awesome, thanks for that!

**Comment by andrrizzi** [comment]
np!
