### ISSUE TITLE
FlatBottom radius is stored as Angstrom and not cast to Nanometer

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#789]
https://github.com/choderalab/yank/blob/master/Yank/restraints.py#L1198-L1199

cc @andrrizzi

**Comment by Lnaden** [comment]
I think the spring constant is in the wrong unit system too. I can fix the problem this afternoon if you want

**Comment by andrrizzi** [comment]
I'd like to restart the calculations asap, so if you are working on it right now feel free to go ahead, otherwise if you have stuff to do I have no problem fixing it.

**Comment by Lnaden** [comment]
Im on it right now

**Comment by Lnaden** [comment]
Nevermind, the call to `addBond(x,y, P)` will cast any unit bearing quantity in the list `P` to the correct unit system. The conversion is handled implicitly
