### ISSUE TITLE
Testing optional dependencies, like OpenEye tools

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#80]
For now, we'll need to find a way to skip tests for optional dependencies (like OpenEye tools) on travis-ci.

In PR #79, I've added a method to check for OpenEye tool availability and skip the test if not found, but we need to find a way to skip doctests that require optional dependencies that are not installed.

@kyleabeauchamp suggests the SKIP feature (https://docs.python.org/2/library/doctest.html#doctest-options) might be metaprogrammed.

Sage seems to have a more elaborate doctest scheme:
http://www.sagemath.org/doc/developer/doctesting.html

See especially optional tests:
http://www.sagemath.org/doc/developer/doctesting.html#run-optional-tests
which seems to be our use case.

Continuing to investigate.

**Comment by pgrinaway** [comment]
If we really want to test code that includes the optional stuff, we can probably use EC2 or Jenkins, but IMO this is low priority.

**Comment by Lnaden** [comment]
I added a flag to the `yank selftest` command which runs the tests on the OpenEye install that things like `nosetests` won't run them, but the user can. Is this a sufficient solution to this problem?

**Comment by jchodera** [comment]
> I added a flag to the yank selftest command which runs the tests on the OpenEye install that things like nosetests won't run them, but the user can. Is this a sufficient solution to this problem?

What do you think about having `yank selftest` have two modes:

### Default mode (no command-line options specified)
Report on as many things of value as we can quickly test.
* Report YANK version
* Report which OpenMM platforms are available and any plugin load failures
* Report on whether OpenEye tools are installed (if so, which version) and whether license is available
* As we find more things that may be useful in debugging installations onsite, we can add those here.

### Extensive testing mode
If the user specifies `--nosetests`, run all `nosetests` to make sure everything is working all right in this installation.

I don't think the doctests are necessary to run, but we could also have a `--doctests` flag to run those.

**Comment by Lnaden** [comment]
Fixed by #489
