### ISSUE TITLE
The default integrator ends up being the OpenMM Langevin integrator.

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#803]
When `integrator_splitting` is specified, it gets set to `None` instead of `"V R O R V"` so the OpenMM Langevin integrator is chosen. I'll push a fix shortly.

**Comment by Lnaden** [comment]
What? Isn't the line in question this:
`integrator_splitting = phase_opts['integrator_splitting'] if 'integrator_splitting' in phase_opts else None`?

So if its set, it should pull it in, right?

**Comment by andrrizzi** [comment]
Correct, but if it's not set, it should set it to VRORV, not None (see [this line](https://github.com/choderalab/yank/blob/master/Yank/experiment.py#L205)).

**Comment by Lnaden** [comment]
Oh, So the line/block [here](https://github.com/choderalab/yank/blob/master/Yank/experiment.py?utf8=%E2%9C%93#L839) does not set the default options in their place?

**Comment by Lnaden** [comment]
That should work.

So I understand what you are doing [here](https://github.com/choderalab/yank/pull/797/files#diff-1957ca1a1cdd9d394cea46a4708af56eR298), you are reading the exiting MCMC move set and filling in the options as need be to overwrite? Does this change of the `integrator_splitting` from phase options to experiment options require a docs update?

**Comment by andrrizzi** [comment]
> So the line/block here does not set the default options in their place?

Correct! That's because `self._options` there doesn't contain defaults of other classes, so if you didn't specify `integrator_splitting` that line I linked above kind of "overwrote" the default to None.

> Does this change of the integrator_splitting from phase options to experiment options require a docs update?

Hmm, I don't think it should. I'll double check but the behavior should be identical.
