### ISSUE TITLE
Parallel molecule setup with Combinatorial tries to make directories over each other

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#808]
Self explanatory title.

When the `!combinatorial` is set for a single molecule, the new parallel setup code causes `os.mkdir` to be called on all directories, resulting in the problem observed it #807 and choderalab/yank-examples#70

Use the `abl-imatinib` example to reproduce

**Comment by andrrizzi** [comment]
Hmm, weird. This should not happen. A `!Combinatorial` flag should result in a different directory for each of the generated molecules, so they shouldn't try to recreate the same one. Will take a look tomorrow.
