### ISSUE TITLE
Find better way to generate residue names for ligands generated from SMILES

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#815]
Currently, we just use the first three letters of the molecule's name in the YAML script, but this can generate collisions with common residue names used for amino acids and solvent. The solutions are see are two:
1. Call everything with a standard name (e.g. `MOL`). This has the advantage of being very predictable from the user perspective.
2. Alternatively, we keep this scheme but we need to check that the generated name is not in the set of MDTraj common resnames that we use for selection in Topography. We still need to fall back to a standard resname if this is the case.

cc: choderalab/yank-examples#76

**Comment by jchodera** [comment]
Why do we rely on residue names for the molecules anyway?

If we called it `MOL`, what if we have a host-guest system where both molecules are small molecules? A numerical index like `000`, `001`, etc might be better.

**Comment by andrrizzi** [comment]
> Why do we rely on residue names for the molecules anyway?

Mostly to keep the logic consistent with the system files case, where the ligand has to be selected by a DSL string. I guess it's also the easier alternative, otherwise I think we would have to identify the different molecules from the tleap output based on bonds and select the atoms of the 1st/2nd molecule in the solvent/complex phase.

> If we called it MOL, what if we have a host-guest system where both molecules are small molecules? A numerical index like 000, 001, etc might be better.

Good point.
