### ISSUE TITLE
Compute statistical inefficiency of replica state index in analysis

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#817]
To add this capability to the analysis, I'm thinking about doing the following:
* Modify `ReplicaExchangeAnalyzer.generate_mixing_statistics()` to also return the result of `pymbar.timeseries.statisticalInefficiencyMultiple()` on the data (after discarding equilibration iterations).
* Modify `ReplicaExchangeAnalyzer.show_mixing_statistics()` and `notebook.HealthReportData.generate_mixing_plot()` to print this statistic right below the Perron eigenvalue and the state equilibration timescale.

Does this sound reasonable?

**Comment by jchodera** [comment]
Why not just add a separate function?

**Comment by andrrizzi** [comment]
I can do that too! We can have even both if we want.

I just thought that `generate_mixing_statistics()` sounds like an umbrella name for all statistics concerning state mixing. If we want to have two distinct functions, what if we rename `generate_mixing_statistics()` to something like `generate_transition_matrix()` and then have `show_mixing_statistics()`/`generate_mixing_plot()` print the results of both functions?

**Comment by jchodera** [comment]
Alternatively, we can have `generate_mixing_statistics()` return a `dict` so we can extend the statistics computed at a later time?

**Comment by andrrizzi** [comment]
Sounds good. What about a `namedtuple` instead of a `dict`? This way we get autocompletion, we avoid using hardcoded strings, and we can equally extend it later.

**Comment by jchodera** [comment]
Sure!
