### ISSUE TITLE
Extract trajectories fails to image molecules.

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#821]
Something changed in MDTraj and extracting the trajectory seems to fail with a bunch of
```
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'
```
I think we are passing `float64` positions to the `Trajectory` object. I'll push a fix soon.

**Comment by Lnaden** [comment]
I would be willing to bet something changed in `numpy` before `MDTraj`, which is related
