### ISSUE TITLE
Support for amber rst7 system files

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#838]
I've realized that to run the SAMPLing calculations I'll have to add support for `rst7` files as an alternative to `inpcrd`. This is already supported, but it needs to be allowed in the YAML syntax. I have a local fix ready. I'll push it tomorrow.

Question: do we need to enforce `phase1_path` and `phase2_path` to have the same type of input files (e.g., both phases have to use amber files)? The two phases are completely independent calculations so I'm tempted to remove this restriction. Any objection?

**Comment by jchodera** [comment]
No objections!
