### ISSUE TITLE
Make --jobid a 1-based id

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#839]
To run YANK with a job array, we have implemented the command line options `--jobid` and `--njobs`. Only schedulers usually use 1-based ids while YANK uses 0-based. We should probably use 1-based job ids for YANK too to avoid doing arithmetic in bash in the LSF script.

**Comment by jchodera** [comment]
If we just use jobid % njobs, isn't whether indexing starts at 0 or 1 irrelevant? We'll eventually cover 0..(njobs-1) regardless of whether jobid starts at 0 or 1.

**Comment by andrrizzi** [comment]
Good point! The only problem with allowing both is that no error will be raised if both job ids `0` and `njobs` gets started by mistake. If we are willing to turn this off, I can make the changes to allow both.

**Comment by jchodera** [comment]
> The only problem with allowing both is that no error will be raised if both job ids 0 and njobs gets started by mistake. 

I'm not quite sure I follow. Why would `0` and `njobs` start unless the user incorrectly specifies the number of jobs to `--njobs`? Do we expect they may not know how many jobs they're asking the scheduler to run?

**Comment by andrrizzi** [comment]
It just worries me that it takes only a typo to start the job with `bsub -J "arrayjob[0,16]" < script.sh` instead of `bsub -J "arrayjob[0,15]" < script.sh`, and the result could be the corruption of the netcdf file.

**Comment by andrrizzi** [comment]
To be clearer, in the example above I assume `njobs=16`.

**Comment by jchodera** [comment]
What about having YANK read the environment variables (to prevent typos) and adding a `--jobarray LSF` flag to instruct it to use those?

**Comment by andrrizzi** [comment]
That's a good idea, but I think there are no environment variables that we can use to figure out what is the index of the last job the user has submitted. I believe the only useful variable to which we have access is `LSB_JOBINDEX` (at least by taking a quick look at the [reference](https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_config_ref/lsf_envars_ref.html)).

**Comment by jchodera** [comment]
Looks like you're right.

**Comment by andrrizzi** [comment]
I'll go ahead with making this 1-based then. We can always extend it in the future to accept both schemes if we find a way to solve this problem.
