### ISSUE TITLE
Incorrect updating of parameters

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#846]
An evil, sneaky bug that we introduced with the Cerberus refactoring. For the leap parameters, we are using the schema:
```python
_LEAP_PARAMETERS_DEFAULT_SCHEMA = {'leap': {
    'required': False,
    'type': 'dict',
    'schema': _LEAP_PARAMETERS_SCHEMA,
    'default': {'parameters': []}}  # Default for if the parameter is missing
}
```
so we are assigning the same list object to every molecule by default. This means, for example, that after adding the antechamber `frcmod` file to the list of parameters of a molecule, we are effectively adding the same `frcmod` file to every molecule.

I'm thinking of switching to use a `default_setter` that creates a new list every time.

**Comment by Lnaden** [comment]
What? Can you give a more concrete example, or even psuedo-example of how this bug plays out with 2 molecules?

**Comment by andrrizzi** [comment]
The main problem occurs at [this line](https://github.com/choderalab/yank/blob/master/Yank/pipeline.py#L1385). We are adding the same file to every molecule since they share the same list object.

I've worked out a fix. I'll push later today after some testing.

**Comment by Lnaden** [comment]
so what you are saying is each molecule needs to use a copy of the `_LEAP_PARAMETERS_DEFAULT_SCHMEA` object so the `parameters` entry is not just an accumulating list of things which get appended from each molecule?

**Comment by andrrizzi** [comment]
Not a copy of the whole schema per se, but a copy of the default value `{'parameters': []}}` since it's a mutable type. I think that's the only instance in which we use a mutable type as a default value based on a quick scan anyway.

**Comment by Lnaden** [comment]
I think there are a couple other mutables in the schema, but they are wrapped in function calls so they get rebuilt per call anyways. This problem would also go away when we put in #824 i imagine, but there is no timeline for that so this should be fixed now
