### ISSUE TITLE
minor issue with extract-trajectory

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/yank#848]
This is fairly minor, but the `extract-trajectory` function gives the following message if you save a trajectory with the `.hdf5` extension: 

```
/Users/albaness/miniconda3/lib/python3.6/site-packages/mdtraj/formats/hdf5.py:198: UserWarning: The .h5 extension is recommended.
  warnings.warn('The .h5 extension is recommended.')
```

If you switch to the `.5` extension, you get this message: 

```
Traceback (most recent call last):
  File "/Users/albaness/miniconda3/lib/python3.6/site-packages/yank/commands/analyze.py", line 120, in dispatch_extract_trajectory
    save_function = getattr(trajectory, 'save_' + extension)
AttributeError: 'Trajectory' object has no attribute 'save_h5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/albaness/miniconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.18.0', 'console_scripts', 'yank')()
  File "/Users/albaness/miniconda3/lib/python3.6/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/Users/albaness/miniconda3/lib/python3.6/site-packages/yank/commands/analyze.py", line 79, in dispatch
    return dispatch_extract_trajectory(args)
  File "/Users/albaness/miniconda3/lib/python3.6/site-packages/yank/commands/analyze.py", line 122, in dispatch_extract_trajectory
    raise ValueError('Cannot detect format from extension of file {}'.format(output_path))
ValueError: Cannot detect format from extension of file ./Roeight_fb_state0.h5

```

Nothing is broken here, but you might get some confused users who see the first message and then switch the next time they use this feature, only to find out it doesn't work!

**Comment by Lnaden** [comment]
Thats actually a MDTraj error, which I agree is confusing

**Comment by Lnaden** [comment]
We should probably trap this extension input and raise a warning we are catching and mapping to a different extension since the MDTraj writer has a slightly different format output

**Comment by andrrizzi** [comment]
We should convert the code to use the `Trajectory.save()` function instead of using inspection to figure out which specific format to use. When I first wrote that, I think that wasn't available or I might have missed it when going through the API docs the first time.
