### ISSUE TITLE
Add additional "slots" for System objects for which energies will computed by no exchanges are allowed

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#85]
In order to implement the heterogeneous dispersion correction for explicitly solvated systems, we need to add support for additional fully-interacting OpenMM `System` objects with enlarged cutoffs for which potential energies will be computed each iteration but no exchanges allowed to take place.

**Comment by Lnaden** [comment]
I closed this since the issue put forward here is addressed by #483, however, if that is not enough, feel free to reopen
