### ISSUE TITLE
Add decorators for nosetests that are to be skipped on travis

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#86]
It would be easiest to use Python decorators to denote nosetests that should be skipped on travis because they are too time-consuming, such as  [this one](https://github.com/choderalab/yank/blob/master/tests/test_alchemy.py#L553).

**Comment by kyleabeauchamp** [comment]
This is partially implemented in #184 

The remaining part is to improve our tests to maximize coverage while using `@attr('slow')` to flag the things that are too slow for travis / jenkins.

**Comment by jchodera** [comment]
Any idea how this should work for test generators that `yield` test functions? Is there a way to check for the `slow` attribute?

**Comment by kyleabeauchamp** [comment]
No idea.  In the future, we might as well just factor out a helper function for running the test and then have two separate nose tests `test_slow()` and `test_fast()`, where the  slow version has a slow attribute tagged

**Comment by rmcgibbo** [comment]
I don't think you can add attributes to the individual tests `yield`ed by a test generator. You could raise a `SkipTest` inside the `yield`ed test though.

**Comment by jchodera** [comment]
@rmcgibbo : Excellent idea.  That approach might work well.

Another possibility: Looking through [the code for the `@attr(name)` decorator](http://nose.readthedocs.org/en/latest/plugins/attrib.html), all it does is essentially
```python
setattr(ob, name, True)
```
That means we can just change our test generators from this idiom
```python
for thing in things:
   f = partial(check_function, thing)
   f.description = "Testing %s..." % thing.name
   yield f
```
to this
```python
for thing in things:
   f = partial(check_function, thing)
   f.description = "Testing %s..." % thing.name
   if thing.is_slow: setattr(f, 'slow')
   yield f
```
Of course, it would be better if we could just check if the `slow` attribute is set by nose and skip even generating the test.

**Comment by Lnaden** [comment]
Right now travis tests skip the `@attr(`slow`)` decorated functions with the -a !slow` flag. Are there other functions we want to mark or is this an acceptable solution for now?

**Comment by andrrizzi** [comment]
I think this is a good solution. We could run slow tests on jenkins using the flag `-a 'slow'` to cover everything.

**Comment by Lnaden** [comment]
Is there any outstanding issue here or can we close this?

**Comment by jchodera** [comment]
As long as the tests are running in the travis timeframe allowed, you can close.

**Comment by Lnaden** [comment]
Done
