### ISSUE TITLE
Optimize chunksizes in Reporter

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#860]
For the non-checkpoint file, `Reporter` still uses chunksizes of 1 iteration, which is going to slow down writing unnecessarily. We can easily make these 10 without worry, but the ideal number would be to set them equal to the checkpoint write interval.

**Comment by jchodera** [comment]
@Lnaden points out I can use `Reporter._checkpoint_interval` for this purpose!

**Comment by Lnaden** [comment]
Fixed by #912, closing.
