### ISSUE TITLE
Remove the `install_requires` from the `setup.py` file

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#876]
Since YANK cannot be installed purely by `EasyInstall` or `pip` because of dependencies, I propose removing the `install_requires` keyword, or at least comment it out for documentation purposes. This would let us reduce the number of items on the `meta.yaml` `requirements: build` section and speed up build times.

**Comment by jchodera** [comment]
That sounds reasonable, since we essentially make `conda` installation our only supported installation mechanism (except for developers).

**Comment by andrrizzi** [comment]
Implemented in #913 .
