### ISSUE TITLE
Reconsider integration of new repex

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#88]
It would be really useful to get GHMC working as an alternative to Langevin, but we may need to track down precision issues on `CUDA` and `OpenCL` platforms first.

**Comment by pgrinaway** [comment]
I'd imagine this is not a 1.0 issue, but I want to check.

**Comment by jchodera** [comment]
Not a 1.0 issue!

**Comment by Lnaden** [comment]
This will be refactored with the API changes and eventually resolved post 1.0

**Comment by andrrizzi** [comment]
We now support general MCMC moves.
