### ISSUE TITLE
Unbiasing of the harmonic restraint

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#882]
This is my plan for implementing the harmonic restraint unbiasing in the analysis.

1. Parse solute-only trajectory and recompute the centroid distances and restraint energies.
2. After decorrelating, discard from the analysis all the frames with restraint energy greater than a threshold. The function will have an argument defining it, but **what should the default value be?** 2kT? 3kT?
3. Recompute the standard state correction by integrating a different potential that is the same as the restraint until it gets to the threshold, at which point it goes to infinity.
4. If the simulation used the anisotropic long-range dispersions correction, subtract the restraint energies to that state; otherwise, create a new state for MBAR that has the energy of the lambda=1 state minus the restraint energy.

I'd implement this in an external script for now (starting from [this one](https://github.com/choderalab/yank-validation/blob/temp/debug_scripts/debug_hostguest.py), which is almost ready) since there are so many changes going on in the analysis, and I'd like to avoid re-doing the same work twice. Once the new analysis API will be merged into `master`, I'll bring it into the analysis.

**Comment by jchodera** [comment]
I think we want to use a structural definition of what the "bound" state is, and this may have little to do with the value of the restraint energy (which simply controls how much statistical error is picked up in reweighting). How hard would it be to allow the user to specify a receptor atom selection and closest heavy atom distance cutoff during analysis time to compute whether or not each frame should be included in the unbiasing? This would allow the user to only analyze snapshots where the ligand is *near* the receptor, or *near* some binding site residues, which could be very useful.

**Comment by andrrizzi** [comment]
> I think we want to use a structural definition of what the "bound" state is, and this may have little to do with the value of the restraint energy (which simply controls how much statistical error is picked up in reweighting).

Sorry, I thought that unbiasing the restraint and reducing the statistical error of reweighting was everything we needed urgently. Implementing also a new definition of the bound state will probably take few days.

I talked about threshold on the energy because
- With the current structural definition of the bound state (i.e. the distance of the centroids), energies and distances are in a 1-to-1 correspondence;
- Having a threshold on the energy makes it very easy to decide which samples have to be discarded because they increase the statistical error.

But I can set the threshold based on the distance as well.

> This would allow the user to only analyze snapshots where the ligand is near the receptor, or near some binding site residues, which could be very useful.

I agree this would be super helpful with the flat-bottom restraint! Probably a little less for harmonic-restraint simulations (unless the spring constant is very low). A couple of thoughts about the new definition of the bound state:
- I think computing the heavy atom distance cutoffs should be fast. I need to do some benchmarking, but what worries me a little is the computation of the average volume of the bound state for the standard state correction.
- Should we use a directional distance (e.g. negative if it points inside the binding site, and positive if it outside)? Otherwise, I'm not sure that a definition of the bound state based on closest heavy atoms would be less arbitrary of the one we are using right now.
- We should figure out if it is possible/makes sense to encapsulate this new definition of bound state in a separate `Restraint` class that could be used also at runtime (beside using it at the analysis stage). This would allow us to easily parallelize these calculations across the MPI processes.

**Comment by jchodera** [comment]
@andrrizzi : I think you're right that there's enough value in simply unbiasing the harmonic restraint given a user-specified energy threshold that we should implement this for urgently-needed projects (Musashi, Merck) and then spec'ing out a more complete contact-based definition for analysis later.

**Comment by davidlmobley** [comment]
I'm just writing here to spectate, and also to note that we're enthusiastic about both aspects of this too (shorter-term reweighting fix, longer-term structural definition).

**Comment by jchodera** [comment]
We're also working on a new restraint type that uses the ligand RMSD to define the bound pose. This will allow us to, say, impose a 2.5A ligand RMSD cutoff in this reweighting step.

**Comment by andrrizzi** [comment]
This was implemented in #915 .
