### ISSUE TITLE
Remediate OpenMM version dependency tracking in setup.py now that we will use conda

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#93]
There's a bunch of code in `setup.py` we probably don't need if we're using version-specific dependencies via `conda`:
https://github.com/choderalab/yank/blob/master/setup.py#L63-L70

Will deal with this later.

**Comment by jchodera** [comment]
It is now:
https://github.com/choderalab/yank/blob/master/setup.py#L112-L146

Should this now look like the [`setup.py` from MDTraj](https://github.com/mdtraj/mdtraj/blob/master/setup.py)?

**Comment by pgrinaway** [comment]
Resolved by #185
