### ISSUE TITLE
Issues with is_openeye_installed on ORNL Titan

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#945]
[`utils.is_openeye_installed('oeomega')`](https://github.com/choderalab/yank/blob/master/Yank/utils.py#L1216) fails on ORNL Titan with miniconda Python 3.6 because [`module = importlib.import_module('openeye', tool)`](https://github.com/choderalab/yank/blob/master/Yank/utils.py#L1256) succeeds, but does not return the correct submodule `openeye.oeomega`. The alternative syntax [module = importlib.import_module('openeye.' + tool)](https://github.com/choderalab/yank/blob/master/Yank/utils.py#L1258) works, however. Can we simply use this other syntax by default?

**Comment by andrrizzi** [comment]
I'm on it! I don't remember writing this code, but it should be easy to fix!

**Comment by Lnaden** [comment]
i wrote that code. The call to `utils.is_openeye_installed` only returns a `True` or `False`, not the module itself. What is the error you see on ORNL Titan, and is it only on Python 3.6 because I thought the first call under the `try:` works on Python 2.7 and 3.5+

**Comment by Lnaden** [comment]
Also, is it only on ORNL Titan? Because if its a general Py36 error, I am surprised we have not seen it sooner

**Comment by andrrizzi** [comment]
Whops! Sorry, I worked out a fix in the meantime, but feel free to change that PR. @jchodera let me know if that branch works.

**Comment by Lnaden** [comment]
If it fixes the issue, its fine. I think we should make sure this works on Py27, 35 and 36. I'm not sure if this function is tested on all of them though.

**Comment by jchodera** [comment]
> If it fixes the issue, its fine. I think we should make sure this works on Py27, 35 and 36. I'm not sure if this function is tested on all of them though.

Didn't we discontinue python 2.7 support some time ago?

**Comment by Lnaden** [comment]
Oh right, I got my package dependencies crossed with openmmtools/openmoltools. Py35 and 36 only!
