### ISSUE TITLE
Sampler's run method doesn't work correctly when the n_iteration argument is not specified

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#954]
If `n_iterations` is `None`, the current algorithm compute incorrectly the maximum iteration, and it run for a shorter time than specified (if it runs at all). This affects the ability to resume through the API, although it doesn't affect resuming through the YAML interface since we always pass `n_iteration`.

I'll open a bugfix PR soon.

**Comment by Lnaden** [comment]
`run` should fail if no iterations are provided to it, correct? What is the use case for executing a run without a number of iterations?

**Comment by andrrizzi** [comment]
Sorry, by `n_iterations` I mean the argument in `Sampler.run(n_iterations=None)`. If `n_iterations` is not provided, the sampler should run up to `sampler.number_of_iterations`.
