### ISSUE TITLE
OpenMM DeviceIndex selection

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#967]
Hi there,
 
For different reasons I cannot use the CUDA_VISIBLE_DEVICES flag to mask GPUs when the CUDA platform is in use. I wonder if it would be possible to expose in YANK the OpenMM "DeviceIdex" property to select which GPU to use. In addition, I wonder if Yank has been tested on the latest OpenMM release 7.2.

Thanks a lot,
Gaetano

**Comment by andrrizzi** [comment]
>  I wonder if it would be possible to expose in YANK the OpenMM "DeviceIdex" property to select which GPU to use.

We plan on doing that (see #689). It's not high-priority right now, but you can start YANK from the Python interface and configure it with something like
```python
from simtk import openmm
from yank.experiment import ExperimentBuilder

openmm.Platform.GetPlatformByName(platform_name).setPropertyDefaultValue('DeviceIndex', 0)
exp_builder = ExperimentBuilder('path/to/script.yaml')
exp_builder.run()
```

> I wonder if Yank has been tested on the latest OpenMM release 7.2.

Yes. I think we've been running several simulations with 7.2 now.

**Comment by Lnaden** [comment]
A couple of quick questions to extend on @andrrizzi's comment:

1. Are you running this locally or on a cluster?
2. How are you checking the GPU's being used (e.g. `nvidia-smi` or some other means)
3. Are you running YANK with MPI or in serial?

**Comment by nividic** [comment]
Hi there, thanks a lot fro the prompt reply. The @andrrizzi solution should be enough for what I'm trying to do, Thanks a lot
@Lnaden 
I'm using the OpenFloe floe engine to run locally Yank. Unfortunately, a race condition happens if I try to set the CUDA_VISIBLE _DEVICES with the floe engine. I'm using nvidia-smi to check the gpu in use. We are using Yank serially no MPI involved.
Thanks again

**Comment by andrrizzi** [comment]
Glad that solves your problem. I'll close the issue to keep the tracker somewhat clean, but feel free to reopen if you have more problems.
