### ISSUE TITLE
Speed up Analysis by Allocating more to Online

### ISSUE THREAD

**Issue by Lnaden** [choderalab/yank#975]
The analysis per-ligand time is very slow (1hr+ depending on states and samples)

We can speed this with a couple of things:
1. Allocate more to doing analysis online and having the `analyze` scripts try to read that data if present
2. Reducing the number of calls to the `timeseries` module to get the autocorrelation time and number effective samples as a function of iteration.

Specifics and details can be worked out through this issue

**Comment by jchodera** [comment]
Closing this in favor of two separate issues.
