### ISSUE TITLE
Improve `yank analyze` integration with online analysis

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#979]
To speed up analysis and user experience with analysis in general, we want to rely more on online analysis.

To help do this, we want to:
* Enable online analysis by default, minimizing its cost as much as possible by using a larger checkpoint interval
* Have `yank analyze` pull from the online analysis data by default, adding a flag to force recomputation if desired

**Comment by Lnaden** [comment]
For a basic layout of what I want to do for this

* Expand `online_analysis` to allow user to specify where the free energy difference should be measured from:
    * Expanded cutoff state end-points (default)
    * Sampled end-states (fall back if no unsampled states specified)
    * User-specified state indices
* Set `online_anlaysis` to be `True` with a min number of iterations to be 250 or 500. Kind of one of those play-by-ear numbers.
* Set the checkpoint interval to be 250-500 as well by default
    * I am worried about this because we have chunksize tied to checkpoint interval. If we make this too big, data corruption will cause more loss.
    * With SAMS, I think the chunksize problems will be minimal and we can circle back around to that and relax chunksize to be a function of checkpoint interval rather than exactly the checkpoint interval in the future
* Change analysis dependency trees: 
    * If you only need the end-state free energy: just get the free energy from file unless forced
        * This would require online analysis to compare unsampled states, see first top-level bullet
    * If you need state-wise analysis (e.g. mixing) or anything more complex, pull the stored state weights (`f_k`), unless forced
    * If no online analysis present or forced, proceed as current.

**Comment by Lnaden** [comment]
Other thoughts

* Set the target free energy error to 0 (only number of iterations will stop simulation) by default

An idea @bas-rustenburg had was to have either a constantly updating Jupyter notebook on the side which plots the free energy over time trace. Or have something like `yank status` also print out the free energy last reported. The former may have some issues if the user opens the file at the same time the simulation tries to write. but this can also be implemented later.
