### ISSUE TITLE
Robust backtracking when NaNs are encountered during simulation

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#983]
Right now, SAMS simulations can still die due after the number of attempts at recovering from NaNs are exhausted.

We can use the infrastructure implemented to address #977 to backtrack to the last good checkpoint and try to resume. If that still fails, we mark that checkpoint as bad and back up again.

**Comment by jchodera** [comment]
I've observed that, despite simulations failing with `CRITICAL` NaN failures, resuming them often allows them to continue to progress without trouble from the last saved checkpoint. I think this backtracking feature will be really useful in ensuring good throughput for our benchmarks, so I've put it on the next bugfix milestone.

**Comment by andrrizzi** [comment]
This was implemented in #977 .
