### ISSUE TITLE
Randomizing initial ligand positions

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#99]
For simulations started from AMBER `prmtop/inpcrd` files, it will only be possible to randomize ligand positions within YANK for implicit solvent simulations.  For explicit solvent simulations, this would cause overlap with solvent molecules that would prevent some near-fully-interacting alchemical states from running stable simulations.

Should we permit this option to be retained, throwing an exception if applied to explicit solvent simulations?  Or should we ditch it?

**Comment by pgrinaway** [comment]
Can we generate a warning if the users does this? If that seems annoyingly verbose, maybe we should just prohibit this combination of options.

**Comment by jchodera** [comment]
If the user requests `--randomize-ligand` for explicit solvent, we don't randomize the ligand, but *do* issue a warning via PR #203.
