### ISSUE TITLE
Restraining the solute for hydration free energy calculation

### ISSUE THREAD

**Issue by markhallen369** [choderalab/yank#993]
Hi!  I was wondering if there is a way to perform hydration free energy calculations with a restraint to keep the solute from moving significantly?  I am interested in studying the hydration free energy as a function of the solute's conformation, which would require sampling conformational space only for the solvent.

**Comment by andrrizzi** [comment]
Hi @markhallen369 . YANK has no support to add restraints in hydration free energy calculations through the YAML interface, but there are a couple of workarounds.
1) You prepare an OpenMM System that include your restraint, save it as an XML, and use it as an input file in the YAML script.
2) Use a normal YAML script for a hydration free energy and use the API to add a restraint after an experiment has been built. Something like
```python
from yank.experiment import ExperimentBuilder

exp_builder = ExperimentBuilder('path/to/yaml/script.yaml')
for experiment in exp_builder.build_experiments():
    for phase in experiment.phases:  # Solvent and vacuum phases.
        system = phase.thermodynamic_state.system
        # TODO: Add here your restraint forces to system.
        phase.thermodynamic_state.system = system
    experiment.run()
```

**Comment by jchodera** [comment]
@markhallen369 : Did this work for you?

**Comment by markhallen369** [comment]
Yes, thanks!!
Mark
